### ISSUE TITLE
Tidsafhængig validering

### ISSUE THREAD

**Issue by MartinHylleberg** [scandihealth/lpr3-docs#1]
Det er uklart i forbindelse med indberetnings vejledningen hvorledes tidsafhængig validering vil foregå.
**Eksempel**: Hvorledes vil valideringen forholde sig til en kontakt hvor der skal være en resultatindberetning inden for 7 dage. Kontakten vil her være valid ved indberetningstidspunktet, men invalid efter 7 dage. 

- Hvad vil validerings services svare ved synkron validering?

- Hvordan bliver vi informeret når kontakten skifter status fra valid til invalid?

**Comment by jkiddo** [comment]
1.  I svaret vil være indeholdt en warning med et tidsstempel for hvornår det vil være en error. Eksempel på dette vil blive skrevet til dokumentationen.
2. I bliver ikke aktivt notificeret når kontakten skifter fra valid til invalid da man jf. 1) er blevet oplyst om hvornår dette er tilfældet.

**Comment by MartinHylleberg** [comment]
[Supported Reporting](https://scandihealth.github.io/lpr3-docs/aspects/index.html#supported-reporting-strategies) afsnitter siger følgende:

>  If errors are found at level 3 in the given asynchronous submission the error(s) will be reported in a prior-to-submission designated folder, accessible by SFTP in the same ebXML-format as used in IHE XDR.

Vil den invalide kontakt begynde at optræde her efter at den er skiftet til invalid?

**Comment by jkiddo** [comment]
ja
