### ISSUE TITLE
Effective time: mismatch between examples and specification?

### ISSUE THREAD

**Issue by graugaard** [scandihealth/lpr3-docs#10]
In sveral examples [here](https://scandihealth.github.io/lpr3-docs/examples/index.html#examples-from-selected-scenarios) (e.g. [Indberetning af sletning af procedure uden kontakt](https://scandihealth.github.io/lpr3-docs/examples/Removal.Procedure.xml) and [Indberetning kun med forløbselement](https://scandihealth.github.io/lpr3-docs/examples/EpisodeOfCare.xml)), there is an effectiveTime tag (line 10) right after the title tag. However, the specification at [art-decor](http://art-decor.org/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.71&effectiveDate=2017-09-13T00:00:00&language=en-US) does not include this.

Is if safe to assume that the effectiveTime tag is only an example artifact and not a part of the official specification?

**Comment by jkiddo** [comment]
The specification is underpinned by the MedCom standard which then transitively requires the use of effectiveTime. See http://art-decor.org/art-decor/decor-project--medcom-

**Comment by graugaard** [comment]
Then what is the difference between author time and effective time?

As I read from the [medcom doc](https://www.medcom.dk/media/4330/dk-cda-header.pdf), section 4.4, it seems that perhaps author time is when one sat down and started to write the document, while effective time is the moment it is completed. But then they are very likely the same since this is done by computer.

Author time could also be interpreted as the moment any contact is made between the patient and the healthcare provider, or just when any treatment starts. But then what time to use, considering that for example there is the possibility of including multiple episode of cares, each which could have different time stamps.

**Comment by jkiddo** [comment]
From the CDA R2 standard:

> 4.2.1.4 | ClinicalDocument.effectiveTime
> Signifies the document creation time, when the document first came into being. Where the CDA document is a transform from an original document in some other format, the ClinicalDocument.effectiveTime is the time the original document is created. The time when the transform occurred is not currently represented in CDA.
> 

Start and end time of the Episode of Care is stated in the act.effectiveTime - see http://art-decor.org/art-decor/decor-templates--lpr-?id=1.2.208.176.7.1.10.80&effectiveDate=dynamic
