### ISSUE TITLE
Error severity in LPR3 RegistryResponse

### ISSUE THREAD

**Issue by jbraschler** [scandihealth/lpr3-docs#101]
Schematron and INTEGRITY_CHECK validation technically have the capability to return "Warnings" in addition to "Errors" that will presumably prevent the submission from being accepted. The way the documentation is currently written implies but doesn't actually state that the only type of error that will ever have a severity value of urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning will be BUSINESS_RULE errors. Is that correct, or will there potentially be schematron and INTEGRITY_CHECK warnings as well?

**Comment by TueCN** [comment]
Currently there are no XSD, SCHEMATRON or INTEGRITY_CHECK RegistryErrors with severity Warning.

However, we cannot guarantee that there will never be added any non-BUSINESS_RULE warnings, please plan accordingly.

Although if any XSD, SCHEMATRON or INTEGRITY_CHECK Warnings _were_ to be added, I think the reasonable approach would be that Warnings do **not** prevent a submission from being accepted. This means you can choose to ignore warnings, if you are not interested in the information they provide.
