### ISSUE TITLE
Accumulated Error List

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#104]
We have read the documentation of the accumulated error list and it states that: "The list is updated at midnight."

Is there a good reason for choosing midnight or could it be later?

I guess no secretaries are waiting for the error list before morning, e.g. 6 a.m. Hence reporters will have more time to finish reporting.

**Comment by jonigkeit** [comment]
Escalating warnings, i.e. warnings that become error if left untreated, have an errorBy property, which is a start of day in the Copenhagen timezone. Therefore the list I updated a midnight.

**Comment by jkiddo** [comment]
@RasmusThernoe - I think this is something you address to the the steering committee as it does require some changes - and if I understand you correctly, it changes the view of how time/dates are perceived by the system contra its users.

**Comment by RasmusThernoe** [comment]
OK - I have raised the suggestion to SDS.

**Comment by KirstenLHSDS** [comment]
This has been discussed with the project steeing group and with DXC (proposal of change of time). Will be changed, most likely from midnight till 02.00, but SDS will do a round with the regions

**Comment by smunck** [comment]
The time has been changed from midnight till 02:00.

**Comment by KirstenLHSDS** [comment]
We consider this closed and notes that the documentation must be updated.

**Comment by TueCN** [comment]
Documentation has been updated.
See https://scandihealth.github.io/lpr3-docs/interface/accumulated-error-list/index.html#schedule
