### ISSUE TITLE
Reporting using java seal

### ISSUE THREAD

**Issue by CgiMofr** [scandihealth/lpr3-docs#108]
We will probably be using the java version of the Seal libraries 
when reporting a ClinicalDocument.
Is there a recommeded version of Seal from www.digitaliser.dk use ?

Scandihealth has created a repository 
https://github.com/scandihealth/seal.java.

Is this to be used instead of the libraries from www.digitaliser.dk?

**Comment by jonigkeit** [comment]
DXC neither recommends nor advises against using the java version of the Seal librabies.

**Comment by jonigkeit** [comment]
@CgiMofr if you have no further comments please close this issue.
