### ISSUE TITLE
realmCode

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#11]
The realmCode of the ClinicalDocument is defined by CDA as a CS datatype, so it should only have a code attribute. The art-decor site require a codeSystem attribute for this, but if that is included we get the following error from the schematron:
Engine name: ISO Schematron (XSLT 2.0)
Severity: error
Description: dtr1-2-CS: cannot have codeSystem (not(@codeSystem) / error) [assert]
Start location: 3:55

If we don't include a codeSystem for the realmCode, we get this error:
Engine name: ISO Schematron (XSLT 2.0)
Severity: error
Description: (DKEpisodeOfCareSummariesDocument): The value for @codeSystem SHALL be '1.0.3166.2.2.2'. (string(@codeSystem)=('1.0.3166.2.2.2') / error) [assert]
Start location: 3:27
URL: http://art-decor.org/art-decor/decor-templates--lpr-?id=1.2.208.176.7.1.10.71

Given the CS datatype of realmCode in CDA, it seems like requiring the codeSystem is an error, but please confirm how we should resolve this issue.

**Comment by jkiddo** [comment]
Affirmative, this is a bug. realmCode should only have the code attribute. Fix will be applied ASAP

**Comment by cjonigkeit-csc** [comment]
Fixed in preproduction [DK Episode Of Care Summaries Document](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.71).
Awaiting deployment to production.
