### ISSUE TITLE
NameFormat is required for Attribute in HsuidHeader segment

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#110]
**This issue is blocking.**

After I have read the documentation for the HsuidHeader I got from #45:
https://www.nspop.dk/download/attachments/39942568/IFS0018%20Healthcare%20Service%20User%20Identification%20Header.docx?version=1&modificationDate=1459240284254&api=v2

I can see the NameFormat XML-attribut are marked as "_Not Used_" for multiple attributes e.g. "nsi:OrgResponsibleName" and "nsi:UserType". But if I look at hsuid-1_1.xsd from:
https://github.com/scandihealth/lpr3-docs/blob/master/schema.definitions.zip

I can see the following XSD rule which marks the "NameFormat" attribute as required:
```xml
  <xs:element name="Attribute">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="AttributeValue" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="Name" type="tns:nameConstraint" use="required"/>
      <xs:attribute name="NameFormat" type="tns:subjectIdentifierType" use="required"/>
    </xs:complexType>
  </xs:element>
```

So my question is what value should I use for "NameFormat" when the documentation specify "_Not Used_" as in e.g. "nsi:OrgResponsibleName" and "nsi:UserType"?

**Comment by jkiddo** [comment]
In agreement with SDS we will be deprecating the use of the HSUid header within the next to weeks. Stay tuned for details regarding the exact point in time.

**Comment by DaveSS** [comment]
Is this going to be a breaking change for the connectivity using the HsuidHeader that we have already established with LPR? In other words, will we need to strip out the HsuidHeader information we are currently sending once the HsuidHeader is deprecated, or will LPR just ignore any information sent in the HsuidHeaderbe for backward compatibility?

**Comment by jkiddo** [comment]
It will be ignored

**Comment by jkiddo** [comment]
So it will be backward compatible

**Comment by jkiddo** [comment]
Aka nonbreakning

**Comment by jkiddo** [comment]
@JacobBangSSE - HSUid is now ignored
