### ISSUE TITLE
medcom:CareProviderID and XDR/CDA authorInstitution conformance problems

### ISSUE THREAD

**Issue by TueCN** [scandihealth/lpr3-docs#111]
[DGWS](https://www.medcom.dk/standarder/webservice-standarder/den-gode-webservice) specifies that the `medcom:CareProviderID` SAML Attribute identifies the healthcare organization that the user identified in the `UserLog` and system identified in the `SystemLog` belongs to. 

DGWS specifies that the value of medcom:CareProviderID can be of the types:
- medcom:cvrnumber
- medcom:pnumber
- medcom:skscode
- medcom:ynumber
- medcom:communalnumber
- medcom:locationnumber
- medcom:other
---
Currently,
- LPR expects that the AttributeValue of `medcom:CareProviderID` is a CVR number (regardless of the specified `NameFormat`) 
  - We want to allow the following `NameFormat` types whose values maps to a single SOR id:
    - medcom:cvrnumber
    - medcom:pnumber
    - medcom:skscode
    - medcom:ynumber
    - medcom:locationnumber
---
We also want to add new constraints to ensure the quality of the submissions:
- The (decoded) root+extension values entered in the XDR metadata field authorInstitution must be the same as entered in the CDA metadata field `author/assignedAuthor/representedOrganization/id`
- The authorInstitution must be a SOR id (covered by #102) and must identify a SOR unit that is the same or a sub unit of the SOR unit identified by medcom:CareProviderID

**Note** This means that there will be no restrictions or assumptions (besides Schematron enforced ones) about the value entered in the CDA metadata field  `custodian/assignedCustodian/representedCustodianOrganization`, but please note that the value is stored in the registry in association with the submission.

**Comment by jkiddo** [comment]
@thor-schliemann 

Ain't that was is stated in the spec, section 2: http://svn.medcom.dk/svn/releases/Standarder/DGWS/Dokumentation/BILAG%20-%20Den%20Gode%20Webservice_1.0.pdf ?

**Comment by jkiddo** [comment]
![dgws-snippet](https://user-images.githubusercontent.com/211696/40431318-7a90ec0e-5ea7-11e8-8986-0d7c622983ec.PNG)

**Comment by jkiddo** [comment]
As decided by SDS, only medcom:cvrnumber in medcom:CareProviderID will be supported by the service as is the current functionality. Documentation will be updated to reflect this. No semantic changes will be made.

**Comment by jkiddo** [comment]
See 8bfd290
