### ISSUE TITLE
Security level of DGWS

### ISSUE THREAD

**Issue by CgiMofr** [scandihealth/lpr3-docs#112]
When using the lpr3 webservices, which security level from MedCom's DGWS should be used ?

**Comment by TueCN** [comment]
> Use of this service mandates proper use of DGWS v1.0.1 using VOCES/FOCES rules Level 3.

https://scandihealth.github.io/lpr3-docs/aspects/index.html#security

**Comment by CgiMofr** [comment]
Thank you for the answer and the links. :-)
