### ISSUE TITLE
Deploys do not comply with the interface guide

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#114]
There seems to be a pattern with new deploys on tuesday around 1 p.m.

This does not comply with the interface guide which specifies:

- As such DXC may deploy new builds on a **nightly** basis.
- New deployments will be notified through GitHub no later than end of business day before **nightly** deploy.

(https://scandihealth.github.io/lpr3-docs/testenvironment/index.html#nightly-build-deployments)

We would very much like the interface guide to be respected - deploys during working hours have hit our development, system testing and even a customer demonstration.

**Comment by TueCN** [comment]
**RESOLUTION**
[The guide](https://scandihealth.github.io/lpr3-docs/testenvironment/index.html#deployments) has been updated to reflect current practices.
