### ISSUE TITLE
Procedure documentation inconsistency

### ISSUE THREAD

**Issue by MartinHylleberg** [scandihealth/lpr3-docs#116]
Hi

The reporting of procedure are described in 2 places:
[The FAQ](https://scandihealth.github.io/lpr3-docs/faq/index.html)
and 
[Notes on the use of HL7 CDA elements in a danish setting](https://scandihealth.github.io/lpr3-docs/aspects/index.html#notes-on-the-use-of-hl7-cda-elements-in-a-danish-setting)

In the FAQ it is specified that we should use DK Procedure Act, DK Procedure Observation and DK Procedure Procedure, however in the "notes on the use of HL7 CDA" section in the reporting guide an update have been added specifying that we only need to use DK Procedure Procedure to do the reporting (and as I read it, we will not be able to use neither DK Procedure Act nor DK Procedure Observation?).

As it is easy to only see one or the other, the FAQ should be updated to reflect the update in the reporting guide (which I assume is the correct one.)

This issue is not blocking

**Comment by jkiddo** [comment]
Correct - it seems to be misleading. We will fix this ASAP

**Comment by jkiddo** [comment]
The FAQ is now alligned with what is stated in the documentation.
