### ISSUE TITLE
Inconsistence in the interface guide: Are there three or four error levels? 

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#117]
At https://scandihealth.github.io/lpr3-docs/aspects/index.html#what-rules-apply-and-what-errors-can-be-reported-and-how four error levels are described.

At https://scandihealth.github.io/lpr3-docs/aspects/index.html#service-endpoint-setup only three error levels are described.

**Comment by jkiddo** [comment]
Documentation updated: 6fa4a48

**Comment by RasmusThernoe** [comment]
Thank you.
