### ISSUE TITLE
usablePeriod element in addr is misspelled 

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#12]
Including the element addr/usablePeriod as specified by art-decor causes the following schematron error since usablePeriod is not defined as part as the addr element:
Engine name: ISO Schematron (XSLT 2.0)
Severity: warning
Description: dtr1-8-AD: empty address particles should not be present. (*[not(@nullFlavor or self::hl7:useablePeriod)][normalize-space(.)=''] / warning) [report]
Start location: 19:19

The correct spelling of the period element in the CDA AD datatype is "useablePeriod". The lack of 'e' in the art-decor specification is causing problems We also encounter a schematron error if we use the correct useablePeriod spelling:
Engine name: ISO Schematron (XSLT 2.0)
Severity: warning
Description: (DKAlternativelyIdentifiedPatientRole)/d27130e38-true-d27235e0: this element 'useablePeriod' is not defined, or not defined with this content. This may concern the templateId, code or id. (rule-reference: d27130e38-true-d27235e0) (not(.) / warning) [assert]
Start location: 26:32
URL: http://art-decor.org/art-decor/decor-templates--lpr-?id=1.2.208.176.7.1.10.107

Please advice us on how this should be resolved.

**Comment by jkiddo** [comment]
Affirmative, this is a bug. Fix will be applied ASAP
