### ISSUE TITLE
Using hl7:targetSiteCode in wrong CDA R2 root

### ISSUE THREAD

**Issue by Remcovanderwerf** [scandihealth/lpr3-docs#120]
Hi,

I am currently working on/developing the translation from the DOL/LPR3 format to CDA R2 standard on Cloverleaf.

At the moment I am working on the following template: [link](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?id=1.2.208.176.7.1.10.25&effectiveDate=dynamic)
Here I found an instance of  hl7:targetSiteCode in the following root /ClinicalDocument/component/structuredBody/component/section/entry/act/targetSiteCode
Following the CDA R2 standard, this is not correct. 
The element targetSiteCode can only be found in:
/ClinicalDocument/component/structuredBody/component/section/entry/**procedure**
/ClinicalDocument/component/structuredBody/component/section/entry/**observation**
And maybe more, but not in the /ClinicalDocument/component/structuredBody/component/section/entry/**act**

Can you explain why and how this  ‘DK Procedure’ template is implemented in this ‘Act’? Or do I have to edit the CDA r2 standard?
Or is my interpretation wrong?
See the screenshot below.

Thank you in advance!
![example](https://user-images.githubusercontent.com/39521104/40530447-2596626c-5ff9-11e8-8b3a-c7fe41b4ce4f.jpg)

Remco van der Werf  | Integration Consultant
VANAD Enovation
The Netherlands

**Comment by jkiddo** [comment]
Hi Remco - good to have you guys on board. You should use the [DK Procedure Procedure - 1.2.208.176.7.1.10.30](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?id=1.2.208.176.7.1.10.132&effectiveDate=dynamic) instead. See also https://scandihealth.github.io/lpr3-docs/aspects/index.html#notes-on-the-use-of-hl7-cda-elements-in-a-danish-setting

That said, it looks like a bug for the DK Procedure Act.

**Comment by jkiddo** [comment]
More specifically:

> UPDATE To ease integration Sundhedsdatastyrelsen has decided that proc.oper urn:oid:1.2.208.176.2.4.20 will contain values for Act, Procedure, and Observation while the two other valuesets proc.act urn:oid:1.2.208.176.2.4.19 and proc.und urn:oid:1.2.208.176.2.4.21 will be empty allowing organizations to use the template DK Procedure Procedure for all mandatory procedure reporting to LPR3.

**Comment by jkiddo** [comment]
We're currently awaiting whether we can flag the deprecated templates as cancelled

**Comment by jkiddo** [comment]
the template is now corrected - but keep in mind that it is still flagged as not currently used.

**Comment by jkiddo** [comment]
@Remcovanderwerf you may close this issue if you are satisfied with the updated documentation on ART Decor

**Comment by Remcovanderwerf** [comment]
Hi @jkiddo , thank you for researching this issue.
I will leave out using the targetsitecode under the /act.
Closing now.

**Comment by jkiddo** [comment]
@Remcovanderwerf just to avoid confusion. You should only be using the http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.30&language=en-US for procedures.

**Comment by Remcovanderwerf** [comment]
@jkiddo Hmm.. So how to implement the following:
http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?id=1.2.208.176.7.1.10.76&effectiveDate=dynamic

Under the **entry** there is a _choice_ statement:
hl7:act included from template 1.2.208.176.7.1.10.25 DK Procedure Act (DYNAMIC)
hl7:observation included from template 1.2.208.176.7.1.10.29 DK Procedure Observation (DYNAMIC)
hl7:procedure included from template 1.2.208.176.7.1.10.30 DK Procedure Procedure (DYNAMIC)

Do i still need to implement this _choice_ or not?

**Comment by jkiddo** [comment]
You only need to use the 1.2.208.176.7.1.10.30 template so there won't much of a choice
