### ISSUE TITLE
How the service handle "Service Unavailable"

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#121]
I can see the service is not up right now since I get the following answer back when I try send a document to:
https://lprws-test.sds.dsdn.dk/cda-ws/DocumentRepository_Service/PatientHealthcareValidateReportingService
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<title>Service Unavailable</title>
<style type="text/css">
body, p, h1 {
  font-family: Verdana, Arial, Helvetica, sans-serif;
}
h2 {
  font-family: Arial, Helvetica, sans-serif;
  color: #b10b29;
}
</style>
</head>
<body>
<h2>Service Unavailable</h2>
<p>The service is temporarily unavailable. Please try again later.</p>
</body>
</html>
```
I can see the format of this message are in HTML which is not documented in the documentation and are also not a valid SOAP answer. Since our integration platform expect an valid SOAP response this is not an valid answer to any SOAP request.

Also, I would like to get some information about how the LPR3 service are going to behave in different operation scenarios so we know what kind of response we can expect from the service when something are going wrong in the LPR3 endpoint.

**Comment by jkiddo** [comment]
The endpoint is responding now with valid SOAP responses. You can expect that if you don't receive a valid SOAP response, something is wrong on the server side. You should only expect SOAP responses

**Comment by jkiddo** [comment]
As the backing protocol is SOAP 1.2, https://www.w3.org/TR/2007/REC-soap12-part2-20070427/#tabreqstatereqtrans this should get you started on what you can expect.
