### ISSUE TITLE
Nullify Conditions

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#122]
Since the Conditions Observation section has 2 types of entries (1 for Main Conditions and 1 for Minor Conditions), we are not exactly sure how documenting a diagnosis moving from 1 entry to the other should be communicted. For example:

1. A diagnosis is sent as a Main Condition with UUID1 in a document.
2. That diagnosis was changed from an Action Diagnosis to a Secondary Diagnosis on the patient.
3. The diagnosis is sent as a Minor Condition (still with UUID1) in a new document as an Append to the 1st document.

We are trying to determine if the submission of UUID1 in document 2 will error at LPR since that UUID was already sent in a different entry type. Does the Major Condition need to be nullified before the same UUID is sent as a Minor Condition or are these both stored as a "condition object" at LPR, so the fact that they are sent in different entries just dictates some attribute on the condition?

**Comment by jkiddo** [comment]
If you don't nullify the diagnosis and basically state the 'same' diagnosis just as a minor condition with the same ID you will get an integrity exception as the stated ID is already in use.

**Comment by DaveSS** [comment]
Since there is only a nullify entry defined for "condition" and not separate nullify entries for "major condition" and "minor condition", we weren't sure if they were both just stored as the same object at LPR so a nullify from switching from one type to another wouldn't necessarily be needed.

Our main concern if is a diagnosis is switched from action to secondary as stated in my example, we would expect to send the information in a single document, since it all occurred at the same time. Therefore we would send a "nullify condition" entry and the "minor condition" entry in the same document and that could cause an integrity error if the "minor condition" entry is processed before the nullify. Would there be some guarantee that nullifies are processed first at LPR, or is this something that we will need to try to resolve differently in our document construction (i.e. we would need to send a nullify for a diagnosis and all other entries pointing to that diagnosis, and then in a subsequent document, send the same diagnosis as a minor condition and resend all entries pointing to that diagnosis?)

**Comment by jkiddo** [comment]
We'll have a look ASAP

**Comment by jonigkeit** [comment]
**RESOLUTION**
We have updated the specification in #162 and will deploy this with the next release.

**Comment by TueCN** [comment]
Closing issue because resolution feedback was not provided. 
Please re-open issue if you still experience the problem.
