### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by cgisbp** [scandihealth/lpr3-docs#123]
Hi,

When I send a test request. 
I got this response: 
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"></SOAP-ENV:Header><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>java.lang.ClassCastException: org.eclipse.emf.ecore.xml.type.impl.XMLTypeDocumentRootImpl cannot be cast to org.openhealthtools.mdht.uml.cda.DocumentRoot</faultstring></soap:Fault></soap:Body></soap:Envelope>

What does that mean?

**Comment by jkiddo** [comment]
This a bug. Please attach the request

**Comment by jkiddo** [comment]
Actually, could you please retry your action. We may believe this was due to a deployment issue

**Comment by simon-dxc** [comment]
Labelled "invalid" since we believe this was due to a deployment issue. If you experience this bug again, please let us know

**Comment by jonigkeit** [comment]
@cgisbp Please close this issue if you have no further comments.

**Comment by CgiMofr** [comment]
I think you can close this issue.
My colleague from cgi is at the moment unable to do it, as his login does not work.
