### ISSUE TITLE
com.dxc.lpr.cda.issues.CDAIssue cannot be cast to com.dxc.lpr.cda.issues.IntegrityIssue

### ISSUE THREAD

**Issue by metodikamikaelnilsson** [scandihealth/lpr3-docs#124]
I get this error response when trying to validate a clinical document at endpoint https://lprws-test.sds.dsdn.dk/cda-ws/DocumentRepository_Service/PatientHealthcareValidateReportingService:

`<faultcode>soap:Server</faultcode><faultstring>java.lang.ClassCastException: com.dxc.lpr.cda.issues.CDAIssue cannot be cast to com.dxc.lpr.cda.issues.IntegrityIssue</faultstring>`

What could be the cause of this?

**Comment by jkiddo** [comment]
This a bug. Please attach the request

**Comment by metodikamikaelnilsson** [comment]
Testing today and I guess it functions as intended now.

When validating the clinical document at [https://scandihealth.github.io/lpr3-docs/examples/EpisodeOfCare.xml](https://scandihealth.github.io/lpr3-docs/examples/EpisodeOfCare.xml) I get this response:

`<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Header><ns10:Header xmlns:ns10="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd" xmlns:ns11="http://www.nsi.dk/hsuid/2016/08/hsuid-1.1.xsd" xmlns:ns12="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns13="urn:lpr" xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns4="urn:ihe:iti:xds-b:2007" xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns6="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:ns7="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns8="http://www.w3.org/2000/09/xmldsig#" xmlns:ns9="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><ns10:SecurityLevel>3</ns10:SecurityLevel><ns10:Linking><ns10:MessageID>75ecefef-343d-4418-9693-9ef950e20ff9</ns10:MessageID></ns10:Linking><ns10:FlowStatus>flow_finalized_succesfully</ns10:FlowStatus><ns10:RequireNonRepudiationReceipt>no</ns10:RequireNonRepudiationReceipt></ns10:Header></soap:Header><soap:Body><ns2:RegistryResponse xmlns:ns10="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd" xmlns:ns11="http://www.nsi.dk/hsuid/2016/08/hsuid-1.1.xsd" xmlns:ns12="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns13="urn:lpr" xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns4="urn:ihe:iti:xds-b:2007" xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns6="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:ns7="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns8="http://www.w3.org/2000/09/xmldsig#" xmlns:ns9="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure"></ns2:RegistryResponse></soap:Body></soap:Envelope>`

**Comment by jkiddo** [comment]
Great - feel free to close the issue
