### ISSUE TITLE
templateId in DK External Observation Organizer Entry Act

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#125]
The DK External Observation Organizer Entry Act template on ArtDecor requires:
   templateId/@root="2.16.840.1.113883.10.12.301"
which is the oid for the CDA Act.

I think this should require:
   templateId/@root="2.16.840.1.113883.10.12.325"
which is the oid for the CDA External Act like the External Episode of Care Act and External Encounter Act templates.

**Comment by jkiddo** [comment]
I'll have look ASAP

**Comment by jkiddo** [comment]
See http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.119&effectiveDate=2018-06-11T07:32:31
