### ISSUE TITLE
org.hibernate.exception.DataException: could not extract ResultSet

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#126]
**This issue is blocking**

I get the following response from PatientHealthcareValidateReportingService:

```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <env:Header xmlns:env="http://www.w3.org/2003/05/soap-envelope"/>
   <soap:Body>
      <soap:Fault>
         <soap:Code>
            <soap:Value>soap:Receiver</soap:Value>
         </soap:Code>
         <soap:Reason>
            <soap:Text xml:lang="en">Call failed on the server. Error has been logged to the server log and database: org.hibernate.exception.DataException: could not extract ResultSet</soap:Text>
         </soap:Reason>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>
```

Here is the document I try to send:
[cda.txt](https://github.com/scandihealth/lpr3-docs/files/2083591/cda.txt)

**Comment by JacobBangSSE** [comment]
And now I got the following response from the server. What are you guys doing? :)
```html
<html>
   <head>
      <title>Error</title>
   </head>
   <body>404 - Not Found</body>
</html>
```

**Comment by jkiddo** [comment]
We'll have a look ...

**Comment by jkiddo** [comment]
@JacobBangSSE we are done have fun now ;)

Please try again - we don't experience any errors on our side.

**Comment by JacobBangSSE** [comment]
Well, I still gets the same error.

**Comment by jkiddo** [comment]
Hmmm ... The error code reported back to you is not exactly great. We will fix that. In the mean time I suggest that you fix your code "HealthIssueCodes.Codes.HealthIssueCodes.ALAL02" to something else - eg.  "ALAL02"

**Comment by JacobBangSSE** [comment]
Yes, it looks like we have an error here. Thanks for you help. I close this issue but I hope you are going to fix the error message to something more clear. :)
