### ISSUE TITLE
The title and effectiveTime elements in the root element.

### ISSUE THREAD

**Issue by metodikamikaelnilsson** [scandihealth/lpr3-docs#128]
Looking at [this](https://scandihealth.github.io/lpr3-docs/examples/EpisodeOfCare.xml) example, the root contains two elements that are not documented in the [docs](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates), namely: title and effectiveTime.

If I try to validate this example at [http://cda.medcom.dk/](http://cda.medcom.dk) without these elements I get this error message: 

> cvc-complex-type.2.4.a: Invalid content was found starting with element 'confidentialityCode'. One of '{"urn:hl7-org:v3":title, "urn:hl7-org:v3":effectiveTime}' is expected.

Why are these elements missing from the docs? Are they unimportant although the document wont get past validation without them?

**Comment by jkiddo** [comment]
The CDA validation site at MedCom is mainly for MedCom profiled CDA documents ... It may be of assistance when doing LPR3 validation but it is not a part of the LPR3 validation mechanism. As such, it may provide you with hints that can be useful - but only that. It may also require fields that are not required as part of LPR3. The LPR3 profile ie. does not dictate the use of title as MedCom does -  however you are free to send e.g. the title in LPR3 documents. The LPR3 schematron files should provide you with minimum conformance requirements.

LPR3 also provides you with test services for validation: See more @ https://scandihealth.github.io/lpr3-docs/aspects/index.html#service-endpoint-setup
