### ISSUE TITLE
Author templateId typo?

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#13]
The author templateId is specified as 1.2.208.176.7.10.102 in art-decor and the schematron, but it probably should be 1.2.208.176.7.1.10.102 to have the same root oid as all other templateIds specified for the LPR3. )the one specified in art-decor is missing a '.1'.

**Comment by jkiddo** [comment]
Affirmative, it's a bug. Will be fixed ASAP

**Comment by jonigkeit** [comment]
Fixed in preproduction [DK Author](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.102&effectiveDate=2017-12-11T00:00:00).
Awaiting deployment to production.
