### ISSUE TITLE
UUID format

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#130]
We are currently seeing a schematron validation error when sending UUIDs without the "-". We are seeing this as we validate CDA documents internally using the schematrons from nightly builds of GitHub. This only occurs in some elements within the document. 

So for example, we are able to send a procedure/id with a type 5 UUID that is upper-case with no dashes. But when we nullify the procedure and send that same UUID as the id in the nullify entry, we get a schematron error based on the following assertion.
```(DKExternalProcedureProcedure): Attribute @extension SHALL be of data type 'uuid' (not(@extension) or matches(@extension,'^[A-Fa-f\d]{8}-[A-Fa-f\d]{4}-[A-Fa-f\d]{4}-[A-Fa-f\d]{4}-[A-Fa-f\d]{12}$') / error) [assert]```
It seems that different elements have different requirements for the UUID format. We have also noticed in the past that certain elements were not allowed to have lower-case letters in the UUID.

Please make the UUID formatting requirements standard across all elements, and document the expectations (if any). Are UUIDs that are either all upper or all lower case acceptable? Are dashes required, optional, or not allowed? I apologize if this is already documented, but I can't find the reference. In general, CDA R2.0 states the following:

2.14.2 
DCE Universal Unique Identifier (UUID) Scheme
**Definition:**      A DCE Universal Unique Identifier is a globally unique string consisting of 5 groups of upper- or lower-case hexadecimal digits having 8, 4, 4, 4, and 12 places respectively. UUIDs are assigned using Ethernet MAC addresses, the point in time of creation and some random components. This mix is believed to generate sufficiently unique identifiers without any organizational policy for identifier assignment (in fact this piggy-backs on the organization of MAC address assignment.) 
 
But I am not sure if there are other constraints on this...

**Comment by jkiddo** [comment]
UUID dictates dashes in its canonical textual representation. The processable/coreschemas/datatypes-base.xsd schema from the standard (CDA R2.0) looks like the following for uuid's:

```
<xs:simpleType name="uuid">
<xs:annotation>
<xs:documentation>
A DCE Universal Unique Identifier is a globally unique string consisting of 5 groups of upper- or lower-case hexadecimal digits having 8, 4, 4, 4, and 12 places respectively. UUIDs are assigned using Ethernet MAC addresses, the point in time of creation and some random components. This mix is believed to generate sufficiently unique identifiers without any organizational policy for identifier assignment (in fact this piggy-backs on the organization of MAC address assignment.)
</xs:documentation>
</xs:annotation>
<xs:restriction base="xs:string">
<xs:pattern value="[0-9a-zA-Z]{8}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{12}"/>
</xs:restriction>
</xs:simpleType>
```

-which as far as I can tell is equal to what is stated in the assertion. If you are saying that you are able to create instances of DK Procedure Procedure (1.2.208.176.7.1.10.30) with ID's not matching the uuid pattern then it sounds like a bug to me

**Comment by DaveSS** [comment]
It looks like this was encountered using a version of the schematron from 4/19. Using the latest schematron, it looks like both of the uuid instances fail the assertion when they do not include the '-',, so this issue must have been resolved between 4/19 and now. Sorry for not noticing the date on the schematron that was being used when the issue was discovered.
