### ISSUE TITLE
Where to find descriptions of values

### ISSUE THREAD

**Issue by metodikamikaelnilsson** [scandihealth/lpr3-docs#131]
I've been going through the documentation at [http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-)

These docs often lacks descriptions of exactly what a certain value references. Take for example [author/time@value](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?id=1.2.208.184.2.10.6&effectiveDate=dynamic) I guess this value references the time of creation of the document, but I'm not 100% certain, and I don't want to rely on guessing.

Where can I find a thorough description of every value in the lpr3 clinical document?

**Comment by jkiddo** [comment]
The CDA profile follows the CDA R2 specification and the DK LPR3  templates describes what is required. For instance if you unfold the DK Encounter you will see the following:

<img width="960" alt="screenshot 2018-06-13 14 57 15" src="https://user-images.githubusercontent.com/211696/41353143-a1f81022-6f1b-11e8-9c47-108ca2380e00.png">

-where you can see the Kontakt.type and its requirements

Regarding the author/time value - that links to the DK CDA MedCom templates - the link can be found as the second last bullet on https://scandihealth.github.io/lpr3-docs/links/index.html

**Comment by metodikamikaelnilsson** [comment]
The docs at https://scandihealth.github.io/lpr3-docs/links/index.html doesn't clearly define where the value of author/time is derived from. I guess it's not the creation of the document but instead the starting time of participation by an author, is that correct?

So a clinical document can have several different authors during its lifespan? And "the starting time of participation by an author" means the first time the latest author created or updated the clinical document?

**Comment by jkiddo** [comment]
From the MedCom spec: Time stamp
Events occurring at a single point in time that are represented in the 
Clinical Document Header will in general be precise to the time. These 
point-in-time events are the time of creation of the document; the starting time of participation by an author, data enterer or the starting 
and ending time of an encounter.

**Comment by jkiddo** [comment]
Only a single author is supported within the LPR3 model. If you need support for multiple authors it should be addressed to the steering committee

**Comment by jonigkeit** [comment]
@metodikamikaelnilsson please close this issue if you have no further comments.
