### ISSUE TITLE
dateTime format

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#138]
For the Observation Organizer section, the value of the observation is always sent as a string, but SDS defines different data types for different types of results. For example, an "injury time" is a dateTime while the "Cause of injury" is an SKS code.

Since these are all sent as strings in the CDA, I assume you will be validating the format of the data in the Business Rules. While I know how an SKS code should be represented, I am not sure how the dateTime should be formatted? Is the format for the dateTime string specified someplace?

**Comment by DaveSS** [comment]
Do you have an update on this. We just want to verify how the dateTime data type in this context is defined. Is it an HL7 data type? JSON?

**Comment by TueCN** [comment]
The String must be formatted by YYYYMMDDhhmmss±ZZzz. 

This is specified by the [DK Medcom Timestamp HL7 datatype template](http://art-decor.org/art-decor/decor-templates--medcom-?section=templates&id=1.2.208.184.2.10.6&effectiveDate=2016-10-24T00:00:00&language=en-US)

*Note:* If LPR expects the value of an observation to be a dateTime and it for some reason fails to parse the value, the value is treated as missing (null) for business rule purposes.

**Comment by jkiddo** [comment]
@DaveSS 

See #164
