### ISSUE TITLE
manufacturedProduct templateId typo?

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#14]
The Contrast Agent ManufacturedProduct templateId is specified as 2.16.840.113883.10.12.312 in art-decor but correct HL7 oid should have an additional '.1'  as follows: 2.16.840.1.113883.10.12.312

**Comment by jkiddo** [comment]
Affirmative. It's a bug. Will be fixed ASAP

**Comment by jonigkeit** [comment]
Fixed in preproduction [DK Contrast Agent ManufacturedProduct](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.4&effectiveDate=2017-12-11T00:00:00).
Awaiting deployment to production.
