### ISSUE TITLE
View LPR3 data?

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#140]
We have been performing some successful submissions of documents to the LPR3 portal. Is there a way to log into the LPR3 system to evaluate what information is currently stored for our test patients as we continue to submit test documents?

**Comment by jkiddo** [comment]
The link to the UI is https://lpradm-test.sds.dsdn.dk/

**Comment by jkiddo** [comment]
I would suspect that an easy way for you would be to go to [CIMT](https://www.regionh.dk/imt). They should be familiar with the interface. But that is only an assumption.
