### ISSUE TITLE
The Azure version of Art-Decor is not working

### ISSUE THREAD

**Issue by MartinHylleberg** [scandihealth/lpr3-docs#145]
**This issue is blocking**

We are currently experiencing problems with art-decor on azure. (http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-)

We are getting this response whenever we try to view a template.

> lpr-art-decor.westeurope.cloudapp.azure.com sent an invalid response.

This is problematic as this is the current version of the documentation and the http://art-decor.org/art-decor/decor-project--lpr- is very much out of date.

**Comment by jonigkeit** [comment]
Site is up again.

**Comment by MartinHylleberg** [comment]
Thank you :)
