### ISSUE TITLE
Problem Replacing Observation Organizer Entry Act

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#146]
This is a similar issue to Issue #141.

In Art Decor, the reference to replace an Observation Organizer Act is specified to directly contain DK External Observation Organizer Entry Act (1.2.208.176.7.1.10.119) instead of coming from DK External Observation Organizer Entry Act Replacement Reference (1.2.208.176.7.1.10.126). So the result based on Art Décor doesn't make use of Replacement Reference template at all. It looks like:
```XML
<reference typeCode="RPLC">
  <externalAct classCode="REG" moodCode="EVN">
    <templateId root="1.2.208.176.7.1.10.119"/>
    <templateId root="2.16.840.1.113883.10.12.301"/>
    <id root="8d38c060-3d3d-4174-bbd3-473c1a0ee282" extension="ffa7bcb2-0ca4-57d9-a7f9-f37fbb1c5482"/>
  </externalAct>
</reference>
```
instead of:
```XML
<reference typeCode="RPLC">
  <templateId root="1.2.208.176.7.1.10.126"/>
  <templateId root="1.2.208.176.7.1.10.117"/>
  <templateId root="2.16.840.1.113883.10.12.324"/>
  <externalAct classCode="REG" moodCode="EVN">
    <templateId root="1.2.208.176.7.1.10.119"/>
    <templateId root="2.16.840.1.113883.10.12.301"/>
    <id root="8d38c060-3d3d-4174-bbd3-473c1a0ee282" extension="ffa7bcb2-0ca4-57d9-a7f9-f37fbb1c5482"/>
  </externalAct>
</reference>
```

**Comment by simon-dxc** [comment]
@DaveSS - If everything is fine could you please close the issue.
We will close it Tuesday next week if we haven't heard from you.
