### ISSUE TITLE
versioning issue

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#15]
Is it necessary to have the following Schematron check?

Engine name: ISO Schematron (XSLT 2.0)
Severity: error
Description: (DKEpisodeOfCareSummariesDocument): /versionNumber must be precisely 1 higher than /relatedDocument/parentDocument/versionNumber (boolean(/relatedDocument) and /versionNumber != /relatedDocument/parentDocument/versionNumber + 1 / error) [assert]
Start location: 2:77

While I think it makes sense to require that a new file will have a versionNumber greater than it's parentDocument, I don't think having it exactly one greater should be required. We may create versions of documents in our system that each get a version number and not all of those are guaranteed to be sent to DXC. We may find errors in the files before we send them or the file may be sent but some transport issue causes an error. When we decide to send a new file, it might make sense to create a new one rather than try to resend an old document with out-of-date information. 

Can this requirement be relaxed to just require that the parentDocument/versionNumber is less than the current documents /versionNumber?

**Comment by jkiddo** [comment]
It should be possible to relax this requirement. Which organization are you representing?

**Comment by DaveSS** [comment]
I am with Epic. We are representing the Capital and Zealand Regions through Sundhedsplatformen.

--dave

**Comment by jonigkeit** [comment]
Hi Dave. We'll relax the schematron for version number, so that the version number of the new set has to be greater than the version of the existing set related to by the parent document.
```xquery
boolean(/relatedDocument) and /versionNumber <= /relatedDocument/parentDocument/versionNumber
```

Keep in mind that the /relatedDocument/parentDocument/versionNumber must have the value of the latest sucessful submitted document's versionNumber. If that is not the case your request will fail.
