### ISSUE TITLE
Wrong time value in GUI

### ISSUE THREAD

**Issue by kbhCGI** [scandihealth/lpr3-docs#152]
Hi

In the GUI "Forløbselement Starttidspunkt:"  is set to 04:00 on all our episode of care.
We are not sending 04:00 in the message.
None of the time values are correct in attached example.
  
![lpr3 dato fejl](https://user-images.githubusercontent.com/41666628/43183791-e21a8a10-8fd5-11e8-8757-0990802bfb68.PNG)

**Comment by TueCN** [comment]
Hi.

I found the XML from the most recent version of you submission. It has the following start time for the episode of care:
```xml
<effectiveTime>
    <low value="20180629000000-0200"/>
</effectiveTime>
```

This is ```00:00 29-06-2018```, but in the timezone of GMT-2.
The locale da-DK used by the LPR server, is observing "summer time" on this date and is therefore in the timezone of GMT+2. This means that when viewed through the web browser, times are displayed in the da-DK timezone, and therefore it is displayed as ```04:00 29-06-2018``` (there are 4 hours difference in timezones).

I hope this explains the observed behaviour.
