### ISSUE TITLE
Result is not always visible in GUI

### ISSUE THREAD

**Issue by kbhCGI** [scandihealth/lpr3-docs#153]
Hi

This episode of care has result, but is not displayed.
Some time it is displayed and some it is not.
![lpr3 manglende resultat](https://user-images.githubusercontent.com/41666628/43187802-05589aa6-8fe2-11e8-89bb-be67d1453cf8.PNG)

**Comment by kbhCGI** [comment]
Same problem with aaada9c5-d2e9-5079-b5a6-27a27f1e9c39 Cpr:0110900FØ2

**Comment by TueCN** [comment]
Hi

You have to expand the section the result has been submitted under ("resultatindberetning årsag")
Only the sections with validation errors auto-expand when you open an EoC in the GUI.


I can see these results on EoC with id ```aaad0dac-3fcf-5032-8a62-ed0b5a403787```
![image](https://user-images.githubusercontent.com/14910711/43266685-4ed4a016-90ec-11e8-9f32-d8083f2209b0.png)


I can see these results on EoC with id ```aaada9c5-d2e9-5079-b5a6-27a27f1e9c39```
![image](https://user-images.githubusercontent.com/14910711/43266569-03243596-90ec-11e8-8200-169a96be03e1.png)


Are there any issues with the registrations? 
> Some time it is displayed and some it is not.

What do you mean by this?
