### ISSUE TITLE
Updating an Episodeofcare adds new Forløbsmarkører

### ISSUE THREAD

**Issue by MartinHylleberg** [scandihealth/lpr3-docs#155]
When sending an update to an episodeofcare the forløbsmarkør is duplicated.
In our scenario we have an episodeofcare with one forløbsmarkør . After creation of the episodeofcare we will send an update to the episodeofcare changing the start time of the episodeofcare. This is the only change to the episodeofcare

After submitting the updated episodeofcare we now have 2 forløbsmarkører.

Below is the original data as shown in the administrative tool
![original](https://user-images.githubusercontent.com/31653587/43248509-5eed9446-90b8-11e8-928d-dab1d6ea3fb9.png)
Below is the episodeofcare after updating the start date
![duplicate](https://user-images.githubusercontent.com/31653587/43248512-61abcc84-90b8-11e8-8d50-c834604a2f98.png)

[Create Episodeofcare](https://github.com/scandihealth/lpr3-docs/files/2230939/eoc01.zip)

[Update Episodeofcare](https://github.com/scandihealth/lpr3-docs/files/2230940/eoc02.zip)

**Comment by TueCN** [comment]
This is a bug, which has now been fixed and is awaiting deployment.

**RESOLUTION**
Existing Forløbsmarkører are now removed during EoC replacement.

*Note*: The same issue was discovered for Diagnose attributes ```lokalrecidiver``` and ```metastaser``` and has been fixed there as well.
