### ISSUE TITLE
UUID version 5 (Windows/.Net)

### ISSUE THREAD

**Issue by ScaAnders** [scandihealth/lpr3-docs#156]
Do you know if there is any standard way to generate UUID v5 values in Windows, .Net or any libraries in WIN32? 
If not, can you provide some input values (namespace and text) and the corresponding output values (UUID) for the some existing UUID v5 so that we can create some valid unit-tests, if we decide to implement the UUID logic ourselves according to the specification?
I will be grateful if you can post this information.

**Comment by jkiddo** [comment]
Have a look at https://stackoverflow.com/questions/8477664/how-can-i-generate-uuid-in-c-sharp, https://scandihealth.github.io/lpr3-docs/examples/index.html#sample-of-how-to-create-a-uuidv5, https://github.com/myquay/GuidOne and https://gist.github.com/rickbeerendonk/13655dd24ec574954366 for starters

**Comment by ScaAnders** [comment]
Hi,
Thank you very much for providing some implementation details.
As you probably already have seen in the links you provided, none of the implementations are “standard” libraries. This makes me suspicious about the correctness of the implementations – they might very well be working but I would like to verify it before using one of them.

If you can spare some time to create a couple of examples (input UUID namespace + string value and the corresponding output UUID) I would be very grateful. Then I would have some verified information to create my unit tests on, thereby verifying the implementation. I ask this of you because I would imagine that you already have a working implementation and by providing some test input-values with the corresponding output-values then you have made it possible for any developer to verify their implementation regardless of language.

I worry that without verifying an implementation we might end up with an implementation that contains an increased likelihood of creating the same output value but with different input values…
Thanks in advance.

**Comment by jkiddo** [comment]
What is 'standard'? A myriad of projects on e.g. github can be considered 'standard'.

Also, have a look at the implementation at e.g. https://github.com/LogosBible/Logos.Utility/blob/master/src/Logos.Utility/GuidUtility.cs

You can calculate some examples on http://tools.adjet.org/uuid-v5 using the ISO OID from https://tools.ietf.org/html/rfc4122#appendix-C 

I.E - using 6ba7b812-9dad-11d1-80b4-00c04fd430c8 (ISO OID) with input 1.2.208.176.7.1.10.80 gives you the value of fe537378-31eb-5036-91da-72ed4eecae10 - which is the 'baseline' OID for generating `DK Episode of Care Act`. See also https://github.com/scandihealth/lpr3-docs/issues/9
