### ISSUE TITLE
DKExternalEpisodeOfCareReference incorrect id/@root

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#16]
The root is for the id (which is aversion 5  UUID) is specified as 1.2.208.176.1.2.1.

I think it is missing the '.7' since other version 5 UUIDs have the following root: 1.2.208.176.7.1.2.1

**Comment by cjonigkeit-csc** [comment]
Fixed all ´DK External * Act´ in preproduction [DK External Episode Of Care Act](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates)
Awaiting deployment to production.
