### ISSUE TITLE
Detail panel in LPR3 client not working

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#163]
When trying to open the detail panel in the LPR3 client we get the following error message on all reports:

![image](https://user-images.githubusercontent.com/36242392/44079996-fddc75da-9faa-11e8-9fdc-50644d8b2b84.png)

**Comment by TueCN** [comment]
This bug should be fixed with the latest milestone, deployed today. 
I am currently able to open the details of any episode of care.
