### ISSUE TITLE
Problem with updating/replacement

### ISSUE THREAD

**Issue by cgisbp** [scandihealth/lpr3-docs#165]
We tried to register a new reporting, it gone well first time. 
When we tried to update the document, it failed with INTEGRITY_CHECK|||Episode of Care ... already exists ...

[Lpr3docA1.txt](https://github.com/scandihealth/lpr3-docs/files/2289547/Lpr3docA1.txt)

**Comment by TueCN** [comment]
**RESOLUTION**
Fixed several bugs regarding replacements.

**Comment by TueCN** [comment]
Closing issue because resolution feedback was not provided. 
Please re-open issue if you still experience the problem.
