### ISSUE TITLE
Use of code lists in the LPR3 service

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#170]
What happens when the LPR3 web servicen validates whether or not a specific code in the input message is present at the relevant code list, e.g.:

- Which timings are used at the **procedure** reporting element to validate if procedure code is present at the relevant code list at a given point in time - start date time, end date time or both?

**Comment by jonigkeit** [comment]
A specific code is valid if there is an overlap between the interval of the procedure and the interval of the code. In case of multiple matches the match closes to the start of the procedure interval is used.
