### ISSUE TITLE
Accumulated error list is not up to date.

### ISSUE THREAD

**Issue by kbhCGI** [scandihealth/lpr3-docs#172]
Hi 

Our (RN) accumulated error list is not up to date.
Last updated Jul 31 15:50
Please start it again :-)

**Comment by TueCN** [comment]
There is an issue with the connection between the LPR server and the FTP server. 
We are investigating.

**Comment by TueCN** [comment]
https://github.com/scandihealth/lpr3-docs/issues/172#issuecomment-415380129 FYI: the accumulated error list does not validate issues. The validated timestamp does not change unless a new submission is made, or if an LPR-administrator manually starts a revalidation of submissions.

**Comment by kbhCGI** [comment]
Does the validate timestamp change, if ex. there is a rule telling, that a code need to be registrated before 10 days and it is not reported to LPR3? (actionsdiagnose not registreted)

**Comment by TueCN** [comment]
We have identified the problem and is working on rectifying it.

**Comment by kbhCGI** [comment]
It is OK now.
