### ISSUE TITLE
Question regarding reported synchronous service error due to excessive message volume

### ISSUE THREAD

**Issue by jbraschler** [scandihealth/lpr3-docs#175]
We have been relayed the following feedback that was sourced from SDS:

> The LPR3 reporting service is a synchronous service. This means that there is no queue for the LPR3 reporting. If there are more alerts than there is capacity, those who are not being treated will receive a message about 'service unavailable'. This must be handled by the sender. There is thus no priority option, but alerts are processed in the order in which they are received, provided there is 'free space' at the reporting service. 

Upon further inquiry, SDS relayed that a maximum of 150,000 CDA documents per hour could be accommodated.

Our question is, precisely what type of error can we expect to receive in a synchronous response message if the submitted document is rejected due to overall throughput exceeding the maximum volume for the service?

**Comment by RasmusThernoe** [comment]
We would like to supplement the question above:

- Will it be the same response when the service is down and when the service is occupied or will reporters be able to distinguish?

- Is there instructions regarding resending frequency in case the service is occupied?

- Is there instructions regarding resending frequency in case the service is down?

**Comment by jonigkeit** [comment]
Assuming that you can establish a HTTP connection with the endpoint you should expect HTTP status codes
 * `503 Service Unavailable`
 * `429 Too Many Requests`

We are looking into using industry standard rate limit headers for use with 429, e.g.

HTTP Header | Description
---------------|--------------
X-RateLimit-Limit          | Request limit per hour
X-RateLimit-Remaining | The number of requests left for the time window
X-RateLimit-Reset         | The remaining window before the rate limit resets in UTC epoch seconds

**Comment by jkiddo** [comment]
For `503` we are looking into proper values for the `Retry-After`HTTP Header

**Comment by RasmusThernoe** [comment]
Do you have a specification of the exact response in case of 503 and 429 from the LPR3 services?

And are reporters obliged to use the HTTP elements mentioned above, e.g. "X-RateLimit" and "Retry-After" or is it just an option?

**Comment by RasmusThernoe** [comment]
One additonal question related to this issue...

Does the same pattern of HTTP codes and parameters apply to both the service that validates and the service that both validate and persist? E.g. should the client expect to receive "429 Too Many Request" when performing online validation?

**Comment by jonigkeit** [comment]
After elaboration we have concluded that *no changes* will be made to the XDR endpoints.
As it is the case now you will receive a HTTP status code: `503 Service Unavailable`.

**Comment by jonigkeit** [comment]
Requirements regarding SOAP HTTP binding have been added to the documentation in 5dac7d8ac8ea8b1e90437a3344f503b3a4934fb3
