### ISSUE TITLE
New problem with updating/replacement (... could not execute statement)

### ISSUE THREAD

**Issue by cgisbp** [scandihealth/lpr3-docs#176]
We tried some new updating/replacement of reports and got new error-500  javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement.

[Lpr3docB1.txt](https://github.com/scandihealth/lpr3-docs/files/2331978/Lpr3docB1.txt)

**Comment by TueCN** [comment]
I have reproduced the error and it seems to be caused by the replacement operation (relatedDocument/@typeCode="RPLC") deleting encounter with ID AAA656A5-EAE0-53BA-A1C0-1F5D84C475B8, which causes a constraint violation.

We will look into this, but a fix will probably not be ready for next release.
