### ISSUE TITLE
Error in SKS code validation 

### ISSUE THREAD

**Issue by Smp-xmedicus** [scandihealth/lpr3-docs#177]
When sending in:
`   <encounter classCode="ENC" moodCode="EVN">
              <templateId root="1.2.208.176.7.1.10.74" />
              <templateId root="2.16.840.1.113883.10.12.302" />
              <id root="96c4afb5-9ca6-430c-b9bf-aeee5ec9185a" extension="4eface74-ffdc-5dbb-a061-73f2e0a10d00" />
              <code code="ALCA00" codeSystem="1.2.208.176.2.4" />
              <effectiveTime>
                <low value="20180827135000+0200" />
                <high value="20180827140000+0200" />
              </effectiveTime>
              <priorityCode code="ATA3" codeSystem="1.2.208.176.2.4" />
              <participant typeCode="RESP">`

I get :
`<ns2:RegistryError codeContext="BUSINESS_RULE|||En SKS-kode anvendt som prioritet for en kontakt skal være gyldig på kontaktens starttidspunkt" errorCode="InvalidDocumentContent" location="96c4afb5-9ca6-430c-b9bf-aeee5ec9185a^b7f835a6-978b-4d8f-9957-be9197c70f8f|||//*[child::*[local-name()='id' and @root='96c4afb5-9ca6-430c-b9bf-aeee5ec9185a' and @extension='4eface74-ffdc-5dbb-a061-73f2e0a10d00']]|||sds:lpr:3.0.4|||05.53" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning">
        </ns2:RegistryError>`

But ATA3 is valid according to the SKS register:
`admATA3                199601012018060520180630Elektiv   
                                                                                                                          
admATA3                201807012018060525000101Planlagt`

It is also saved in LPR3 as Elektiv, not as it should Planlagt.

**Comment by TueCN** [comment]
It seems that for some reason the "Elektiv" version of the code is picked and used in business rule validation, instead of the intended "Planlagt" version which is valid on the encounter start date of 2018-08-27

We will look into this.

**Comment by TueCN** [comment]
I cannot reproduce the problem using the provided XML. 
@Smp-xmedicus can you please verify everything works as expected now? 

If you are still able to reproduce the problem, please provide the full `ClinicalDocument` XML

**Comment by Smp-xmedicus** [comment]
This seems to be solved now. Thx.
