### ISSUE TITLE
Error in Abort reporting.

### ISSUE THREAD

**Issue by Smp-xmedicus** [scandihealth/lpr3-docs#178]
When reporting:
`      <component contextConductionInd="true">
        <section>
          <templateId root="1.2.208.176.7.1.10.113" />
          <templateId root="2.16.840.1.113883.10.12.201" />
          <entry typeCode="COMP">
            <observation classCode="OBS" moodCode="EVN">
              <templateId root="1.2.208.176.7.1.10.45" />
              <templateId root="1.2.208.176.7.1.10.36" />
              <templateId root="2.16.840.1.113883.10.12.303" />
              <id root="96c4afb5-9ca6-430c-b9bf-aeee5ec9185a" extension="ac6890f5-07a8-55cb-b111-0e09ac2c5991" />
              <code code="DO049" codeSystem="1.2.208.176.2.4" />
              <entryRelationship typeCode="COMP">
                <observation classCode="OBS" moodCode="EVN">
                  <templateId root="1.2.208.176.7.1.10.43" />
                  <templateId root="2.16.840.1.113883.10.12.303" />
                  <code code="ALGA01" codeSystem="1.2.208.176.2.4" />
                </observation>
              </entryRelationship>
              <entryRelationship typeCode="REFR">
                <encounter classCode="ENC" moodCode="EVN">
                  <templateId root="1.2.208.176.7.1.10.77" />
                  <templateId root="2.16.840.1.113883.10.12.301" />
                  <id root="96c4afb5-9ca6-430c-b9bf-aeee5ec9185a" extension="4eface74-ffdc-5dbb-a061-73f2e0a10d00" />
                  <code nullFlavor="NA" />
                </encounter>
              </entryRelationship>
            </observation>
          </entry>
        </section>
      </component>
`
and:
`              <entryRelationship typeCode="REFR">
                <organizer classCode="BATTERY" moodCode="EVN">
                  <templateId root="1.2.208.176.7.1.10.88" />
                  <templateId root="2.16.840.1.113883.10.12.305" />
                  <code code="RAA04" codeSystem="1.2.208.176.2.4" />
                  <statusCode code="RAS01" />
                  <participant typeCode="RESP">
                    <templateId root="1.2.208.176.7.1.10.49" />
                    <templateId root="2.16.840.1.113883.10.12.321" />
                    <participantRole classCode="ROL">
                      <scopingEntity classCode="ORG">
                        <id root="1.2.208.176.1.1" extension="353281000016001" assigningAuthorityName="SOR" />
                      </scopingEntity>
                    </participantRole>
                  </participant>`

I get a warning: 
`<ns2:RegistryError codeContext="BUSINESS_RULE|||Hvis der er en diagnose i kodelisten diag.abort, skal der være en komplet resultatindberetning RAA04 (abortoplysninger) senest 7 dage efter kontaktens afslutning" errorCode="InvalidDocumentContent" location="96c4afb5-9ca6-430c-b9bf-aeee5ec9185a^b7f835a6-978b-4d8f-9957-be9197c70f8f|||//*[child::*[local-name()='id' and @root='96c4afb5-9ca6-430c-b9bf-aeee5ec9185a' and @extension='4eface74-ffdc-5dbb-a061-73f2e0a10d00']]|||sds:lpr:3.0.4|||RAA04.1-w" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning">
        </ns2:RegistryError>`

and an error:
`<ns2:RegistryError codeContext="BUSINESS_RULE|||Resultatindberetning RAA04 (abortoplysninger) må kun trigges af en diagnose i kodelisten diag.abort" errorCode="InvalidDocumentContent" location="96c4afb5-9ca6-430c-b9bf-aeee5ec9185a^b7f835a6-978b-4d8f-9957-be9197c70f8f|||//*[child::*[local-name()='id' and @root='96c4afb5-9ca6-430c-b9bf-aeee5ec9185a' and @extension='281152dc-9ffa-5160-9e03-12fefa5f8545']]|||sds:lpr:3.0.4|||RAA04.4" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning">
        </ns2:RegistryError>`

In LPR DO049 is shown as aktions diagnose and RAA04 is shown as completed Result. But I still get warning and error.

**Comment by TueCN** [comment]
The XML you attached does not show the full "Resultatindberetning" [DK Observation Organizer Entry Reference Act](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.90&effectiveDate=2018-01-04T00:00:00). 

I cannot see if your Resultatindberetning has a "Diagnose" (Condition Observation) reference to the Diagnose (observation) with code DO049.

The RAA04.4 error says that the RAA04 resultatindberetning must be "triggered" by a main condition observation which has a code on the list "diag.abort". 

If there is no reference to a main condition observation in the resultatindberetning act, the RAA04.4 is also reported, which I assume is the problem here.

**Comment by Smp-xmedicus** [comment]
You are right, it was a wrong reference.
