### ISSUE TITLE
Error in SKS validation in resultat

### ISSUE THREAD

**Issue by kbhCGI** [scandihealth/lpr3-docs#179]
We get errors in result, but the SKS code is valid. 
![lpr3 fejl i resultat](https://user-images.githubusercontent.com/41666628/44898638-0cff0180-acef-11e8-9a7e-8b61b6491494.png)

Why are you using kodeliste res.cncstad and res.ctcstad , should you not use res.ncstad & res.tcstad??
Or is it same error as #177, where it look like you are using an wrong date when you look the code up.

**Comment by TueCN** [comment]
> should you not use res.ncstad & res.tcstad?

You are correct. The business rules have not been updated with the changes from indberetningsvejledningen version 1.2 yet. 

It is something that will be updated very soon (scheduled for next "service pack" release 3.7. 
It might not make it in the first 3.7 version, but will come in one of the following hotfix releases)

**Comment by RasmusThernoe** [comment]
Will you provide a change log when updating the business rules to version 1.2 of indberetningsvejledningen?

**Comment by TueCN** [comment]
**RESOLUTION**
Dynamic rules have been updated. 

@RasmusThernoe 
See https://gist.github.com/TueCN/07af1b3f91142c20a54f23a7919c1f2c for details
