### ISSUE TITLE
Error not shown in GUI and no acc. error list.

### ISSUE THREAD

**Issue by kbhCGI** [scandihealth/lpr3-docs#180]
Hi
We have this episode of care:
![fejl i gui 1 1](https://user-images.githubusercontent.com/41666628/45030942-04832f80-b03d-11e8-8a3f-277ba42bc1b9.png)
It has status OK in the list.

But when we open the episode of care there is an error.
![fejl i gui 1 2](https://user-images.githubusercontent.com/41666628/45030989-27addf00-b03d-11e8-8d91-4dd9ab51d084.png)
![fejl i gui 1 3](https://user-images.githubusercontent.com/41666628/45030992-2a103900-b03d-11e8-8774-1326cde8c71b.png)

There is no accumulated error list.

Error was in responce from WS.

**Comment by TueCN** [comment]
Yes this is a bug. The episode of care should have Fejltype "Fejl" in the list of search results

**Comment by TueCN** [comment]
With the enablement of SEB/SOR integration I no longer have access to view your episode of care.

@kbhCGI could you please verify this is still an issue in the new version 3.7 of LPR and if so, attach the input XML that reproduces this bug?

**Comment by kbhCGI** [comment]
I get this an error then i try to send it again #190

**Comment by TueCN** [comment]
@kbhCGI #190 has been closed now. Can you try and reproduce the problem now?

**Comment by kbhCGI** [comment]
@TueCN i get the error from #195

**Comment by TueCN** [comment]
Ok, we must await [milestone/26](https://github.com/scandihealth/lpr3-docs/milestone/26) being deployed and then you can try again.

**Comment by kbhCGI** [comment]
cannot reproduce the problem.
