### ISSUE TITLE
Betalingsoplysninger is not shown in GUI

### ISSUE THREAD

**Issue by kbhCGI** [scandihealth/lpr3-docs#181]
Hi

Why is betalingsoplysninger not shown in GUI?
![betalingsoplysninger mangler](https://user-images.githubusercontent.com/41666628/45139891-ca32a300-b1a0-11e8-92e8-ef7be985335a.png)

It had same error as #180, OK in list and error in betalingsoplysninger.

**Comment by TueCN** [comment]
**RESOLUTION**
Paymentinformation (betalingsoplysninger) owned by encounters were not correctly saved to the database. The link from the betalingsoplysning to its owner (encounter) was not set.

This is fixed now.
