### ISSUE TITLE
Response from LPR3 service in case of exception

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#185]
In some GitHub issues (e.g. 139, 143 and 147) the client get a failure response without a registry response and an error category (XSD, Schematron, Integrity or Business Rule).

The issues above are examples of input that result in a server side exception.

Do you have a specification on how the server tell the client that the unexpected input triggered an error which is outside any of the defined error categories, e.g. a Java exception?

**Comment by TueCN** [comment]
The response always adhere to the SOAP version 1.2 specification.

If (and only if) an unexpected error occurs (e.g. Java RuntimeException), the service will return a SOAP [Fault](https://www.w3.org/TR/soap12-part1/#soapfault) element (child of body).

Feel free to create an issue here on GitHub when you receive a SOAP fault
