### ISSUE TITLE
Reporting of virtual encounter

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#186]
I have reported a "Måling af puls" in a virtual encounter.

I have reported a "Telefonkonsultation" in an outpatient encounter.

None of these gives an error.

I would expect an error since the reporting guide (Indberetningsvejledningen) states:

> ”Omfatter obligatorisk kun ydelserne telefonkonsultation og videokonsultation, der skal indberettes som procedure under kontakten 'Virtuel kontakt'.

Is this a business rule which is pending in the LPR3 service?

**Comment by maagaard-DXC** [comment]
In general all reports must conform to the reporting guide (Indberetningsvejledningen) regardsless of what rules are implemented in the LPR3 service.

A list of implemented rules can be found here: 
https://scandihealth.github.io/lpr3-docs/testenvironment/index.html#rules-implemented-on-test-system.
