### ISSUE TITLE
Error: Missing Classification/Slot element with an authorInstitution attribute

### ISSUE THREAD

**Issue by CgiMofr** [scandihealth/lpr3-docs#188]
hi,

Since friday the 21 of september, sometime after lunch,  we are getting the following error when submitting:

INTEGRITY_CHECK|||The submission set must have an ihe-xdr Classification/Slot element with an authorInstitution attribute|||AUTHOR_INSTITUTION_NOT_FOUND

However, the following snippet is from our submissions:
![image](https://user-images.githubusercontent.com/39047490/45950074-8ba14300-bffe-11e8-95b9-d1ae4973ff8b.png)

What could be the error ?

**Comment by TueCN** [comment]
Hi

We started enforcing the existing constraints defined in [XDS Metadata for Document Sharing Danish Profile](http://svn.medcom.dk/svn/drafts/Standarder/IHE/DK_profil_metadata/Metadata-v095.docx)

See https://github.com/scandihealth/lpr3-docs/issues/102#issuecomment-424258194


See example taken directly from [XDS Metadata for Document Sharing Danish Profile](http://svn.medcom.dk/svn/drafts/Standarder/IHE/DK_profil_metadata/Metadata-v095.docx):
```xml
<rim:Slot name="authorInstitution">
    <rim:ValueList>
        <rim:Value>Odense Universitetshospital – Svendborg Sygehus^^^^^&
             1.2.208.176.1.1&ISO^^^^88878685</rim:Value>
    </rim:ValueList>
</rim:Slot>

```

**Comment by MichaelEsmannSSE** [comment]
The value "88878685" does not look like a valid SOR code to me(?)

**Comment by jkiddo** [comment]
> Example has been updated: [5bb9908](https://github.com/scandihealth/lpr3-docs/commit/5bb990802e63d200f839eb0271fb37c939cdb430) and authorities have been notified about the misguiding example in the underlying specification

It should have been 241301000016007 in the example

**Comment by MichaelEsmannSSE** [comment]
Will you release schematron files that are able to do this validation of our requests?

**Comment by CgiMofr** [comment]
Hi,
We have changed our submissions and now send correct XON data. But still get errors. We have tried with what we think is correct:
![image](https://user-images.githubusercontent.com/39047490/46065071-6c76f280-c171-11e8-969b-7f1525dfd980.png)


(NOTE: the xml we send is in one line, and the newline between 'Region' and 'Nordjylland' is not sent)

and which gives the error:

_INTEGRITY_CHECK|||The submission set must have an ihe-xdr Classification/Slot element with an authorInstitution attribute|||AUTHOR_INSTITUTION_NOT_FOUND"_

The last thing we tried was:
![image](https://user-images.githubusercontent.com/39047490/46065098-80225900-c171-11e8-8931-5887d7efadc1.png)


with just '&' instead of &, as the example in the document. This is however bad xml,
and we get the error:

_Problems creating SAAJ object model._

We cant see what causes the problem ?

**Comment by TueCN** [comment]
@MichaelEsmannSSE 
Right, the example should have been:
```xml
<rim:Slot name="authorInstitution">
    <rim:ValueList>
    <ns2:Value>Region Nordjylland^^^^^&amp;1.2.208.176.1.1&amp;ISO^^^^6071000016008</ns2:Value>
</rim:Slot>
```

No the XDS metadata attribute `authorInstitution` is not part of schematron validation. The metadata is validated directly by our web service.

The schematron validation only acts on the CDA `ClinicalDocument` level and below.

**Comment by MichaelEsmannSSE** [comment]
@CgiMofr 
We have had success with the request below. Based on the example we have added the attribute _classificationScheme="urn:uuid:a7058bb9-b4e4-4307-ba5b-e3f0ab85e12d"_

```
<ns2:Classification classificationScheme="urn:uuid:a7058bb9-b4e4-4307-ba5b-e3f0ab85e12d">
          <ns2:Slot name="authorInstitution">
            <ns2:ValueList>
              <ns2:Value>Region Midtjylland^^^^^&amp;1.2.208.176.1.1&amp;ISO^^^^6081000016005</ns2:Value>
            </ns2:ValueList>
          </ns2:Slot>
        </ns2:Classification>
```

**Comment by CgiMofr** [comment]
Thank you @MichaelEsmannSSE  - it solved our problem :-)
I close this issue.
