### ISSUE TITLE
Performance of online validation

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#189]
Do you have specifications on the response time of the online validation service (dry run validation) -especially the dependency between size of request and response time?

**Comment by jonigkeit** [comment]
SLAs are undergoing revision by SDS, because current SLA for response time of all web service calls is set a 5 minutes and 10 seconds.

**Comment by KirstenLHSDS** [comment]
The previous answer is not representing the requirements. As mentioned, the current SLA is being revised. Regarding the question about dependency between size of request and response time, there is by now too few examples to measure this in a reliable way.

**Comment by jonigkeit** [comment]
@RasmusThernoe please close this issue if you have no further comments.

**Comment by RasmusThernoe** [comment]
We have raised this to SDS - still waiting for an answer.

**Comment by jonigkeit** [comment]
Sry @RasmusThernoe of course you are entitled to having your question answered.
I will assign the issue to myself and reply as soon as the SLA have been revised.

**Comment by KirstenLHSDS** [comment]
Performance is adressed, and of course the 5 min response is not valid. SDS and DXC are taking combined initiatives to ensure sufficient performance. As performance tuning is yet ongoing, it is not reasonable to commit to a definite number of seconds per CDA-document. Of course the target is to be able to handle daily load during the night. .

**Comment by jonigkeit** [comment]
@RasmusThernoe I hope this satisfies your question

**Comment by RasmusThernoe** [comment]
The question specifically concerned **online validation** because of the direct impact on end-users.

We still lack guidance on how to design online validation that provide acceptable end-user experience.

**Comment by jonigkeit** [comment]
See #277
