### ISSUE TITLE
schematrons

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#19]
Is it possible to get new schematrons generated from the art-decor that reflect the proposed changes already implemented? The ones we can get from github are pretty old and display a number of errors for known issues so it is difficult to find the errors we need to fix.

**Comment by jkiddo** [comment]
We'll do our best to release them ASAP

**Comment by jonigkeit** [comment]
Here are the latest schematrons: 
[lpr-schematron-1.1.zip](https://github.com/scandihealth/lpr3-docs/files/1590021/lpr-schematron-1.1.zip)
