### ISSUE TITLE
Contact info is not deleted when updated. 

### ISSUE THREAD

**Issue by kbhCGI** [scandihealth/lpr3-docs#197]
Hi

I have sende this message multible times today. (3 times)
Now contact infomation is repeated 3 times.
We are using delete/update when we are sending.

![image](https://user-images.githubusercontent.com/41666628/46405150-95fec380-c707-11e8-9c86-fd084565af3a.png)

**Comment by TueCN** [comment]
@kbhCGI can you please provide all relevant information for when this issue happened and how this issue can be reproduced? 

1.  The XML that constitutes the submission (`ClinicalDocument` is enough)
2. Which endpoint was used (see https://scandihealth.github.io/lpr3-docs/testenvironment/index.html#address
3. The date and time that the above submission was submitted to the above endpoint, which resulted in the error.

See https://github.com/scandihealth/lpr3-docs/blob/master/CONTRIBUTING.md#bugs

**Comment by kbhCGI** [comment]
@TueCN I was testing issue #192
I did send 3 almost identical Clinicaldocuments 
[18100308350622.txt](https://github.com/scandihealth/lpr3-docs/files/2459598/18100308350622.txt)
[18100308460624.txt](https://github.com/scandihealth/lpr3-docs/files/2459599/18100308460624.txt)
[18100312220629.txt](https://github.com/scandihealth/lpr3-docs/files/2459600/18100312220629.txt)
(Filname is YYMMDDTTmmxxxxx)

Endpoint:
https://lprws-test.sds.dsdn.dk/cda-ws/DocumentRepository_Service/PatientHealthcareReportingService

**Comment by p-christensen** [comment]
**RESOLUTION**
During document replacement existing encounters was not removed.

This has been fixed.
