### ISSUE TITLE
Straksvalidering i forbindelse med børn

### ISSUE THREAD

**Issue by MartinHylleberg** [scandihealth/lpr3-docs#2]
Hejsa

I forbindelse med straksvalidering har vi identificeret følgende som vi er usikker på:

- Foreløbigt indberettet: Et forløbselement med en (eller flere) kontakt.

- Begge er indrapporteret for sig, altså først indberettes forløbselement, derefter indberettes kontakt med reference til forløbselement.

- Nu forsøger vi at flytte tidspunkt på forløbselement således at kontakten ikke ligger inden for forløbselementets tid. 

Da det kun er forløbselementet der er ændret vil det kun være det som vi sender til valideringsservice for at få valideret. Hvordan forholder validerings servicen sig til det? Vi vil naturligvis i forbindelse med en eventuel indberetning få kontakten på ftp fejllisten, men hvad får vi at vide af valideringsservicen? Får vi at vide at der vil være en kontakt der vil blive invalid hvis man indberetter forløbselement  ?

**Comment by jkiddo-dxc** [comment]
>  Får vi at vide at der vil være en kontakt der vil blive invalid hvis man indberetter forløbselement ?

Ja
