### ISSUE TITLE
Art-decor vs indberetningsvejledning

### ISSUE THREAD

**Issue by MartinHylleberg** [scandihealth/lpr3-docs#20]
Vi har identificeret en forskel mellem art-decor og indberetningsvejledningen i forhold til cardinalitet på felter. Se nedenfor

For patientens adresse kan vi se følgende:

Felt | Indberetningsvejledning | Art-decor
------------ | ------------- | -------------
Landekode (country) | 1 | 1
kommunekode(county) | 0..1 | 0..1
addresselinie(streetAddressLine) | 0..* | 1..4
city | NA | 1..1

Som i kan se er der flere felter i art-decor som er krævede felter, hvorimod der fra indberetnings vejledningen kun er påkrævet en landekode.

Kan i fortælle hvilken der er den korrekte?

Som udgangspunkt ser vi det som det optimale med en så lav en cardinalitet som muligt, altså at at det er indberetningsvejledningen der følges, da det ikke altid vil være muligt at have alle informationer til rådighed.

**Comment by cjonigkeit-csc** [comment]
Indberetningssnitfladen er underlagt en række krav, som ikke udelukkende stammer fra indberetningsvejledningen, som bl.a. DK CDA Header, DGWS, IHE XDR, CDA R2.
Krav om adresseline og city kommer fra DK CDA Header.
Det er dermed samtlige krav fra samtlige rammeværktøjer og de dynamiske regler gældende i Indberetningsvejledningen, der skal opfyldes for at kunne indberette.
Vi anbefaler at indberettere kender r

**Comment by cjonigkeit-csc** [comment]
Vi anbefaler at indrettere kender rammeværktøjerne ned i detaljer for at modgå overraskelser. Indbettere kan få dispensation for dynamiske regler under bestemte situationer, men ikke for statiske regler. Et eksempel er den dynamiske regel 0201, som kræver at forløbssluttidspunkt er efter starttidspunkt. Dispensation for denne regel har ingen effekt for indberetninger via WS snitfladen pga. Afsnit 3.62 i HL7 Data Types - Abstract Specification Release 1, 2004

**Comment by cjonigkeit-csc** [comment]
In the future please use english.

**Comment by cjonigkeit-csc** [comment]
Hi @MartinHylleberg
@DaveSS has pointed out that you can use nullFlaver on postalCode, addressLine, and city.
If you do not have that information in your system, you can send something similar to this
```xml
<addr use="H">
  <streetAddressLine nullFlavor="NI"/>
  <postalCode nullFlavor="NI"/>
  <city nullFlavor="NI"/>
  <country>Danmark</country>
</addr>```

You can see [an example in our staging environment.](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.127&effectiveDate=2017-12-11T00:00:00)
