### ISSUE TITLE
MYNDIGHED_CODE_NOT_FOUND|||0009

### ISSUE THREAD

**Issue by finnha** [scandihealth/lpr3-docs#208]
Can you tell why I get the error:

"INTEGRITY_CHECK|||Myndighedskode 0009 not found in the registry|||MYNDIGHED_CODE_NOT_FOUND|||0009"

CDA document and error file attached

[f7_error.txt](https://github.com/scandihealth/lpr3-docs/files/2509769/f7_error.txt)
[f7.txt](https://github.com/scandihealth/lpr3-docs/files/2509770/f7.txt)

**Comment by TueCN** [comment]
Hi,

It seems the municipality code 0009 (Kommune Ukendt) has not been loaded into LPR from CPR's [Myndighedsregister](https://www.cpr.dk/kunder/gratis-download/myndighedsregister-og-udtraeksbeskrivelse/). 
This is a bug.

You are using the code as the municipality code of the address of a patient with an alternative identification: 

```xml
<patientRole classCode="PAT">
    <templateId root="1.2.208.176.7.1.10.107"/>
    <id root="9E8AA121-92BB-5592-9B68-75FBBB209C42" extension="1610610SG1" assigningAuthorityName="Region Midtjylland"/>
    <addr>
        <streetAddressLine nullFlavor="NI"/>
        <postalCode nullFlavor="NI"/>
        <city nullFlavor="NI"/>
        <county>0009</county>
        <country>5999</country>
    </addr>
    <patient classCode="PSN">
        <name>
            <family>LPR syvende gang</family>
            <given>Finn</given>
        </name>
        <administrativeGenderCode code="M" codeSystem="2.16.840.1.113883.5.1" displayName="Male"/>
    </patient>
</patientRole>
```

While we fix this error you can work around it by changing the municipality code to one of the other legal values, e.g. `0101`

**Comment by TueCN** [comment]
**RESOLUTION**
Now LPR3 loads the code 0009 from CPR's Myndighedsregister and it can now be used in submissions.

**Comment by TueCN** [comment]
@finnha I assume the solution worked for you. I am closing the issue, but feel free to reopen the issue if it has not been resolved.
