### ISSUE TITLE
sFTP vs FTPs

### ISSUE THREAD

**Issue by MartinHylleberg** [scandihealth/lpr3-docs#21]
[Supported reporting strategies](https://scandihealth.github.io/lpr3-docs/aspects/index.html#supported-reporting-strategies) nævner at det er mulig at hente forretningsfejl (level 3) ved hjælp af sFTP.

For god ordens skyld vil vi gerne lige have afklaret om der menes sFTP eller FTPs, altså er det 
"SSH File Transfer Protocol" eller er det "FTP over SSL"?

**Comment by cjonigkeit-csc** [comment]
Der er tale om S-FTP, FTP-SSL, FTPS, eller FTP Secure

**Comment by cjonigkeit-csc** [comment]
In the future please use english.

**Comment by jkiddo** [comment]
FTPS is not an option. Only SFTP is supported

**Comment by jkiddo** [comment]
The solution will support FTPS with mutual authentication based on OCES

**Comment by maagaard-DXC** [comment]
Clarification: According to decision from SDS only sFTP is supported.
