### ISSUE TITLE
id@root value in Alternatively Identified Patient Role

### ISSUE THREAD

**Issue by metodikamikaelnilsson** [scandihealth/lpr3-docs#210]
What value should be set in id@root in Alternatively Identified Patient Role?

Sometimes it is a oid:

United States drivers license number (Nevada)
```xml
<id root="2.16.840.1.113883.4.3" extension="X+24483652"/>
```

Sometimes it is a uuid:

ErstatningsCPRnummer Region Nordjylland
```xml
<id root="E45407A7-86EC-5AA4-A08B-0B33A62A1127" extension="08119675AG1" assigningAuthorityName="Region Nordjylland"/>
```

Where can I find information on what value to put in this attribute?

**Comment by jonigkeit** [comment]
Any registered OID is valid as long as your in control of it's id space.
If you do not have a registered oid use a version 5 UUID and make sure that it will not clash, by for instance using a namespace specific for your reporting authority.  When using a UUID you must retain its schematics at all times and provide the schemantics upon request.

**Comment by metodikamikaelnilsson** [comment]
You say that "any registered OID" is valid. Where are these OID's registered? How do we fetch these OIDs? For example, let's say that I want to retrieve the OID for swedish person numbers, where would I fetch that?

**Comment by jkiddo** [comment]
@metodikamikaelnilsson http://oid-info.com/get/1.2.752.59 could be a valid guess since 1.2.752.59 is the registered OID of Skatteverket being the authority of the SSN's in Sweden, AFAIK.

**Comment by metodikamikaelnilsson** [comment]
Thanks for the link. One more question regarding this issue: I see in the examples at [art-decor](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-) that the id@root for Erstatnings CPR nummer is set to a UUID (E45407A7-86EC-5AA4-A08B-0B33A62A1127). Does this mean that there doesn't exist any OID for danish erstatningsnummer? Should this UUID always be used when setting id@extension to a danish erstatningsnummer?

**Comment by jkiddo** [comment]
There isn't any central authority governing replacement SSNs in Denmark - there are only guidelines. As a consequence, there isn't any central OID for danish replacement SSNs (erstatningsnummer)

**Comment by metodikamikaelnilsson** [comment]
Ok, so when dealing with replacement SSN we create a UUID according to the description:

> Any registered OID is valid. If you do not have a registered oid, use a version 5 UUID and make sure that it will not clash, by for instance using a namespace specific for your reporting authority. When using a UUID you must retain its schematics at all times and provide the schemantics upon request.

**Comment by metodikamikaelnilsson** [comment]
Should danish replacement SSNs from different regions have different UUIDs, or can all have the same UUID?

**Comment by metodikamikaelnilsson** [comment]
I just need a little bit more clarification before I can close this issue.

1. Lets say we create an UUID for erstatningsnummer issued in Nord Jylland: "ABC123" (I use an abbreviation for simplification). We use this exact UUID for all erstatningsnummer issued in Nord Jylland when we send in clinical documents to the LPR3 registry. Another company also creates a UUID for erstatningsnummer issued in Nord Jylland, but theirs is: "DEF456". As I understand, the LPR3 registry is constructed so that this isn't a problem?

2. When using an UUID instead of an OID, there is no way to know which type of ID is used. It could e.g. be a colombian driving license number, or a danish erstatningsnummer. So I guess this doesn't matter as long as we always map a particular type of ID to the same UUID?

3. When creating a UUID for a particular type of alternative ID, it doesn't matter which name and namespace that is used to create this UUID, as long as the UUID doesn't clash with another UUID used as the root value for another alternative ID type?

**Comment by metodikamikaelnilsson** [comment]
Thanks for the clarification.
