### ISSUE TITLE
Test-LPR3 - not possibe to search for CPR

### ISSUE THREAD

**Issue by AnneRegionSyd** [scandihealth/lpr3-docs#211]
In Test-LPR3 it's not possible to search for a CPR. I get a java runtime error message saying "The server is temporary unavailable"... See attatched file. 
It is possible to search for errors but not CPR.

**Comment by AnneRegionSyd** [comment]
[Java error Test LPR3.docx](https://github.com/scandihealth/lpr3-docs/files/2525656/Java.error.Test.LPR3.docx)

**Comment by simon-dxc** [comment]
DXC are working on this

**Comment by TueCN** [comment]
**RESOLUTION** 
All searches performed from "LPR3 - Vis indberetninger" UI has been optimized and finishes faster than before. 
Note that searching without any search criteria restrictions might still cause timeouts (Service Unavailable error message). This depends on the user's SEB permissions and the amount of data in the registry.
