### ISSUE TITLE
Error: soap:Server>result returns more than one elements

### ISSUE THREAD

**Issue by Marc-Petersen** [scandihealth/lpr3-docs#215]
Since Nov 1st. 11:13 **all** our submitted reports have failed with:
![image](https://user-images.githubusercontent.com/44767916/47988130-af69a580-e0e1-11e8-91d3-e658100dbdff.png)
_Error: soap:Server>result returns more than one elements_

We using the https://lprws-test.sds.dsdn.dk/cda-ws/DocumentRepository_Service/PatientHealthcareSaveIfNoErrorsReportingService endpoint.
We're reporting from Region H/SJ.

The error text indicates that elements have multiple IDs (and since it affects all our submissions) - possibly multiple elements.

**Comment by TueCN** [comment]
Hi @Marc-Petersen could you please provide an example of a request that fails? 
(including SOAP headers, I suspect it might have to do with the medcom:CareProviderID CVR-no or XDR authorInstitution SOR-id you are using).

I just tested the service and it responds as normal to our test requests.

**Comment by Marc-Petersen** [comment]
[msg-16361695.txt](https://github.com/scandihealth/lpr3-docs/files/2548320/msg-16361695.txt)

Hope this is want you're looking for...

**Comment by TueCN** [comment]
Yes it is as I suspected. 
There is a configuration problem in the service which causes failures for submissions using the CVR-no 29190623 as medcom:CareProviderID.

We are working with SDS to rectify the situation

**Comment by simon-dxc** [comment]
Hi @Marc-Petersen 
Could you please check if it's working now?

**Comment by Marc-Petersen** [comment]
Yes. It looks much better now. Queue is getting smaller and we're getting responses now. What has changed?
