### ISSUE TITLE
The LPR3 administration client is slow

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#219]
We are experiencing that the LPR3 administration client is getting slower and slower. 

Today the LPR3 client spend more than 40 seconds in order perform a search on CPR number - even though the patient only have a very limited amount of data.

This low performance is blocking the system test that we are currently performing.

**Comment by jonigkeit** [comment]
We are aware of response times in the test environment. Please direct inquiries regarding service levels and performance to the project group at the Danish National Health Data Agency.

**Comment by maagaard-DXC** [comment]
DXC is currently working on improving response time on the test environment.

**Comment by SorenTL** [comment]
Update. It seems as if the service has come to a complete stop. The following af error respons is being showed as soon the "søg" button is pushed. No data is being loaded.


java.lang.RuntimeException: Load failure: Type 'com.extjs.gxt.ui.client.data.BasePagingLoadConfig' was not assignable to 'com.google.gwt.user.client.rpc.IsSerializable' and did not have a custom field serializer. For security purposes, this type will not be deserialized.

![loadfailure](https://user-images.githubusercontent.com/44675699/48472022-935ab800-e7f5-11e8-897d-4847ab21cd20.gif)

**Comment by MichaelEsmannSSE** [comment]
I had the same problem. For me it was sufficient to press Ctrl-F5 in IE.
But searching on a CPR number is stil VERY slow. It takes about 100 seconds

**Comment by maagaard-DXC** [comment]
As DXC continues working on a solution to the problem here is a hint to reduce the impact on searches in the administration client.

Please select:
- An "Institutionsejer" - for instance "Region Midtjylland" combined with a "Søgetype for ansvarlig enhed" for instance "Forløb".
- A time interval in the "Valideret" field - for instance 2 days

-

**Comment by TueCN** [comment]
**RESOLUTION** 
All searches performed from "LPR3 - Vis indberetninger" UI has been optimized and finishes faster than before. 
Note that searching without any search criteria restrictions might still cause timeouts (Service Unavailable error message). This depends on the user's SEB permissions and the amount of data in the registry.

**Comment by RasmusThernoe** [comment]
Performance significantly improved -  thank you for the fix.
