### ISSUE TITLE
Indberetnings rækkefølge

### ISSUE THREAD

**Issue by MartinHylleberg** [scandihealth/lpr3-docs#22]
Givet følgende CDA dokumenter:

* 1 dokument indeholdende forløbselement A
  * Document version: 1
  * Document id: AAA-BBB-AAA
  * SetId AAA-BBB
* 1 dokument indeholdende kontakt B
  * Document version: 2
  * Document id: AAA-BBB-BBB
  * SetId AAA-BBB
* 1 dokument indeholdende procedure C
  * Document version: 3
  * Document id: AAA-BBB-CCC
  * SetId AAA-BBB

Dokumenterne afsendes nu i følgende rækkefølge: document AAA-BBB-CCC, så AAA-BBB-BBB og til sidst AAA-BBB-AAA (version 3, så version 2, så version 1).

Return værdien fra webservicen forventes at være følgende:
* AAA-BBB-CCC: Forretningsfejl - manglende objekt reference, kontakt AAA-BBB-BBB eksisterer ikke
* AAA-BBB-BBB: Forretningsfejl - manglende objekt reference, forløbselement AAA-BBB-AAA eksisterer ikke
* AAA-BBB-AAA Ingen fejl

**Forventning/spørgsmål:**
Return værdien fra hver indrapportering gælder kun for det element der indsendes, altså når AAA-BBB-BBB indsendes vil man ikke kunne se at fejlen fra AAA-BBB-CCC er løst?

**Forventing/Spørgsmål:**
Når den akkumulerede fejllisten hentes, vil man ikke kunne se de to initielle fejl der er i ovenstående indrapportering, da fejlene var løst da AAA-BBB-AAA dokumentet blev indberettet?

Altså, det forventes at  indsendingsrækkefølgen for dokumenterne er irrelevant, så længe at versionsnumrene stemmer overens?

**Comment by cjonigkeit-csc** [comment]
En indberetning, der ikke overholder de _statiske_ regler **afvises** uagtet om den ønskes gemt _med eller uden_ fejl.
En indberetning, der overholder de _statiske_ regler men ikke overholder de _dynamiske_ regler **afvises**, hvis den ønskes gemt _uden_ fejl.
En indberetning, der overholder de _statiske_ regler men ikke overholder de _dynamiske_ regler **accepteres (markeres som fejlfyldt)**, hvis den ønskes gemt _med_ fejl.

**ALGORITME** | Gem uden fejl|Gem med fejl
--------- | ----------- | -----------
overholder ikke statiske regler | afvises | afvises
overholder statiske men ikke dynamiske regler | afvises | accepteres (markeres som fejlfyldt)
overholder statiske og dynamiske regler | accepteres | accepteres

Det beskrevne scenarie mangler væsentlige informationer om værdier for XPath udtryk

1. /ClinicalDocument/id/@root
2. /ClinicalDocument/id/@extension
3. /ClinicalDocument/setId/@root
4. /ClinicalDocument/versionNumber/@value
5. /ClinicalDocument/relatedDocument/parentDocument/id/@root
6. /ClinicalDocument/relatedDocument/parentDocument/id/@extension
7. /ClinicalDocument/relatedDocument/parentDocument/setId/@root
8. /ClinicalDocument/relatedDocument/parentDocument/versionNumber/@value

samt om disse ClinicalDocument'er sendes i samme XDR Request i forskellige Submission Set eller i forskellige XDR Requests, førend vi kan give et præcist svar.

Uagtet den mangelfulde beskrivelse, tror vi at det der prøves beskrevet ved scenariet vil have følgende result:
- _Kun_ AAA-BBB-AAA accepteres, såfremt der er tale om forskellige XDR requests
- Alle ClinicalDocument'er accepteres, såfremt der er tale om samme XDR request men forskellige submission sets.

**Comment by cjonigkeit-csc** [comment]
In the future please use english.
