### ISSUE TITLE
What is the difference between DK Internal Episode Of Care Reference and DK External Episode Of Care Reference?

### ISSUE THREAD

**Issue by metodikamikaelnilsson** [scandihealth/lpr3-docs#220]
What is the difference between DK Internal Episode Of Care Reference and DK External Episode Of Care Reference?

Do the root value of the DK External Episode Of Care Reference reference the setId of another clinical document?

**Comment by TueCN** [comment]
Hi,
there are 3 types of EoC references and their differences are explained in the description of the root and extension attributes of the hl7:id element

- DK Internal Episode Of Care Reference
    - The value of @root must be the same as the value of the containing ClinicalDocument setId root attribute
    - The value of @extension shall be a version 5 UUID to an episode of care within the encompassing CDA document instance
- DK External Episode Of Care Reference
    - The value of @root must be the same as the value of the containing ClinicalDocument setId root attribute. Ensuring that references can only be made to an external episode of care within the same set
    - The value of @extension shall be a version 5 UUID to an existing episode of care
- DK Set External Episode Of Care Reference
    - the value of @root shall be a version 5 UUID to an existing or future episode of care
        - Note: This means that the referenced EoC does not have to exist in the registry and even if it does, does not need to belong to the same setId as this CDA document

**Comment by metodikamikaelnilsson** [comment]
So, to clarify, do the word "External" in DK External Episode of Care mean that the episode of care that is referenced belongs to another CDA document?

**Comment by TueCN** [comment]
Sorry I just updated my answer as you were commenting. 
- "Set External" can reference an existing or non-existing EoC in any set (this can be useful if the EoC was created and referenced in systems external to LPR, but not yet submitted to LPR)
- "External" can reference a EoC in another CDA document **of the same set**
