### ISSUE TITLE
Change of Author

### ISSUE THREAD

**Issue by kdjohansson** [scandihealth/lpr3-docs#221]
Will it be allowed to change authorInstitution (SOR code) from one clinical document version to another (within the same set)? A reason could for example be organizational changes. And would global identifiers already generated and reported based on original author still be "appropriate" to use within the already started episode of care?

**Comment by TueCN** [comment]
Currently it is technical possible, but I am not sure whether the CDA standard allows it. 

According to [Danish Metadata profile](http://svn.medcom.dk/svn/drafts/Standarder/IHE/DK_profil_metadata/Metadata-v095.docx) the XDR attribute authorInstitution must have same values as 

> CDA reference: 
> 
> The mapping shall include the following values from the CDA as listed below.
> 
> The name of the institution:
> $displayName = **ClinicalDocument/author/assignedAuthor/representedOrganization/name**
> 
> The associated OID for “Sundhedsvæsenets Organisations Register” (SOR):
> $codeSystem = **ClinicalDocument/author/assignedAuthor/id/@root**
> 
> The id for the institution in “Sundhedsvæsenets Organisations Register”:
> $code = **ClinicalDocument/author/assignedAuthor/id/@extension**
> 
> Example values in the DK PHMR CDA is:
> $code = “88878685”
> $displayName = “Odense Universitetshospital – Svendborg Sygehus”
> $codeSystem = ”1.2.208.176.1.1”
> 
> XML example:
> 
> ```xml
> <rim:Slot name="authorInstitution">
>     <rim:ValueList>
>         <rim:Value>Odense Universitetshospital – Svendborg Sygehus^^^^^&
>              1.2.208.176.1.1&ISO^^^^88878685</rim:Value>
>     </rim:ValueList>
> </rim:Slot>
> ```

So it depends on whether you is allowed to update the **assignedAuthor** element in a CDA document. 
@jkiddo can you help clarify if this is allowed?

**Comment by jkiddo** [comment]
As long as the XDR metadata reflects the content of the CDA - meaning that the document adhere to the spec, I don't think there is any technical problem. It more depends on the business rules of LPR3 @TueCN
