### ISSUE TITLE
DateTime (TS element) issues

### ISSUE THREAD

**Issue by ScaAnders** [scandihealth/lpr3-docs#222]
I am trying to submit a clinical documents but get some issues with 'ts' elements not being in correct format. So I then tried to submit the sample xml you provide on the following url:
http://lpr-art-decor.westeurope.cloudapp.azure.com:8000/decor/services/RetrieveTemplate?prefix=lpr-&version=&language=en-US&id=1.2.208.176.7.1.10.71&effectiveDate=2018-01-04T00%3A00%3A00&format=html&collapsable=true&inline=true#

However I am getting the same time issues with the sample xml - this is the errors from the sample xml:

ErrorCode: InvalidDocumentContent
Location: 550e8400-e29b-41d4-a716-446655440000^2159b2c3-fa2d-4d8e-9af4-995893b12b39|||55:53
CodeContext: XSD|||cvc-pattern-valid: Value '20170222110000+02:00' is not facet-valid with respect to pattern '[0-9]{1,8}|([0-9]{9,14}|[0-9]{14,14}\.[0-9]+)([+\-][0-9]{1,4})?' for type 'ts'.

ErrorCode: InvalidDocumentContent
Location: 550e8400-e29b-41d4-a716-446655440000^2159b2c3-fa2d-4d8e-9af4-995893b12b39|||55:53
CodeContext: XSD|||cvc-attribute.3: The value '20170222110000+02:00' of attribute 'value' on element 'low' is not valid with respect to its type, 'ts'.

ErrorCode: InvalidDocumentContent
Location: 550e8400-e29b-41d4-a716-446655440000^2159b2c3-fa2d-4d8e-9af4-995893b12b39|||56:54
CodeContext: XSD|||cvc-pattern-valid: Value '20170222150000+02:00' is not facet-valid with respect to pattern '[0-9]{1,8}|([0-9]{9,14}|[0-9]{14,14}\.[0-9]+)([+\-][0-9]{1,4})?' for type 'ts'.

ErrorCode: InvalidDocumentContent
Location: 550e8400-e29b-41d4-a716-446655440000^2159b2c3-fa2d-4d8e-9af4-995893b12b39|||56:54
CodeContext: XSD|||cvc-attribute.3: The value '20170222150000+02:00' of attribute 'value' on element 'high' is not valid with respect to its type, 'ts'.

Can you resolve the issues in the sample xml, so that we have a "baseline" document that we know is valid and can be submitted?
Thanks.

**Comment by jkiddo** [comment]
The bug is that the timestamps contain a ':'

**Comment by ScaAnders** [comment]
Is it possible that you can have a look at the sample xml you detail on the LPR-Art-Decor site because after I removed the character ':', multiple additional errors have turned up.

**Comment by TueCN** [comment]
**RESOLUTION**
The example on [DK Episode Of Care Summaries Document](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.71&effectiveDate=2018-01-04T00:00:00) has been updated and is now a structurally valid document that contains a few BUSINESS_RULE errors.

**Comment by ScaAnders** [comment]
Thanks!
