### ISSUE TITLE
TargetSiteCode doesn't get deleted when a diagnose is updated without it.

### ISSUE THREAD

**Issue by adrianpredam** [scandihealth/lpr3-docs#224]
**targetSiteCode** doesn't get deleted when a diagnose is updated without it.
Steps to reproduce it: 
- Create a diagnose under an encounter with targetSiteCode (see attached **diagnosis_with_target_site_code.xml** from targetsite.zip)
- Update the diagnose by removing the targetSiteCode (see attached **diagnosis_without_target_site_code.xml** from targetsite.zip)

Result: The targetSideCode still present conforming to the SDS client (see attached **Inkedsds_bodysite (002)_LI.jpg**  from targetsite.zip)

 [targetsite.zip](https://github.com/scandihealth/lpr3-docs/files/2572284/targetsite.zip)

**Comment by adrianpredam** [comment]
[targetsite.zip](https://github.com/scandihealth/lpr3-docs/files/2572287/targetsite.zip)

**Comment by TueCN** [comment]
Sorry, no ETA currently

**Comment by TueCN** [comment]
**RESOLUTION** 
Fixed bug that prevented removal of TargetSiteCode when replacing a condition observation

**Comment by adrianpredam** [comment]
Tested successfully
