### ISSUE TITLE
Valid ClinicalDocument sample

### ISSUE THREAD

**Issue by ScaAnders** [scandihealth/lpr3-docs#225]
We have received a ClinicalDocumnt sample that should valid and possible to submit (please see the attached document). When we try to submit the document we get 16 errors:
ErrorCode: InvalidDocumentContent
Location: B83B76C3-A7E0-4C1F-B599-5F027BD93682^550e8400-e29b-41d4-a716-446655440000|||/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][4]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][7]/*:procedure[namespace-uri()='urn:hl7-org:v3'][1]/*:participant[namespace-uri()='urn:hl7-org:v3'][1]/*:participantRole[namespace-uri()='urn:hl7-org:v3'][1]
CodeContext: SCHEMATRON|||(DKProcedureProducerParticipationBody): The value for @classCode SHALL be 'ROL'.

ErrorCode: InvalidDocumentContent
Location: B83B76C3-A7E0-4C1F-B599-5F027BD93682^550e8400-e29b-41d4-a716-446655440000|||/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][1]/*:act[namespace-uri()='urn:hl7-org:v3'][1]/*:entryRelationship[namespace-uri()='urn:hl7-org:v3'][1]/*:act[namespace-uri()='urn:hl7-org:v3'][1]/*:participant[namespace-uri()='urn:hl7-org:v3'][1]/*:participantRole[namespace-uri()='urn:hl7-org:v3'][1]
CodeContext: SCHEMATRON|||(DKReferrerParticipantBody): The value for @classCode SHALL be 'ROL'.

ErrorCode: InvalidDocumentContent
Location: B83B76C3-A7E0-4C1F-B599-5F027BD93682^550e8400-e29b-41d4-a716-446655440000|||/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][4]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][3]/*:procedure[namespace-uri()='urn:hl7-org:v3'][1]/*:participant[namespace-uri()='urn:hl7-org:v3'][1]/*:participantRole[namespace-uri()='urn:hl7-org:v3'][1]
CodeContext: SCHEMATRON|||(DKProcedureProducerParticipationBody): The value for @classCode SHALL be 'ROL'.

ErrorCode: InvalidDocumentContent
Location: B83B76C3-A7E0-4C1F-B599-5F027BD93682^550e8400-e29b-41d4-a716-446655440000|||/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][4]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][11]/*:procedure[namespace-uri()='urn:hl7-org:v3'][1]/*:participant[namespace-uri()='urn:hl7-org:v3'][1]/*:participantRole[namespace-uri()='urn:hl7-org:v3'][1]
CodeContext: SCHEMATRON|||(DKProcedureProducerParticipationBody): The value for @classCode SHALL be 'ROL'.

ErrorCode: InvalidDocumentContent
Location: B83B76C3-A7E0-4C1F-B599-5F027BD93682^550e8400-e29b-41d4-a716-446655440000|||/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][1]/*:act[namespace-uri()='urn:hl7-org:v3'][1]/*:participant[namespace-uri()='urn:hl7-org:v3'][1]/*:participantRole[namespace-uri()='urn:hl7-org:v3'][1]
CodeContext: SCHEMATRON|||(DKResponsibleUnitParticipantBody): The value for @classCode SHALL be 'ROL'.

ErrorCode: InvalidDocumentContent
Location: B83B76C3-A7E0-4C1F-B599-5F027BD93682^550e8400-e29b-41d4-a716-446655440000|||/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][4]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][5]/*:procedure[namespace-uri()='urn:hl7-org:v3'][1]/*:participant[namespace-uri()='urn:hl7-org:v3'][1]/*:participantRole[namespace-uri()='urn:hl7-org:v3'][1]
CodeContext: SCHEMATRON|||(DKProcedureProducerParticipationBody): The value for @classCode SHALL be 'ROL'.

ErrorCode: InvalidDocumentContent
Location: B83B76C3-A7E0-4C1F-B599-5F027BD93682^550e8400-e29b-41d4-a716-446655440000|||/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][4]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][6]/*:procedure[namespace-uri()='urn:hl7-org:v3'][1]/*:participant[namespace-uri()='urn:hl7-org:v3'][1]/*:participantRole[namespace-uri()='urn:hl7-org:v3'][1]
CodeContext: SCHEMATRON|||(DKProcedureProducerParticipationBody): The value for @classCode SHALL be 'ROL'.

ErrorCode: InvalidDocumentContent
Location: B83B76C3-A7E0-4C1F-B599-5F027BD93682^550e8400-e29b-41d4-a716-446655440000|||/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][4]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][1]/*:procedure[namespace-uri()='urn:hl7-org:v3'][1]/*:participant[namespace-uri()='urn:hl7-org:v3'][1]/*:participantRole[namespace-uri()='urn:hl7-org:v3'][1]
CodeContext: SCHEMATRON|||(DKProcedureProducerParticipationBody): The value for @classCode SHALL be 'ROL'.

ErrorCode: InvalidDocumentContent
Location: B83B76C3-A7E0-4C1F-B599-5F027BD93682^550e8400-e29b-41d4-a716-446655440000|||/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][4]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][9]/*:procedure[namespace-uri()='urn:hl7-org:v3'][1]/*:participant[namespace-uri()='urn:hl7-org:v3'][1]/*:participantRole[namespace-uri()='urn:hl7-org:v3'][1]
CodeContext: SCHEMATRON|||(DKProcedureProducerParticipationBody): The value for @classCode SHALL be 'ROL'.

ErrorCode: InvalidDocumentContent
Location: B83B76C3-A7E0-4C1F-B599-5F027BD93682^550e8400-e29b-41d4-a716-446655440000|||/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][4]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][2]/*:procedure[namespace-uri()='urn:hl7-org:v3'][1]/*:participant[namespace-uri()='urn:hl7-org:v3'][1]/*:participantRole[namespace-uri()='urn:hl7-org:v3'][1]
CodeContext: SCHEMATRON|||(DKProcedureProducerParticipationBody): The value for @classCode SHALL be 'ROL'.

ErrorCode: InvalidDocumentContent
Location: B83B76C3-A7E0-4C1F-B599-5F027BD93682^550e8400-e29b-41d4-a716-446655440000|||/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][4]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][10]/*:procedure[namespace-uri()='urn:hl7-org:v3'][1]/*:participant[namespace-uri()='urn:hl7-org:v3'][1]/*:participantRole[namespace-uri()='urn:hl7-org:v3'][1]
CodeContext: SCHEMATRON|||(DKProcedureProducerParticipationBody): The value for @classCode SHALL be 'ROL'.

ErrorCode: InvalidDocumentContent
Location: B83B76C3-A7E0-4C1F-B599-5F027BD93682^550e8400-e29b-41d4-a716-446655440000|||/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][4]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][4]/*:procedure[namespace-uri()='urn:hl7-org:v3'][1]/*:participant[namespace-uri()='urn:hl7-org:v3'][1]/*:participantRole[namespace-uri()='urn:hl7-org:v3'][1]
CodeContext: SCHEMATRON|||(DKProcedureProducerParticipationBody): The value for @classCode SHALL be 'ROL'.

ErrorCode: InvalidDocumentContent
Location: B83B76C3-A7E0-4C1F-B599-5F027BD93682^550e8400-e29b-41d4-a716-446655440000|||/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][2]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][1]/*:encounter[namespace-uri()='urn:hl7-org:v3'][1]/*:participant[namespace-uri()='urn:hl7-org:v3'][1]/*:participantRole[namespace-uri()='urn:hl7-org:v3'][1]
CodeContext: SCHEMATRON|||(DKResponsibleUnitParticipantBody): The value for @classCode SHALL be 'ROL'.

ErrorCode: InvalidDocumentContent
Location: B83B76C3-A7E0-4C1F-B599-5F027BD93682^550e8400-e29b-41d4-a716-446655440000|||/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:custodian[namespace-uri()='urn:hl7-org:v3'][1]/*:assignedCustodian[namespace-uri()='urn:hl7-org:v3'][1]/*:representedCustodianOrganization[namespace-uri()='urn:hl7-org:v3'][1]/*:id[namespace-uri()='urn:hl7-org:v3'][1]
CodeContext: SCHEMATRON|||(DKCustodian): The value of the @extension SHALL be a valid Danish Business Identification number (cvr-nummer)

ErrorCode: InvalidDocumentContent
Location: B83B76C3-A7E0-4C1F-B599-5F027BD93682^550e8400-e29b-41d4-a716-446655440000|||/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:custodian[namespace-uri()='urn:hl7-org:v3'][1]/*:assignedCustodian[namespace-uri()='urn:hl7-org:v3'][1]/*:representedCustodianOrganization[namespace-uri()='urn:hl7-org:v3'][1]/*:id[namespace-uri()='urn:hl7-org:v3'][1]
CodeContext: SCHEMATRON|||(DKCustodian): The value for @assigningAuthorityName SHALL be 'Erhvervs- og Selskabsstyrelsen'.

ErrorCode: InvalidDocumentContent
Location: B83B76C3-A7E0-4C1F-B599-5F027BD93682^550e8400-e29b-41d4-a716-446655440000|||/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][4]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][8]/*:procedure[namespace-uri()='urn:hl7-org:v3'][1]/*:participant[namespace-uri()='urn:hl7-org:v3'][1]/*:participantRole[namespace-uri()='urn:hl7-org:v3'][1]
CodeContext: SCHEMATRON|||(DKProcedureProducerParticipationBody): The value for @classCode SHALL be 'ROL'.

Is it possible that you can refine the example or send a new sample?

[CDA_01.zip](https://github.com/scandihealth/lpr3-docs/files/2576490/CDA_01.zip)

**Comment by KirstenLHSDS** [comment]
@DXC - the example is provided by a SDS-employee, I will ask him. @ScaAnders please check dokumentation

**Comment by jonigkeit** [comment]
I assume you’re experiencing the same issue as in #226. Please try again using XOP/MTOM encoding.

**Comment by ScaAnders** [comment]
Yes, it is related to #226
