### ISSUE TITLE
Chrome / search & time out

### ISSUE THREAD

**Issue by KirstenLHSDS** [scandihealth/lpr3-docs#229]
On request from Tom / Region Nordjylland: 

Generelt har jeg sagtens kunnet bruge Chrome – og har gjort det under hele vores test. Jeg plejer nok at få nogle Java fejl (På vejen ind – men ikke på selve søgesiden), men ikke noget der forhindrer mig i at bruge browseren (De plejer bare at kunne klikkes væk) – indtil i går.
Fejlen sker når jeg forsøger at søge data frem. Her får jeg nedenstående fejl, som man godt kan klikke væk, men siden bliver aldrig færdig med den søgning jeg har gang i.
 

Med venlig hilsen
Lasse Jensen
IT-konsulent
lasjen@rn.dk

REGION NORDJYLLAND
IT – Forvaltning, Drift og Support
Niels Bohrs Vej 30
9220 Aalborg Ø
![fejlrapport fra rn](https://user-images.githubusercontent.com/41285026/48623159-31db4a80-e9a9-11e8-8ea3-95947a241400.jpg)

www.rn.dk

**Comment by TueCN** [comment]
This is most likely a duplicate of https://github.com/scandihealth/lpr3-docs/issues/219#issuecomment-438590643

See https://github.com/scandihealth/lpr3-docs/issues/219#issuecomment-438594500 for resolution

**Comment by TueCN** [comment]
Hi @KirstenLHSDS, 
can you please verify with Tom whether the suggested solution resolved his issue?

**Comment by KirstenLHSDS** [comment]
Can be closed after confirmation with Tom
