### ISSUE TITLE
Relaxing exclusiveness of XSD, Schematron, integrity, and dynamic rules errors in response

### ISSUE THREAD

**Issue by cjonigkeit-csc** [scandihealth/lpr3-docs#23]
Due to significant reduction of response times, we are considering to relax the exclusiveness restriction on the types of errors an IHE XDR response can contain.
Parallel execution of all requirements; XSD, Schematron, integrity, and dynamic rules with a fail fast strategy will result in potential mixed and undeterministic list of errors in the IHE XDR Response.

**Comment by jkiddo** [comment]
Serial execution of requirements will be maintained during test and approval phases.

**Comment by jkiddo** [comment]
On another note, parallel validation can safely be conducted without involving 3.party or add relaxation. Using the following rule set, interface towards 3.party remains unchanged:

1) If schema errors are found, only return these 
2) If schematron errors are found, only return these (given that none are found at 1) )
- ... and so on

**Comment by cjonigkeit-csc** [comment]
@jkiddo - you forgot the fail fast part. As soon as a validator has failed, no new validator in the set of validators will run. E.g. when the integrity validator fails, before the schematron validator has started, it will not run. In your "rule set" that will still return zero schematron erros although the potentially could be some.
