### ISSUE TITLE
Expected CDA documents for the official integration tests

### ISSUE THREAD

**Issue by ScaAnders** [scandihealth/lpr3-docs#233]
We are to start the official integration test within a couple of weeks. Is it possible that we can have a look at the resulting CDA documents that you are expecting in order to pass the official tests?
If any clients already have passed the tests maybe you publish the these documents so that we can use these in our internal testing when generating the ClinicalDocuments. That would allow us to find a lot more errors before undergoing the official test.

**Comment by KirstenLHSDS** [comment]
In general, the tilslutningstest is supposed to document, that documents generated by the individual EPJ-system can be submitted, and the intention is, that the test is conducted after the project test. Hence, the examples above of valid CDA-documents will be the referencepoint. 
@ScaAnders as you have submitted and passed the Tilslutningstest, could you please validate this issue and close if possible
