### ISSUE TITLE
Import of ClinicalDocument

### ISSUE THREAD

**Issue by ScaAnders** [scandihealth/lpr3-docs#234]
Is there any way we can upload a ClinicalDocument to LPR3 without using the webservice? Something like an "import document" button within the UI?
That way we could just skip the complexity associated with the webservice, MTOM protocol, DGWS and just focus on the core document and the validation rules within LPR3.

**Comment by ScaAnders** [comment]
I need to point out that this is purely for testing purpose so that we can work in parallel with both the WS protocol and the CDA format itself.

**Comment by TueCN** [comment]
I am afraid not. 
The currently exposed endpoints are the only source of data entry into the registry.

**Comment by jonigkeit** [comment]
@ScaAnders you can request an enhancement through the project group at SDS. This could be a function in the UI or a CDA client capable of sending XDR request including DGWS
