### ISSUE TITLE
SKS codes rejected by LPR3

### ISSUE THREAD

**Issue by Marc-Petersen** [scandihealth/lpr3-docs#235]
We are submitting CDAs using a bleeding secondary diagnosis DO720 on delivery contacts. This diagnosis needs an add code with the amount of bleeding VPHxxxx (ex, VPH0450).
It is a code, that is used in LPR2, and it will stay in use for LPR3. 

However, we are getting rejected in the endpoint:
    <Header>
        <ep2:Header xmlns:ep2="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd">
            <ep2:SecurityLevel>3</ep2:SecurityLevel>
            <ep2:TimeOut></ep2:TimeOut>
            <ep2:Linking>
                <ep2:MessageID>597238-16678200-6496477108</ep2:MessageID>
            </ep2:Linking>
            <ep2:FlowStatus>flow_finalized_succesfully</ep2:FlowStatus>
            <ep2:RequireNonRepudiationReceipt>no</ep2:RequireNonRepudiationReceipt>
        </ep2:Header>
    </Header>
    <Body>
        <ep6:RegistryResponse xmlns:ep6="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure">
            <ep6:RegistryErrorList highestSeverity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error">
                <ep6:RegistryError codeContext="INTEGRITY_CHECK|||SKS kode VPH0450 not found from 2018-11-07T16:43+01:00 to 2018-11-08T09:53+01:00|||SKS_CODE_NOT_FOUND|||VPH0450|||2018-11-07T16:43+01:00|||2018-11-08T09:53+01:00" errorCode="InvalidDocumentContent" location="2220246C-E2C9-11E8-A49E-A1058FF62DB0^028AA656-E6B9-11E8-A8AE-A1058FF62DB0|||//*[@*='VPH0450']" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"></ep6:RegistryError>
            </ep6:RegistryErrorList>
        </ep6:RegistryResponse>
    </Body>
 
A member of our staff have been in contact with Ole B. Larsen (from SDS, I suspect), who confirm the validity of the codes.

Why are these CDAs being rejected?

**Comment by jonigkeit** [comment]
The code VPH0450 does not exist in ftp://filer.sst.dk/filer/sks/data/sks_xml/akt_version/SKSklassifikationspakke.zip or ftp://filer.sst.dk/filer/sks/data/skscomplete/SKScomplete.txt.

**Comment by Marc-Petersen** [comment]
This response is from our internal code-guy:
_It does exist in this folder:
ftp://filer.sst.dk/filer/sks/data/skscomplete/
In this document:
ftp://filer.sst.dk/filer/sks/data/skscomplete/SKTtot_2016-07.txt_

Does that not mean it should be supported?
Please advise.

**Comment by jonigkeit** [comment]
To avoid ultracrepidarianism, we will forward your inquiry to SDS.

**Comment by jonigkeit** [comment]
All codes in ftp://filer.sst.dk/filer/sks/data/skscomplete/SKTtot_2016-07.txt should be supported. This is a mistake on our behalf.

**Comment by EsbenHenrichsen** [comment]
Could you please submit an expected fix date? In RegionH we are trying to finalising our testing this week.

**Comment by TueCN** [comment]
Sorry we do not have expected fix dates for bugs in general. 
The next scheduled patch release is Tuesday 18th Dec, but this is not a small fix, and it is unsure if it will be ready for Tuesday.

**Comment by Julie-Marie** [comment]
Testet og passed

**Comment by Marc-Petersen** [comment]
We're getting hit with Invalid SKS code error again. 
![image](https://user-images.githubusercontent.com/44767916/52334806-eca34380-2a00-11e9-8f9e-8e222ecf667e.png)
Has validation rules changed on SDS side?

**Comment by p-christensen** [comment]
The SKS codes should be available tomorrow.

**Comment by Marc-Petersen** [comment]
Could this issue be reopened until solution is in place?
Is that something I can do?

**Comment by TueCN** [comment]
Do you not have a "Reopen" button under the comment text box?

By the way, we assume this issue is regarding PROD environment? Please specify which environment this re-opened issue is experienced on.

**Comment by Marc-Petersen** [comment]
Yes. Prod env.
No. just a comment button.

**Comment by TueCN** [comment]
@Marc-Petersen we have just manually updated the SKS classification in PROD and the 'tillægskoder' should now be updated. 

Please re-test

**Comment by Marc-Petersen** [comment]
Ok. The Invalid SKS code errors for these is gone. Resent messages has passed validation.
Please re-close. 
My Comment and Close button is missing.
