### ISSUE TITLE
Inconsistency in documentation of "Implantatoplysninger"

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#238]
There is an inconsistency in the description of the fields batch number + serial number between the LPR3 reporting guide (DA: Indberetningsvejledningen) version 1.2 and the result report specifications (DA: Resultatindberetningsspecifikationer (RI-specs) bilag 1a).

In the LPR3 reporting guide, page 207 states that at least one of the field most be filled:

> batch-lotnummer | 0..1   OR   serienummer | char | alfanumerisk | obligatorisk   enten batch-lotnummer eller serienummer. Begge kan indberettes.   Kan evt. hentes via skanningsfunktionalitet – se   også ’registreringstids- punkt’
> -- | -- | -- | -- | --
> serienummer | 0..1   OR   batch-lotnummer | char | alfanumerisk

In the result reporting specifications, page 10 states that if one is filled then the other must be filled or else both must be empty:

> IF   Resultat.vaerdi <> Null WHERE Resultat.type = {RDB04} THEN Required   ELSE Null | RDB03 | batch-lotnummer | 0..1 |   | char |   | gældende   standard | nej
> -- | -- | -- | -- | -- | -- | -- | -- | --
> IF   Resultat.vaerdi <> Null WHERE Resultat.type = {RDB03} THEN Required   ELSE Null | RDB04 | Serienummer | 0..1 |   | char |   | gældende standard | nej

In the result reporting specifications, page 10 it is also stated that one and only one of the fields must be filled:

> ”note 1: dette par af regler angiver at ét , men kun ét af disse to felter skal være udfyldt; udfyldningen af disse 2 felter er altså gensidigt udelukkende”

Which one is the right description?

**Comment by jonigkeit** [comment]
This seems to be question that is not regarding the XDR interface.

[How to contribute](https://github.com/scandihealth/lpr3-docs/blob/master/CONTRIBUTING.md)
> We will only answer questions directly concerning the technical parts of the interface the register, e.g. how to register data. If you're question is about what data to register contact the project group at Danish National Health Data Agency.

**Comment by RasmusThernoe** [comment]
OK. Closing the issue and question directed to the Danish National Health Data Agency.
