### ISSUE TITLE
mandatory address fields

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#24]
This is related to issue 20 (which is now closed, so I didn't seem able to leave a comment about it.)

The DK CDA Header specifies that the various elements within the addr element are "required", but it shouldn't mean they are "mandatory" (which are different concepts in CDA since a "required" element can have a nullFlavor, but a "mandatory" element is not allowed to have a nullFlavor.) So the following CDA constraints:

CONF-DK: 10
SHALL contain at least one and not more than 4 streetAddressLine.
CONF-DK: 11
SHALL contain exactly one [1..1] postalcode.
CONF-DK: 12
SHALL contain exactly one [1..1] city.

allow the following snippet of a document to pass validation
```
            <addr>
                <streetAddressLine nullFlavor="UNK"/>
                <postalCode nullFlavor="UNK"/>
                <city nullFlavor="UNK"/>
                <country>DKTranslated</country>
            </addr>
```

The following should fail since the conformance statement states that there SHALL be exactly 1 postalCode:

```
            <addr>
                <streetAddressLine nullFlavor="UNK"/>
                <city nullFlavor="UNK"/>
                <country>DKTranslated</country>
            </addr>
```

Note that this definition of the term SHALL is explicitly stated at the top of the DK CDA Header document in section 1.3.1:
"The keyword SHALL allow the use of nullFlavor unless the requirement is on an attribute or the use of nullFlavor is explicitly precluded. Legal values according to this specification come from the HL7 NullFlavor vocabulary."

So in order to make an item mandatory in an implementation guide you must use a SHALL and then SHALL NOT allow nullFlavor constraints on the element or make one of it's attributes required. This is only done a few times in the DK CDA Header document (for some id and time elements and the confidentialityCode, languageCode, and the administrativeGenderCode element.) Other elements should allow nullFlavors.

**Comment by cjonigkeit-csc** [comment]
We will fix this immediately.
Thank you for bringing this issue to our attention.

**Comment by cjonigkeit-csc** [comment]
Hi @DaveSS we have corrected [the MedCom template in our staging environment](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--medcom-?section=templates&id=1.2.208.184.2.10.7&effectiveDate=2016-10-24T00:00:00). Please have a look at it.
We will release this together with fixes to other templates in [Release 1.4](https://github.com/scandihealth/lpr3-docs/milestone/5).

**Comment by DaveSS** [comment]
Thank you, I didn't notice that constraint on the nullFlavors. We will make sure to use either NI or NA for nullFlavors if necessary (and to specifically only use NI for the address element.).

One further question about the DK Address Body, I am not familiar with how Art-Decor creates schematrons, but I would expect a constraint like "SHOULD contain zero or one [0..1] country." to have a cardinality of 0...1 but not to have a conformance column listed as "R". These seem contradictory, since Required in CDA means the element must be present in the CDA document but it might just by my lack of understanding of the Art-Décor tool. Does the schematron generated allow the country element to be missing as would be allowed by the 0...1 cardinality, or does it require it to be present like the R conformance statement indicates (most of the US-Realm IGs have a column for the conformance verb SHALL, SHOULD, or MAY but don't usually include the conformance column in tables so I am not as familiar with how the R or M in this column affects the schematrons created.) Also, is it possible to use O or R2 to indicate if the an element is truly optional (like the useablePeriod of the addr), or does the value need to be R or M? It would help with readability if it doesn't adversely affect the schematrons.

**Comment by cjonigkeit-csc** [comment]
Art Decor is using the [IHE Data Optionality Constraints](https://www.ihe.net/uploadedFiles/Documents/Templates/IHE_TF_GenIntro_AppE_Profiling_Rev1.0_2014-07-01.pdf). See section E.4.2.2 onwards.
