### ISSUE TITLE
Is it possible to reopen an Episode of Care?

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#241]
In the LPR3 Reporting Guide (DA: Indberetningsvejledningen) it states:

- Page 42:  "Tidligere afsluttede forløbselementer kan ikke genåbnes"

- Page 42: "Når et forløb(selement) er lukket, er det fordi, afdelingen har afsluttet forløbsansvaret ud fra en klinisk beslutning. Det må derfor ikke genåbnes med tilbagevirkende kraft..."

- Page 46: "Det afsluttede og indberettede forløbselement kan ikke genåbnes."

Using the LPR3 service an episode of care can be reported in version 1 with an end date time.

Using the LPR3 service the same episode of care can be reported in version 2 without an end date time - no technical or business error is returned.

Is it the reporting guide or the service which is correct?

**Comment by smunck** [comment]
The LPR3 Reporting guide must be followed, even though it might be technically possible to do something else. 

If an eoc has ended, and the patient later returns, a new eoc must be created. If the first eoc is reopened, it will be reported that the hospital has had responsibility for the patient for the whole period which is not true. 

Even though an eoc must not be reopened, it should be technically possible to correct errors in data. If a user has registered a wrong end date, it should be possible to correct the date and report the eoc again with correct data. So it is technically possible to report a eoc with a new enddate (or no end date if that is the correct value).

**Comment by RasmusThernoe** [comment]
Thank you for the clarification.
