### ISSUE TITLE
Notice: All previous versions of data to be purged with next release

### ISSUE THREAD

**Issue by TueCN** [scandihealth/lpr3-docs#242]
Due to changes in the internal data layer with the major release scheduled for today, it is necessary to purge all **history** on data in the TEST environment on https://lprws-test.sds.dsdn.dk. 
This means that the current version of all data (EoCs, Encounters, Patients, Diagnoses, etc) will be the only version in the system after the deploy today.

Server is scheduled to be taken offline at: TBA

**Comment by SorenTL** [comment]
Is it by any means possible to postpone this to 15.00 CET as we are conducting a customer test one the environment now. This is a very short notice for such a change.

**Comment by maagaard-DXC** [comment]
SDS have sent the change to review with Regional project managers.
Please be advised that the upgrade of environment scheduled for 13.00 will go ahead regardless of whether or not the history will be purged.

**Comment by maagaard-DXC** [comment]
In agreement with SDS upgrade have been postponed to tomorrow morning.

**Comment by maagaard-DXC** [comment]
History will be purged after accept from all Regional Project Managers.
