### ISSUE TITLE
Invalid representedOrganization

### ISSUE THREAD

**Issue by ScaAnders** [scandihealth/lpr3-docs#244]
I have a CDA document with the following author section:
`  <author typeCode="AUT" contextControlCode="OP">
    <templateId root="1.2.208.176.7.1.10.102" />
    <templateId root="2.16.840.1.113883.10.12.102" />
    <time value="20181115010000+0100" />
    <assignedAuthor nullFlavor="NI" classCode="ASSIGNED">
      <representedOrganization classCode="ORG" determinerCode="INSTANCE">
        <id root="1.2.208.176.1.1" extension="634491000016008" assigningAuthorityName="SOR" />
      </representedOrganization>
    </assignedAuthor>
  </author>`
I then get the exception you see below, telling me that I am missing an 'id' element inside the representedOrganization. Can you tell me how I must change the CDA?
LPR3 response:
`<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><soap:Header><Action xmlns="http://www.w3.org/2005/08/addressing">urn:ihe:iti:2007:ProvideAndRegisterDocumentSet-bResponse</Action><MessageID xmlns="http://www.w3.org/2005/08/addressing">urn:uuid:43ce0cea-fc71-42d3-9eca-beb767da005a</MessageID><To xmlns="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/anonymous</To><RelatesTo xmlns="http://www.w3.org/2005/08/addressing">urn:uuid:d63aece6-c760-4295-9e86-595c6a49428f</RelatesTo><ns10:Header xmlns:ns10="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd" xmlns:ns11="http://www.nsi.dk/hsuid/2016/08/hsuid-1.1.xsd" xmlns:ns12="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns13="urn:lpr" xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns4="urn:ihe:iti:xds-b:2007" xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns6="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:ns7="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns8="http://www.w3.org/2000/09/xmldsig#" xmlns:ns9="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><ns10:SecurityLevel>3</ns10:SecurityLevel><ns10:TimeOut>1440</ns10:TimeOut><ns10:Linking><ns10:FlowID>0bef5b89-e7a8-420c-867b-8ef2d52094ca</ns10:FlowID><ns10:MessageID>460f5a2c-7110-4a7b-95c6-6f595e6211e4</ns10:MessageID></ns10:Linking><ns10:FlowStatus>flow_finalized_succesfully</ns10:FlowStatus><ns10:Priority>RUTINE</ns10:Priority><ns10:RequireNonRepudiationReceipt>yes</ns10:RequireNonRepudiationReceipt></ns10:Header></soap:Header><soap:Body><ns2:RegistryResponse xmlns:ns10="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd" xmlns:ns11="http://www.nsi.dk/hsuid/2016/08/hsuid-1.1.xsd" xmlns:ns12="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns13="urn:lpr" xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns4="urn:ihe:iti:xds-b:2007" xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns6="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:ns7="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns8="http://www.w3.org/2000/09/xmldsig#" xmlns:ns9="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure"><ns2:RegistryErrorList highestSeverity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"><ns2:RegistryError codeContext="XSD|||cvc-complex-type.2.4.a: Invalid content was found starting with element 'representedOrganization'. One of '{&quot;urn:hl7-org:v3&quot;:realmCode, &quot;urn:hl7-org:v3&quot;:typeId, &quot;urn:hl7-org:v3&quot;:templateId, &quot;urn:hl7-org:v3&quot;:id}' is expected." errorCode="InvalidDocumentContent" location="7abb8caf-f33b-5ccf-a3ef-e8aba41096a4^null|||26:74" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"></ns2:RegistryError></ns2:RegistryErrorList></ns2:RegistryResponse></soap:Body></soap:Envelope>
`

**Comment by TueCN** [comment]
Your XML does not validate up against the CDA XML schema.

The validation error message specifies what is expected: 
> One of '{urn:hl7-org:v3:realmCode, urn:hl7-org:v3:typeId, urn:hl7-org:v3:templateId, urn:hl7-org:v3:id}' is expected.

You can place e.g. a `<id nullFlavor="NI"/>` as the first child of `<assignedAuthor>`
```xml
        <assignedAuthor nullFlavor="NI" classCode="ASSIGNED">
            <id nullFlavor="NI"/>
            <representedOrganization classCode="ORG" determinerCode="INSTANCE">
                <id root="1.2.208.176.1.1" extension="634491000016008" assigningAuthorityName="SOR"/>
            </representedOrganization>
        </assignedAuthor>

```

You can download the CDA XML schema from https://gazelle.ihe.net/XSD/HL7/CDA/

**Comment by ScaAnders** [comment]
Thanks!
