### ISSUE TITLE
Milestones and new deploys

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#245]
According to https://scandihealth.github.io/lpr3-docs/testenvironment/index.html:

> To increase velocity and success DXC will continuously deliver new versions of the LPR3 solution. Time of deployment will be communicated by SDS project management and communication through **milestones**. 

According to https://github.com/scandihealth/lpr3-docs/milestones there are no future deploys - except from the one today.

Is the deploy today going to be the last deploy on the test environment before LPR3 goes into production?

**Comment by TueCN** [comment]
No, we have future deploys planned.
We usually do not create the next milestone before the previous one is closed.

The currently open (past due date) milestone is currently awaiting approval by SDS, as it includes the wiping of all history data. 
See #242.

**Comment by RasmusThernoe** [comment]
What is the notice period between the milestone is created on GitHub until the deploy is performed?

**Comment by maagaard-DXC** [comment]
Usually about a week but it differs depending on the current needs. 
Normal process is that then one Milestone is closed the next is created.
