### ISSUE TITLE
CDA id-extension

### ISSUE THREAD

**Issue by ScaAnders** [scandihealth/lpr3-docs#247]
![cda id extension](https://user-images.githubusercontent.com/41738261/49276062-90122e00-f47d-11e8-9d5a-baed9843dd6f.png)
Do you have a description about what the content of the 'extension' attribute of the CDA 'id' element should be? Please attached screenshot from the doc.

**Comment by TueCN** [comment]
Hi,

Can you link to the template you are showing in the screenshot? 
You can get links in art-decor by clicking the paperclip icon in the title bar of the open template.

**Comment by ScaAnders** [comment]
http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.71&effectiveDate=2018-01-04T00:00:00

**Comment by TueCN** [comment]
This is the identifier of the ClinicalDocument element. The content should be a UUID, as specified by the datatype (DT column). 

You can generate the UUID on the fly, but if you plan to append or replace the document later, you must store it so you can refer to it in the [relatedDocument](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.111&effectiveDate=2018-01-04T00:00:00)/parentDocument/id/@extension of the appending/replacing document

See https://scandihealth.github.io/lpr3-docs/aspects/index.html#documents-and-versioning

**Comment by ScaAnders** [comment]
Thanks!
