### ISSUE TITLE
Mapping from LPR3 to CDA Observation Organizer

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#25]
I have a couple questions about the Observation Organizer section and how it maps to the LPR3 Results Report.

1.  I want to verify where certain information is reported in the CDA Document. In section 13.4 of the VEJLEDNING TIL INDBERETNING TIL LANDSPATIENTREGISTERET (LPR3) document there is a table that specifies the following:
- There is a "trigId" for the injury report (which indicates the contact reason). I don't find a place in the actual Observation Organizer section for this data. Is this data actually represented as the contact reason in the Kontakt section of the CDA document that the Observation Organizer references?
- There is a datetime at the Report level in addition to a datetime at the level of individual results within this report. The CDA Document only has datetime elements at the level of the individual results (observations), and not at the report level (organizer) level. Is this data missing from the CDA or is it just being pulled from a different referenced section or just one of the individual observations? 

2.  In section 10.4.1 of the same document, there is a table defining the Result Report to the Cancer Registry, and in that table there are a couple of Result Types that have a cardinality that allow there to be more than one occurrence of that result type (the macroscopic and microscopic basis for a diagnosis). I think the whole report (organizer) contains individual results (observations) and each of those observations can contain a single code (result type) and a single value. If we have a case like the macroscopic basis for a diagnosis where a single result type might have multiple values, should we represent that with multiple observations, each with the same code but different value?

I apologize if my translations from the LPR3 specification document to English are not accurate. Please let me know if I can clarify any of the above.

**Comment by cjonigkeit-csc** [comment]
> There is a "trigId" for the injury report (which indicates the contact reason). I don't find a place in the actual Observation Organizer section for this data. Is this data actually represented as the contact reason in the Kontakt section of the CDA document that the Observation Organizer references?

Yes.

> There is a datetime at the Report level in addition to a datetime at the level of individual results within this report. The CDA Document only has datetime elements at the level of the individual results (observations), and not at the report level (organizer) level. Is this data missing from the CDA or is it just being pulled from a different referenced section or just one of the individual observations?

That is a bug on our behalf. See #29

>In section 10.4.1 of the same document, there is a table defining the Result Report to the Cancer Registry, and in that table there are a couple of Result Types that have a cardinality that allow there to be more than one occurrence of that result type (the macroscopic and microscopic basis for a diagnosis). I think the whole report (organizer) contains individual results (observations) and each of those observations can contain a single code (result type) and a single value. If we have a case like the macroscopic basis for a diagnosis where a single result type might have multiple values, should we represent that with multiple observations, each with the same code but different value?

Yes, multiple observations, each with the same code but different value.

**Comment by DaveSS** [comment]
I am referring to the table describing Injury Reporting in section 13.4. There appears to be a time element in the gray section referring to the Report, and then a separate time element in the Result section of the table. I included a snippet of the table that I am referring to below:
![injury report](https://user-images.githubusercontent.com/7239040/35445530-d04edef8-02a9-11e8-871e-a545f9fc290e.png)

**Comment by cjonigkeit-csc** [comment]
The indberetningstidspunkt is taken from `/ClinicalDocument/effectiveTime/@value`.
