### ISSUE TITLE
Can't login to LPR3 administration module

### ISSUE THREAD

**Issue by joelmetodika** [scandihealth/lpr3-docs#254]
Hi, I get the following error message when trying to login to the LPR3 administration module:
"DXC Traffic Manager: the service is temporarily unavailable (503). Please try again later."
We are in the middle of doing "tilslutningstest" related things and really need to know when this will be available again.

Regards Joel
Metodika AB
![screen shot 2018-12-11 at 15 37 06](https://user-images.githubusercontent.com/45793526/49807825-5b468680-fd5b-11e8-8696-0ab924cb51ce.png)

**Comment by maagaard-DXC** [comment]
We are currently deploying this weeks scheduled service pack so that is why you are getting this error.
Service will be available again tomorrow.

**Comment by joelmetodika** [comment]
Ok, where is this schedule available for viewing? At what time tomorrow will it be up and running?

**Comment by maagaard-DXC** [comment]
Environment will be up and running first thing.
Schedule can be seen in Milestones here:
https://github.com/scandihealth/lpr3-docs/milestones

**Comment by joelmetodika** [comment]
Ok, thanks for the information and quick responses!

Regards Joel

**Comment by joelmetodika** [comment]
I could login to the admin module this morning but now it's not possible again. I get a "com.google.gwt.user.client.rpc.StatusCodeException". Are you doing more maintenance work?

**Comment by TueCN** [comment]
The test service is currently experiencing problems. We are working on restoring normal behavior.

However, also note that there is a known issue regarding stale browser caches when new builds are deployed.

Wait for the service to come back online and also please clear your browser cache as described on https://github.com/scandihealth/lpr3-docs/issues/219#issuecomment-438594500

**Comment by joelmetodika** [comment]
Now it works. Thanks!
