### ISSUE TITLE
CUSTODIAN_NOT_FOUND

### ISSUE THREAD

**Issue by Smp-xmedicus** [scandihealth/lpr3-docs#256]
[Clinical_document.txt](https://github.com/scandihealth/lpr3-docs/files/2671075/Clinical_document.txt)
[Full_message.txt](https://github.com/scandihealth/lpr3-docs/files/2671077/Full_message.txt)

Why do this combination get rejected, maybe a missing link between SOR=293161000016004 and CVR=27506909?

`	<author typeCode="AUT">
		<templateId root="1.2.208.176.7.1.10.102" />
		<templateId root="2.16.840.1.113883.10.12.102" />
		<time value="20181212090004+0100" />
		<assignedAuthor classCode="ASSIGNED">
			<id nullFlavor="NI" />
			<representedOrganization classCode="ORG" determinerCode="INSTANCE">
				<id root="1.2.208.176.1.1" extension="293161000016004" assigningAuthorityName="SOR" />
			</representedOrganization>
		</assignedAuthor>
	</author>
	<custodian typeCode="CST">
		<templateId root="1.2.208.176.7.1.10.103" />
		<templateId root="2.16.840.1.113883.10.12.104" />
		<assignedCustodian classCode="ASSIGNED">
			<representedCustodianOrganization classCode="ORG" determinerCode="INSTANCE">
				<id root="2.16.840.1.113883.2.24.1.1" extension="27506909" assigningAuthorityName="Erhvervs- og Selskabsstyrelsen" />
			</representedCustodianOrganization>
		</assignedCustodian>
	</custodian>`

With rejection:
`  <s:Body>
    <ns2:RegistryResponse xmlns:ns10="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd" xmlns:ns11="http://www.nsi.dk/hsuid/2016/08/hsuid-1.1.xsd" xmlns:ns12="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns13="urn:lpr" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns4="urn:ihe:iti:xds-b:2007" xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns6="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:ns7="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns8="http://www.w3.org/2000/09/xmldsig#" xmlns:ns9="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure" xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0">
      <ns2:RegistryErrorList highestSeverity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error">
        <ns2:RegistryError codeContext="INTEGRITY_CHECK|||Author/custodian is not matching registered relation|||CUSTODIAN_NOT_FOUND" errorCode="InvalidDocumentContent" location="unknown document id|||/*[local-name()='ClinicalDocument']/*[local-name()='custodian']/*[local-name()='assignedCustodian']/*[local-name()='representedCustodianOrganization']/*[local-name()='id']/@extension" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"></ns2:RegistryError>
      </ns2:RegistryErrorList>
    </ns2:RegistryResponse>
  </s:Body>
`

**Comment by TueCN** [comment]
Correct, a service user has not been registered with SOR=293161000016004 and CVR=27506909. 
Please contact SDS to get this combination registered as a "dataproducent".
