### ISSUE TITLE
Nullify sections of CDA Document

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#26]
I wanted to validate that when using the RPLC method for updating documents, the new document replaces the previous submitted document with the full current state of all resources in the previous version of the document including additional allowed resources for that document. And that by not including a resource that was present in a previous version of a document will be the method of deleting that resource. I want to verify that the Nullify section does not need to be explicitly used in the case of RPLC.

**Comment by cjonigkeit-csc** [comment]
I have spliced the issue into two, see #23.

**Comment by cjonigkeit-csc** [comment]
Answering your question. A RPLC method replaces everything that has previously been submitted to a set with the new information contained in the replacing document, e.g. start from scratch.
