### ISSUE TITLE
Transaction rolled back

### ISSUE THREAD

**Issue by Smp-xmedicus** [scandihealth/lpr3-docs#260]
We get an error "Transaction rolled back" when sending a normal request.
Attached is full document, clinical document and error response.  

[RollBack.zip](https://github.com/scandihealth/lpr3-docs/files/2686823/RollBack.zip)

**Comment by TueCN** [comment]
I have reproduced the error, and it is a bug

**Comment by TueCN** [comment]
The error occurs because you are trying to create 2 condition observations with the same extension 
`CC96A17B-FE64-544F-BC38-EB2F9D90AEF6`. 
One 'aktionsdiagnose' and one 'bidiagnose'.

We will look into returning a better error message in the future.
