### ISSUE TITLE
Validation issues with MYNDIGHEDSKODE

### ISSUE THREAD

**Issue by Marc-Petersen** [scandihealth/lpr3-docs#261]
When I submit a CDA with county code of '992'
![image](https://user-images.githubusercontent.com/44767916/50152502-11622100-02c4-11e9-81b5-3a1dd885d183.png)
The following response contains an additional '0':
<ep6:RegistryError codeContext="INTEGRITY_CHECK|||Myndighedskode 0992 not found in the registry|||MYNDIGHED_CODE_NOT_FOUND|||**0992**" errorCode="InvalidDocumentContent" location="2CBE8300-F18D-11E8-BEEF-A1058FF62DB0^05C241D2-FFDF-11E8-9FAB-A1058FF62DB0|||//*[@*='0992']" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"></ep6:RegistryError>
why?
Also.
When I submit a county code of '185' - no errors are logged in the response message. This code is NOT in any indberetningsvejledninger, I have seen. This is for a testpatient from DK with ECPR.
![image](https://user-images.githubusercontent.com/44767916/50152904-36a35f00-02c5-11e9-916d-68a2102b4853.png).
I would expect this message to fail.

**Comment by TueCN** [comment]
I am fairly confident 0992 is not a valid county code while 0185 is. 
See rule 01.A in [Logisk datamodel og indberetningsregler - Bilag 1 (PDF)](https://sundhedsdatastyrelsen.dk/-/media/sds/filer/rammer-og-retningslinjer/patientregistrering/indberetning-til-lpr3/vejledning-lpr3-bilag-1-model-og-indberetningsregler.pdf?la=da)

> -> kommunekode | MynKod {0009; 0101-0860; 0956-0961} | gyldig kommunekode iht. Myndighedsregisteret

See https://github.com/scandihealth/lpr3-docs/issues/231 and https://github.com/scandihealth/lpr3-docs/issues/103

**Comment by Marc-Petersen** [comment]
Yes. But I'm not sending four digits. Only three - 992 and 185.
Are you automatically prepending a zero?

**Comment by Marc-Petersen** [comment]
Also: Are you validating on county-code in all messages or only some? I.E messages for patients with certain CPR status, country of residency etc.?

**Comment by TueCN** [comment]
1. Yes, country code 0992 is equivalent to 992.
2. All country codes are always validated.

**Comment by Marc-Petersen** [comment]
You mean county, country or both?

**Comment by TueCN** [comment]
Sorry meant county, but it is the same for both :)

**Comment by Marc-Petersen** [comment]
Thanks. What about foreign patients.? Ex. from Sweden? Do we report their county as unknown or not at all?

**Comment by TueCN** [comment]
That is a non-technical question I cannot answer. Please contact SDS directly. 
See [CONTRIBUTING.md#questions](https://github.com/scandihealth/lpr3-docs/blob/master/CONTRIBUTING.md#questions)

**Comment by smunck** [comment]
SDS has answered this question to H/SJ: Der skal kun indberettes kommunekoder for patienter med bopæl i Danmark eller Grønland. Dvs. der må kun anvendes danske eller grønlandske kommunekoder.

**Comment by Marc-Petersen** [comment]
Closing
