### ISSUE TITLE
LPR3 error: Procedure could not be found for nullify [5864]

### ISSUE THREAD

**Issue by clausheinecke** [scandihealth/lpr3-docs#266]
We get this error when we delete a Kontakt with the Kontakttype "Fysisk fremmøde" and that Kontakt has a procedure attached.
![billede](https://user-images.githubusercontent.com/45626571/50680865-93af4c80-1009-11e9-83c0-51fdb2936c02.png)

The error message states that the procedure does not exists in LPR - but it does.
![billede](https://user-images.githubusercontent.com/45626571/50682294-ad06c780-100e-11e9-9457-a7a2a50696a8.png)

We want to keep the procedure in LPR.
Can you help us understand what the issue is?
We believe that we have created the CDA according to the specs.

**Comment by TueCN** [comment]
@clausheinecke could you please attach
1) The XML that creates the existing Kontakt+Procedure (press the "Hent råfil" button in the UI)
2) The input XML that gives the error you want help to understand

> We want to keep the procedure in LPR.

What do you mean by this? If you delete a Kontakt, all data under the Kontakt is also deleted.

**Comment by clausheinecke** [comment]
This is our CDA that should delete the Kontakt and as I understand it also tries to resubmit the procedurecode, so we can keep the code in LPR (now linked to the Forløbselement).
[Deletion CDA.txt](https://github.com/scandihealth/lpr3-docs/files/2726673/Deletion.CDA.txt)

And this is the latest accepted CDA:
[Latest CDA.txt](https://github.com/scandihealth/lpr3-docs/files/2726676/Latest.CDA.txt)

**Comment by clausheinecke** [comment]
Here is another example of (almost) the same issue. This time it is the diagnosis we can't "nullify":
<ClinicalDocument xmlns="urn:hl7-org:v3" classCode="DOCCLIN" moodCode="EVN">
	<realmCode code="DK"></realmCode>
	<typeId extension="POCD_HD000040" root="2.16.840.1.113883.1.3"></typeId>
	<templateId root="1.2.208.176.7.1.10.71"></templateId>
	<templateId root="2.16.840.1.113883.10.12.2"></templateId>
	<templateId root="2.16.840.1.113883.10.12.1"></templateId>
	<id extension="CCED650E-1801-11E9-82CB-A1058FF62DB0" root="7DE75B7A-B340-11E8-B441-A1058FF62DB0"></id>
	<code code="34133-9" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Summary of episode note"></code>
	<effectiveTime value="20190114143922+0100"></effectiveTime>
	<confidentialityCode code="N" codeSystem="2.16.840.1.113883.5.25"></confidentialityCode>
	<setId assigningAuthorityName="EPC" root="7DE75B7A-B340-11E8-B441-A1058FF62DB0"></setId>
	<versionNumber value="120"></versionNumber>
	<recordTarget>
		<templateId root="1.2.208.176.7.1.10.101"></templateId>
		<templateId root="2.16.840.1.113883.10.12.101"></templateId>
		<patientRole classCode="PAT">
			<templateId root="1.2.208.176.7.1.10.106"></templateId>
			<templateId root="1.2.208.176.7.1.10.107"></templateId>
			<id extension="2701909994" root="1.2.208.176.1.2" assigningAuthorityName="CPR"></id>
			<id extension="2701900XX6" root="1.2.840.114350.1.13.416.3.7.5.737384.1001"></id>
			<addr>
				<streetAddressLine>Hjorth Nielsens Vej 94</streetAddressLine>
				<postalCode>1113</postalCode>
				<city>Lyngby</city>
				<county>167</county>
				<country>5100</country>
				<useablePeriod xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="IVL_TS">
					<low value="20190111000000+0000"></low>
				</useablePeriod>
			</addr>
			<patient classCode="PSN">
				<name>
					<family>Lpr</family>
					<given>Pas</given>
					<given>Fok</given>
					<given>J</given>
				</name>
				<administrativeGenderCode code="F" codeSystem="2.16.840.1.113883.5.1"></administrativeGenderCode>
				<birthTime value="19900127000000+0000"></birthTime>
			</patient>
		</patientRole>
	</recordTarget>
	<author typeCode="AUT">
		<templateId root="1.2.208.176.7.1.10.102"></templateId>
		<templateId root="2.16.840.1.113883.10.12.102"></templateId>
		<time value="20190114143922+0100"></time>
		<assignedAuthor classCode="ASSIGNED">
			<id nullFlavor="NI"></id>
			<representedOrganization classCode="ORG" determinerCode="INSTANCE">
				<id extension="6111000016004" root="1.2.208.176.1.1" assigningAuthorityName="SOR"></id>
			</representedOrganization>
		</assignedAuthor>
	</author>
	<custodian typeCode="CST">
		<templateId root="1.2.208.176.7.1.10.103"></templateId>
		<templateId root="2.16.840.1.113883.10.12.104"></templateId>
		<assignedCustodian classCode="ASSIGNED">
			<representedCustodianOrganization classCode="ORG" determinerCode="INSTANCE">
				<id extension="29190623" root="2.16.840.1.113883.2.24.1.1" assigningAuthorityName="Erhvervs- og Selskabsstyrelsen"></id>
			</representedCustodianOrganization>
		</assignedCustodian>
	</custodian>
	<relatedDocument typeCode="APND">
		<parentDocument classCode="DOCCLIN" moodCode="EVN">
			<id extension="BAFE979C-1800-11E9-AECC-A1058FF62DB0" root="7DE75B7A-B340-11E8-B441-A1058FF62DB0"></id>
			<setId assigningAuthorityName="EPC" root="7DE75B7A-B340-11E8-B441-A1058FF62DB0"></setId>
			<versionNumber value="119"></versionNumber>
		</parentDocument>
	</relatedDocument>
	<component contextConductionInd="true">
		<structuredBody>
			<component contextConductionInd="true">
				<section>
					<templateId root="1.2.208.176.7.1.10.116"></templateId>
					<templateId root="2.16.840.1.113883.10.12.201"></templateId>
					<entry typeCode="COMP">
						<act classCode="ACT" moodCode="EVN">
							<templateId root="1.2.208.176.7.1.10.118"></templateId>
							<templateId root="2.16.840.1.113883.10.12.301"></templateId>
							<code nullFlavor="NA"></code>
							<statusCode code="nullified"></statusCode>
							<reference typeCode="RPLC">
								<templateId root="1.2.208.176.7.1.10.117"></templateId>
								<templateId root="2.16.840.1.113883.10.12.324"></templateId>
								<externalAct classCode="ACT" moodCode="EVN">
									<templateId root="1.2.208.176.7.1.10.78"></templateId>
									<templateId root="2.16.840.1.113883.10.12.325"></templateId>
									<id extension="A9A33CBD-CF32-5437-86CE-98A3E8481C83" root="7DE75B7A-B340-11E8-B441-A1058FF62DB0"></id>
								</externalAct>
							</reference>
						</act>
					</entry>
					<entry typeCode="COMP">
						<act classCode="ACT" moodCode="EVN">
							<templateId root="1.2.208.176.7.1.10.118"></templateId>
							<templateId root="2.16.840.1.113883.10.12.301"></templateId>
							<code nullFlavor="NA"></code>
							<statusCode code="nullified"></statusCode>
							<reference typeCode="RPLC">
								<templateId root="1.2.208.176.7.1.10.117"></templateId>
								<templateId root="2.16.840.1.113883.10.12.324"></templateId>
								<externalObservation classCode="OBS" moodCode="EVN">
									<templateId root="1.2.208.176.7.1.10.100"></templateId>
									<templateId root="2.16.840.1.113883.10.12.326"></templateId>
									<id extension="441DE6F7-4EB9-5301-BD9C-DC8C15B30E8F" root="7DE75B7A-B340-11E8-B441-A1058FF62DB0"></id>
								</externalObservation>
							</reference>
						</act>
					</entry>
				</section>
			</component>
		</structuredBody>
	</component>
</ClinicalDocument>

**Comment by clausheinecke** [comment]
Here is the latest example of almost the same issue. This time it's a diagnosis we can't nullify when we change a Kontakt from "Fysisk fremmøde" to an "internal kontakt" which we don't report.
[Nullify diagnosis.txt](https://github.com/scandihealth/lpr3-docs/files/2755363/Nullify.diagnosis.txt)

**Comment by TueCN** [comment]
@clausheinecke yes when we delete a Kontakt, all data referencing the encounter directly is also deleted.
See https://scandihealth.github.io/lpr3-docs/aspects/index.html#id-usage-and-referencing-in-lpr3
> Act, Procedure and Observation references the Encounter/Episode of Care, which means that e.g. nullifying the Encounter also nullifies all entities that points toward the Encounter (elements "under" the encounter). 

>Nullifying only the Act/Procedure/Observation that points towards the encounter removes only the entity itself and the encounter is left unchanged. 

>The same goes for nullifying an Episode of Care which removes all Encounters and transitively all activities below it.

**Comment by TueCN** [comment]
@clausheinecke  your latest example only contains the nullification. 
I need all the related documents so I can reproduce the error on our internal test environment.

```xml
<relatedDocument typeCode="APND">
    <parentDocument classCode="DOCCLIN" moodCode="EVN">
        <id extension="BAFE979C-1800-11E9-AECC-A1058FF62DB0" root="7DE75B7A-B340-11E8-B441-A1058FF62DB0"></id>
        <setId assigningAuthorityName="EPC" root="7DE75B7A-B340-11E8-B441-A1058FF62DB0"></setId>
        <versionNumber value="119"></versionNumber>
    </parentDocument>
</relatedDocument>
```

I need the XML for all the related documents in the set, before I can be certain I am reproducing the issue the same you you are.

So I need doucment `BAFE979C-1800-11E9-AECC-A1058FF62DB0`, and its related documents (if any).

**Comment by TueCN** [comment]
@clausheinecke the XML you attached is not the full set so I cannot submit the XML documents to our internal test ennvironment (the attachhed "OK.data.txt" has a related document).

However, I started analyzing your XML and as you mentioned, I can see you try to nullify both a Kontakt and a Diagnose that belongs to that Kontakt.

As I mentioned previously, when you delete an encounter, everything directly referencing that encounter is also deleted. 

I believe that LPR processesses nullification acts in the order they are listed in the input XML and your XML lists the Kontakt nullification act before the Diagnose nullification act.
So because the Kontakt nullification is processed before the Diagnose nullification, the Diagnose has already been deleted when processing the Diagnose nullification, and therefore you get your "DIAGNOSIS COULD NOT BE FOUND FOR NULLIFY" error message 
(which is your system's interpretation of LPR's response: EXTERNAL_CONDITION_OBSERVATION_NOT_FOUND)

The general solution would be to always only include the "root" element of what you want to delete (only the Kontakt and nothing "under" the Kontakt). The same would go for any other roots, e.g. when deleting a Diagnose all the ResultatIndberetning elements referencing that Diagnose are also automatically deleted and must not be also included in the nullify message.

Hope that clears up the problem :)

**Comment by clausheinecke** [comment]
Thx, Tue. Your last post was helpful.
Can you verify that our interpretation (see below) of your design is correct?

Epic writes:
The feedback we got from DXC helps a lot, thanks!  Knowing that DXC is filing data to their database element-by-element as they read the XML message (and not after processing the full document) I see where this error comes from.

I find it's easier to think about this issue with a visual example:
Inline image

Lets say we have a pathway element with two kontakts (kontakts A and B), and both kontakt has one procedure (procedures 1 and 2).  If a user in Epic deletes Kontakt A and procedure 1, Epic will communicate this change to DXC with a new CDA message that documents both changes. 

Let's say that the XML element nullifying Kontakt A appears higher up in the document than the XML element nullifying procedure 1.  Reading post #9, I believe DXC reads the nullification of kontakt A and immediately deleted that kontakt (and all linked objects).  As a result, their database would appear as follows:
Inline image

Later in that same CDA message, DXC reads the nullification of procedure 1.  DXC checks their database, but no longer sees procedure 1, and throws the error we're seeing here.  Obviously this is a very simplified example, so extrapolating further I would imagine that we could also see this issue in similar cases, such as:
•A Pathway Element is nullified prior to a procedure that points to that pathway element
•A kontakt is nullified prior to a diagnosis or result report that points to that kontakt
•A procedure is nullified before a result report that points to that procedure

**Comment by clausheinecke** [comment]
Ups- images were pasted in.
Image 1:
![billede](https://user-images.githubusercontent.com/45626571/51660422-fa42dd00-1fad-11e9-8e0b-edbf9d5a042e.png)
Image 2:
![billede](https://user-images.githubusercontent.com/45626571/51660434-09298f80-1fae-11e9-9aa1-fa84d4276fa8.png)

**Comment by clausheinecke** [comment]
Are we the ones getting this error?

**Comment by TueCN** [comment]
@clausheinecke yes, your interpretation describes the LPR functionality as it exists today

**Comment by clausheinecke** [comment]
And do other regions get the same error as we do? Or don't they have the same issue as we do?

**Comment by TueCN** [comment]
Seemingly not. 
We have not heard of anyone else that has had the same issue.
