### ISSUE TITLE
Acc. errorlist is not generated 

### ISSUE THREAD

**Issue by kbhCGI** [scandihealth/lpr3-docs#267]
Hi

There is no errorlist for RN, is the job not running?

**Comment by TueCN** [comment]
**RESOLUTION**
There was a problem with the transfer of accumulated error list files, which has now been rectified.
Expect the error list files to be available on the FTP server within 1 hour.

**Comment by kbhCGI** [comment]
Errorlist received.

**Comment by kbhCGI** [comment]
Hi
There is no errorlist for RN, is the job not running?
