### ISSUE TITLE
LPR3 Administration Client not available

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#268]
No administration client available:

![image](https://user-images.githubusercontent.com/36242392/50772759-21e83480-128f-11e9-9898-584d81e4861b.png)

**Comment by TueCN** [comment]
Verified. We are working on resolving the issue.

**Comment by TueCN** [comment]
**RESOLUTION**
Rectified a configuration error that happened sometime between last deployment and now.

The environment should be up and running again.

**Comment by MichaelEsmannSSE** [comment]
@TueCN On https://github.com/scandihealth/lpr3-docs/milestones it says that there will be a new release tomorrow, 8. january. Can you confirm that, and  is there an estimate for the downtime?

**Comment by TueCN** [comment]
Yes, [milestone/32](https://github.com/scandihealth/lpr3-docs/milestone/32) is a regular, scheduled, "Tuesday hotfix" with downtime starting from around 15:00 CET. 

The milestone description will be updated when the scope is 100% locked.

**Comment by RasmusThernoe** [comment]
Working again - issue closed.
