### ISSUE TITLE
Problem logging in to LPR3 Administration Client

### ISSUE THREAD

**Issue by MichaelEsmannSSE** [scandihealth/lpr3-docs#269]
I get this error after I have given my password to "digital signatur":

 SST.UserManagementClaimsTransformations.AddAdRoleClaimsTransform, SST.UserManagementClaimsTransformations fejl i forhold til at transformere. Transformationspipelinen blev stoppet.

**Comment by TueCN** [comment]
Yes, I get the same error. I believe it is an issue in SEB, not in LPR

**Comment by stinnekn** [comment]
It seems to only be a problem with the LPR3administration client for test. Using the same browser I could log in the the administration client for prod without being asked to login againg. Implying that the login via nemid went well and that SEB is not a problem there. 
Do you look further into the issue or are we supposed to go go to the servicedesk for SEB?

**Comment by TueCN** [comment]
The problem seems to have disappeared for me. If the problem persists or returns, please raise the issue with SEB. 
The same error page was displayed earlier when trying to log in to SDS' internal test environment, so it is not directly related to the server on https://lpradm-test.sds.dsdn.dk
