### ISSUE TITLE
Possible error responses for document submissions

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#27]
At https://scandihealth.github.io/lpr3-docs/ I see that there is an invalid response example with Schema and Schematron errors listed, but I don't see any examples of the business level errors that might be generated. Would it be possible to get an example of how these errors would be sent back in the RegistryResponse. Additionally, is there a list of the possible errors of this type that might be generated? As we develop workflows to allow these business level errors to be resolved, it would be extremely helpful to understand the types of errors we can expect to encounter.

**Comment by cjonigkeit-csc** [comment]
We will look at this first thing tomorrow.

**Comment by jonigkeit** [comment]
You can see a business rule error and warning [here](https://scandihealth.github.io/lpr3-docs/aspects/index.html#what-rules-apply-and-what-errors-can-be-reported-and-how).

A list of business rules deployed in the test environment can be found in the [test environment section](https://scandihealth.github.io/lpr3-docs/testenvironment/index.html).

The expected list of business rules that will be deployed when the system is put into production is defined by [Logisk datamodel og indberetningsregler - Bilag 1](https://sundhedsdatastyrelsen.dk/-/media/sds/filer/rammer-og-retningslinjer/patientregistrering/indberetning-til-lpr3/vejledning-lpr3-bilag-1-model-og-indberetningsregler.pdf?la=da) and [Resultatindberetningsspecifikationer (RI-specs) - Bilag 1a](https://sundhedsdatastyrelsen.dk/-/media/sds/filer/rammer-og-retningslinjer/patientregistrering/indberetning-til-lpr3/vejledning-lpr3-bilag-1a-ri_specs.pdf?la=da).

**NB:** SDS can add, change, and remove rules on a day to day basis once the system is put into production.
