### ISSUE TITLE
Which namespace to use when sending clinical docs?

### ISSUE THREAD

**Issue by metodikamikaelnilsson** [scandihealth/lpr3-docs#270]
Which namespace should we use when sending clinical docs to the https://lprws.sds.dsdn.dk/cda-ws/DocumentRepository_Service/-endpoints? This: http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd or this: http://svn.medcom.dk/svn/releases/Standarder/DGWS/Schemas/medcom-1.0.1.xsd?

**Comment by TueCN** [comment]
Use http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd

See https://scandihealth.github.io/lpr3-docs/examples

**Comment by MickeNilsson** [comment]
Thanks. Closing the issue.
