### ISSUE TITLE
Reporting of issues when in production

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#272]
Is this GitHub forum the official "issue handling tool" when LPR3 is in production?

Often you request stack trace and clinical documents as input to debugging.

**Comment by KirstenLHSDS** [comment]
SDS will answer this :-)

**Comment by KirstenLHSDS** [comment]
When in production, questions regarding understanding of validation can be asked to patientregistrering@sundhedsdata.dk
Other issues should be routed to servicedesk@sundhedsdata.dk
SDS is looking into providing a secure mail for sensitive information. A workaround can be to either use upload to sFTP or to provide only insensitive indicators.

**Comment by KirstenLHSDS** [comment]
It has been communicated to project managers, that future issues regarding production must be reported to SDS Servicedesk: servicedesk@sundhedsdata.dk 
The creator will be approaced, if sensitive information is required for evaluation of the issue
