### ISSUE TITLE
ForloebElement Cannot have ForloebReference to itself 

### ISSUE THREAD

**Issue by kbhCGI** [scandihealth/lpr3-docs#273]
Hi

We get this error "ForloebElement Cannot have ForloebReference to itself", but can't see that we are doing this.
Will you please look at it.

[Lpr3hl7.zip](https://github.com/scandihealth/lpr3-docs/files/2745090/Lpr3hl7.zip)

**Comment by jonigkeit** [comment]
It seems that the episode of care that you are reference has a reference to itself
![image](https://user-images.githubusercontent.com/1263467/51530720-e37c7900-1e3b-11e9-9838-eccf5611f96b.png)

**Comment by jonigkeit** [comment]
We will purge it from the system

**Comment by kbhCGI** [comment]
Cannot reproduce now.
