### ISSUE TITLE
LPR3 error 5107 | 05.107 sds:lpr:3.1.1

### ISSUE THREAD

**Issue by clausheinecke** [scandihealth/lpr3-docs#274]
Why are we getting this error, when we report what is expected?
![billede](https://user-images.githubusercontent.com/45626571/50970978-2dcc3480-14e3-11e9-9533-85c7b8c53f48.png)

**Comment by jimiclaussen** [comment]
Hi is there any possebility that we can get an answer today ?

**Comment by TueCN** [comment]
We do unfortunately not have the resources to investigate issue reports today. 
Hopefully we can get back to you next week.

**Comment by smunck** [comment]
SDS has looked into the problem. They can reproduce the error only if they add seconds in the CDA. That way the error is correct (because of the added seconds, there is less than a minute between the two times), but it is not visible in the user interface as seconds are not shown.
