### ISSUE TITLE
Next release: Will be 15. january at 11 (earlier than normal)

### ISSUE THREAD

**Issue by KirstenLHSDS** [scandihealth/lpr3-docs#276]
Dear all

Due to an request, it is decided to start the planned release tuesday earlier than normal schedule, ie starting at 11.00.

**Comment by TueCN** [comment]
Due to last minute changes in the new build, the server was only taken down now. 
We expect it to be back up around 14:00 CET

**Comment by TueCN** [comment]
Upgrade completed
