### ISSUE TITLE
Error in LPR3 administration client

### ISSUE THREAD

**Issue by CgiMofr** [scandihealth/lpr3-docs#280]

**Comment by CgiMofr** [comment]
After sending an update to an EpisodeOfCare we try to see the update in the administration client.
But we get a runtime error.
The two screendumps below should give enough information:

![gui-error1 jpg](https://user-images.githubusercontent.com/39047490/51249743-7dec4080-1994-11e9-98dc-b537da798558.jpg)

![gui-error jpg](https://user-images.githubusercontent.com/39047490/51249748-85abe500-1994-11e9-8e74-16a3fcfad77f.jpg)

**Comment by TueCN** [comment]
Have you tried to clear your browser cache? 
See https://github.com/scandihealth/lpr3-docs/issues/219#issuecomment-438594500

**Comment by TueCN** [comment]
Nevermind, I have reproduced the problem. It is not cache related.

**Comment by TueCN** [comment]
Hmm for some reason I can no longer reproduce the problem. 
Everything works as expected when I open the EoC now... 
@CgiMofr can you still reproduce the problem?

The validation timestamp is still 16-01-2019 12:08 so it does not look like anything has changed in the data. Very peculiar.

**Comment by TueCN** [comment]
@CgiMofr we still have problems reproducing the error.
> We have then sent it twice today.

I don't understand what you mean by that. You cannot register the same document multiple times without changing UUIDs.

Can you attach the input XML that reproduces the error?

**Comment by CgiMofr** [comment]
New example:
![pic1](https://user-images.githubusercontent.com/39047490/51603663-bba81680-1f0a-11e9-91a4-533f78869886.jpg)
[19012311580992.zip](https://github.com/scandihealth/lpr3-docs/files/2787056/19012311580992.zip)

**Comment by jonigkeit** [comment]
We believe this issue is caused by the same problem as #285

**Comment by KirstenLHSDS** [comment]
SDS will check status with DXC and if still an issue, create this as an incident in Servicedesk

**Comment by AzadehDXC** [comment]
This issue is closed since it should be fixed with the resolution of #285 .
