### ISSUE TITLE
Versioning in gui  mixup

### ISSUE THREAD

**Issue by CgiMofr** [scandihealth/lpr3-docs#284]
hi,
In the screendump below we expected only 2 versions,  That is: version #1 and #4 in the screendump.

![pic1](https://user-images.githubusercontent.com/39047490/51388759-aefe7980-1b2a-11e9-8312-577f256bb8ec.jpg)

Version #2 on screendump 1 seems to be:

![pic2](https://user-images.githubusercontent.com/39047490/51389031-6dba9980-1b2b-11e9-9788-0a21ba14b0cd.jpg)

and version #3 on screndump 1 seems to be:

![pic3](https://user-images.githubusercontent.com/39047490/51389055-7a3ef200-1b2b-11e9-8a15-12470de3baac.jpg)

**Comment by TueCN** [comment]
Sorry I do not understand your issue. 
Can you describe exactly what the problem is and attach the XML needed to reproduce the issue?

**Comment by CgiMofr** [comment]
On 16.01.2019 we have sent 0103970FØ2 twice, the last one is sent with version number 2.
![pic4](https://user-images.githubusercontent.com/39047490/51470297-c67c7300-1d73-11e9-8416-510063c77eb9.jpg)
We only expect 2 versions in ’Administrationsmodulet’, but there are 4, where are they from?
![pic5](https://user-images.githubusercontent.com/39047490/51470329-d85e1600-1d73-11e9-92cb-a7ce8eb68b96.jpg)

I do not know how to reproduce the issue.

**Comment by CgiMofr** [comment]
Reopened, because it was closed by accident

**Comment by jonigkeit** [comment]
The reason is that the episode of care was revalidated on
*2019-01-16T12:27:54.01000* and *2019-01T12:28:34.661000*

Revalidation causes creation of a new version.

If this behavior is undesirable for you, please file an enhancement request with SDS.
