### ISSUE TITLE
LPR3 servicen not available

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#286]
The LPR3 servicen is not available.

When sending a request to the LPR3 servicen we get:

- "DXC Traffic Manager: the service is temporarily unavailable (503). Please try again later.

Same result when opening the administration client.

**Comment by TueCN** [comment]
We are testing some snapshot/rollback procedures needed for the upcoming prod trial run.

Sorry for the inconvenience

**Comment by TueCN** [comment]
Normal service has resumed
