### ISSUE TITLE
UUID in accummulated error list are not represented correct

### ISSUE THREAD

**Issue by jonigkeit** [scandihealth/lpr3-docs#292]
`@extension` UUIDs are not communicated as required by [RFC 4122](https://www.ietf.org/rfc/rfc4122.txt), as the hyphens are missing.

Also the `@root` UUIDs are LPR-internal UUIDs and not the the externally communicated ones (set roots).

**Comment by RasmusThernoe** [comment]
**This is blocking**

This is preventing the Central Region from parsing the accumulated error list fetched from the reporting test.

**Comment by jonigkeit** [comment]
**RESOLUTION**
Formatted all UUID as required by RFC 4122 and using submitted values for `@root` instead of internal identifiers.

**Comment by TueCN** [comment]
Expected around 15 CET

**Comment by kdjohansson** [comment]
@TueCN When is the service expected to be down today?

**Comment by TueCN** [comment]
Expected around 14 CET
