### ISSUE TITLE
[minor issue] Formatting on Test environment page are broken

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#298]
This is just a minor issue.

The text about the new endpoints are a bit broken:
![image](https://user-images.githubusercontent.com/36299108/51990852-30022d00-24aa-11e9-863b-ecd173a67ccd.png)

Page:
https://scandihealth.github.io/lpr3-docs/testenvironment/index.html

**Comment by JacobBangSSE** [comment]
Same problem on the "Production environment" page:
![image](https://user-images.githubusercontent.com/36299108/51991003-78b9e600-24aa-11e9-904b-967b1954048b.png)

Link:
https://scandihealth.github.io/lpr3-docs/productionenvironment/index.html

**Comment by TueCN** [comment]
Hmm apparently my markdown previewer is not in line with MkDocs. 
Will fix
