### ISSUE TITLE
Appending Data from Old Encounters

### ISSUE THREAD

**Issue by jbraschler** [scandihealth/lpr3-docs#299]
If a document set consisting of a Pathway Element with encounters dating back over a long period of time (e.g, 18 months) is replaced (i.e., ClinicalDocument/relatedDocument/@typeCode="RPLC"), what would happen if we tried to subsequently append (i.e., ClinicalDocument/relatedDocument/@typeCode="APND")  a document to that document set containing one of the encounters that occurred 18 months ago? Would the service accept the document containing the old encounter with no errors, even though the encounter and all of the data attached to it is old enough to not actually be relevant for reimbursement?

**Comment by jonigkeit** [comment]
There are two principles that define the behavior

1. You're only able to append or replace to the latest document in the chain of document of a document set.
1. Replacing a document removes all data that has been communicated so far.

**Example**
 * On day `0` you submit document `a` with the document set `X` of version `1` containing episode of care `PCPR1`
**Now episode of care `PCPR1` exists in the registry**
 * On day `1` you submit document `b` to the document set `X` of version `1` with the new version `2` as an `append` to document `a` containing encounter `ENC1` that references episode of care `PCPR1`
**Now episode of care `PCPR1` with encounter `ENC1` exists in the registry**
 * On day `2` you submit document `c` to the document set `X` of version `1` with the new version `3` as an `append` to document `b` containing encounter `ENC2` that references episode of care `PCPR1`
***The request fails as the newest version of the document set `X` is `2`***
**Still episode of care `PCPR1` with encounter `ENC1` exists in the registry**
* On day `3` you submit document `c` to the document set `X` of version `2` with the new version `3` as an `append` to document `a` containing encounter `ENC2` that references episode of care `PCPR1`
***The request fails as the latest document of document set `X` is document `b`***
**Still episode of care `PCPR1` with encounter `ENC1` exists in the registry**
* On day `4` you submit document `c` to the document set `X` of version `2` with the new version `3` as an `append` to document `b` containing encounter `ENC2` that references episode of care `PCPR1`
**Now episode of care `PCPR1` with encounter `ENC1` and `ENC2` exists in the registry**
* On day `5` you submit document `d` to the document set `X` of version `3` with the new version `4` as an `replacement` to document `c` containing episode of care `PCPR1` and encounter `ENC2` and `ENC3` that references episode of care `PCPR1`
**Now episode of care `PCPR1` with encounter `ENC2` and `ENC3` exists in the registry**
* On day `6` you submit document `e` to the document set `X` of version `4` with the new version `5` as an `append` to document `d` containing procedure `PROC1` that references episode of care `ENC1`
***The request fails as the encounter `ENC1` does not exists in the registry***
**Still episode of care `PCPR1` with encounter `ENC2` and `ENC3` exists in the registry**
* On day `7` you submit document `e` to the document set `X` of version `4` with the new version `5` as an `append` to document `d` containing encounter `ENC1` that references episode of care `PCPR1`
**Now episode of care `PCPR1` with encounter `ENC1`, `ENC2`, and `ENC3` exists in the registry**
