### ISSUE TITLE
Cardinality on usage of DK Supplementary Code Act (used on act, observation, and procedure) is wrong

### ISSUE THREAD

**Issue by jkiddo-dxc** [scandihealth/lpr3-docs#3]
The Procedure section entries (act, observation, and procedure) specify that they can contain 0…1 entryRelationship elements corresponding to 1.2.208.176.7.1.10.5 DK Supplementary Code Act.

This cardinality should be 0..* according to SDS spec

**Comment by cjonigkeit-csc** [comment]
Fixed in preproduction [DK Procedure Act](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.25).
Awaiting deploy to production
