### ISSUE TITLE
Information about latest successful submission

### ISSUE THREAD

**Issue by MartinHylleberg** [scandihealth/lpr3-docs#30]
Consider the following scenario:
For all pseudo code below please assume that all documents are valid and contains the correct information.

1. A number of CDA documents have been reported.
Latest successfull CDA document had
`SetId = AAA-BBB-CCC
DocumentId= E
Version = 5
parentDocument: DocumentId = D, Version = 4`

2. We now create the next CDA document for reporting.
 ` SetId = AAA-BBB-CCC
  DocumentId = F
  Version = 6
  parentDocument: DocumentId= E, Version = 5
`
3. Document is being sent to SDS.
3.a. Http connection opens
3.b. document is sent.
3.c. document is persisted at SDS
3.d. response is about to be sent back, but connection fails.

Status is now as follows:
SDS: Everything is ok, Latest saved document has 
 ` SetId = AAA-BBB-CCC
  DocumentId = F
  Version = 6
  parentDocument: DocumentId= E, Version = 5
`
Reporter: The report failed. Latest saved document has
 ` SetId = AAA-BBB-CCC
  DocumentId = E
  Version = 5
  parentDocument: DocumentId= D, Version = 4
`

3. Connection is restored. Retry with document
4. An error is returned.

Seen from the submitters side there was an error and it must be assumed that the document was not saved.
Seen from SDS side everything was ok, the document was saved and a response was sent back.

So there is now a discrepancy between what the submitter and what the receiver knows without an obvious way to synchronize the information. 

So the question is: 
Will there be a way to retrieve the last successful submitted document information such that it is possible to correct the situation?

**Comment by cjonigkeit-csc** [comment]
That can indeed occur. You should be able to retrieve the set version and document id from the returned schematron errors.

**Comment by cjonigkeit-csc** [comment]
Having looked at the code, you will get an integrity / business error containing information about the latest version number and document id.
