### ISSUE TITLE
Unable to login to SDS test gui-client

### ISSUE THREAD

**Issue by MichaelEsmannSSE** [scandihealth/lpr3-docs#300]
When I try to login to the SDS gui-client I get this error message after typing the password for my certificate:

Request failed
The request failed. The reason is:

Unable to validate SAML message!
Stacktrace:

**Comment by TueCN** [comment]
Yes, SEB updated their test certificate last night. We are in the proces of updating it on our servers

**Comment by TueCN** [comment]
Heads up: We will be restarting the server shortly, to get the new certificate loaded

**Comment by jonigkeit** [comment]
**RESOLUTION**
IdP certificate has been updated.
