### ISSUE TITLE
ITI41 Response different

### ISSUE THREAD

**Issue by Remcovanderwerf** [scandihealth/lpr3-docs#302]
Hi,

just recently i discovered that the ITI-41 response message is a bit different than before.

before, the element `<ns10:FlowStatus>flow_finalized_succesfully</ns10:FlowStatus>`  was present under the `<soap:header>`.
See:
[with.txt](https://github.com/scandihealth/lpr3-docs/files/2816703/with.txt)

Just recently this element is not present anymore. See:
[without.txt](https://github.com/scandihealth/lpr3-docs/files/2816704/without.txt)

I used this element in the implementation to validate if the response i received is a valid response of the registry or not (for example "service unavailable"  does not hold this element).

Is there a reason that this element is not present anymore? 
Is there a chance to bring back this element?

Looking forward hearing from you!

Kind regards,

Remco van der Werf
Enovation | The Netherlands
Contractor: Region Syddanmark

**Comment by TueCN** [comment]
No this is not an intentional change, it is probably related to the changes in #240 

I will look into it

**Comment by TueCN** [comment]
I have identified the issue and will restore the old behaviour:
- FlowStatus will be set to `flow_finalized_succesfully` in all non-exceptional responses (i.e. HTTP 200 messages with a `RegistryResponse`)
- FlowStatus will **not** be set in SOAP fault messages.

**Comment by Remcovanderwerf** [comment]
Sounds great!

When will this change be active?

**Comment by TueCN** [comment]
I am testing a fix now. Is the issue blocking for your use of the service? 
I can deploy it straight away or it can be included in the normal release cycle (Tuesday)

**Comment by Remcovanderwerf** [comment]
Currently not so the normal deployment on tuesday will suffice.

I will plan on changing my configuration back for wednesdays.

Thank you!

**Comment by TueCN** [comment]
@Remcovanderwerf we have just deployed a new version (that also includes this fix). 
Please test now.

**Comment by Remcovanderwerf** [comment]
Hi @TueCN,

The response is as expected again including the "flow_finalized_succesfully".

Thank you for the investigation and solution, closing this issue.
