### ISSUE TITLE
LPR3 rule 02.03 Forløbselement reference starttime <= referenced FE starttime

### ISSUE THREAD

**Issue by clausheinecke** [scandihealth/lpr3-docs#304]
Hi
We find it inappropriate that a Forløbselement can't reference to another Forløbselement and they both have the same start time.
We will have a lot of those cases, like when we receive a referral and during the visitation process creates an order for a Xray or another investigation, the initial Forløbselement will have the same start time as the linked Forløbselement. We didn't find this to be an issue, before we began to receive the error messages.
We also see this error when we during conversion had multiple Kontakts on the same "patientforløb" and they got converted we created the Forløbselement according to the SDS guidelines (start time got incremented by 1 hour on the same responsible department) but since not all Kontakts had the same responsible department we sat the start time to be the same. Even though they referenced to each other.
Will you consider change the logic, so the start time can be the same?

**Comment by clausheinecke** [comment]
BTW: why do we get the error message linked to the Kontakt and not the Forløbselement? That doesn't make sense...

**Comment by TueCN** [comment]
Hi

1. > We find it inappropriate that a Forløbselement can't reference to another Forløbselement and they both have the same start time.  

    1. The logic is specified by Indberetningsvejledningen (see [Bilag 1](https://sundhedsdatastyrelsen.dk/-/media/sds/filer/rammer-og-retningslinjer/patientregistrering/indberetning-til-lpr3/vejledning-lpr3-bilag-1-model-og-indberetningsregler.pdf?la=da), id 02.03). These rules are defined by SDS. Please contact them directly.

2. > why do we get the error message linked to the Kontakt and not the Forløbselement?  
    
    1. This is due to how the rule logic is written. The rule author can specify which "indberetningselement" the validation error should be linked to. SDS administrates the rule logic implementations. Please contact them to get rule 02.03 errors linked to the Forløbselement instead of the Kontakt.


In general, this issue tracker site is inteded for technical issues only and non-technical issues should be directed at SDS directly.
