### ISSUE TITLE
schematron release notifications

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#31]
Is there a schedule or estimates of when you expect to release new versions of the schematrons? Having a regular schedule for future updates or at least published estimates of when new versions are expected will help us plan the testing of our LPR3 document development.

**Comment by jonigkeit** [comment]
Hi Dave

we will potentially release nightly builds of the entire IHE XDR interface from next week and until a few weeks before the system goes live.
Right now we are designing how to version and notify integrators of changes to the individual components that make up the interface, including documentation, example, SchemaTron etc., see more in the [governance section](https://scandihealth.github.io/lpr3-docs/governance/index.html).
