### ISSUE TITLE
Possible double submission issue

### ISSUE THREAD

**Issue by Remcovanderwerf** [scandihealth/lpr3-docs#311]
Hi,

can you please investigate the following (if possible).

environment: PRODUCTION
date/time:   24-01-2019   21:20:05

Document_id: `1E6F8C9B-7004-4C30-8FA7-55527E79330B`
Set_id: `E1CCA1F0-CA70-5215-A1F9-4ED375E3A9C4`
Version: 1 

Response: `INTEGRITY_CHECK|||Set with id e1cca1f0-ca70-5215-a1f9-4ed375e3a9c4 already exists in the registry, and ClinicalDocument does not contain a relatedDocument`

Issue: The response tells that the setid has already been submitted / used. The correct document was actually in the registry already since it was available in the portal. The CPR numbers were corresponding (which indicates there was no set-id clash).
This indicates that the document was submitted twice but from our sending application there is no sign of double submission whatsoever.

This issue occured for multiple documents but for all these occasions there is no sign of double submission from our sending application.

Are you able to investigate/check if this document was submitted twice and if yes by what times? Or could this be an issue on the LPR3 side?

Thank you in advance!

Kind regards,

Remco van der Werf
Enovation | The Netherlands
Contractor: Region Syddanmark

**Comment by jonigkeit** [comment]
Hi @Remcovanderwerf
What catches my immediate attention is that you are using UUID Version 5 values for your setId, and that is fine.
Can you explain the algorithm you use in your integration to produce the values, e.g. how are your namespaces constructed?

**Comment by Remcovanderwerf** [comment]
Hi @jonigkeit I currently am not able to get that information since these UUIDv5's are not generated in my implementation.

I think you are indirectly indicating it could be a set-id clash with another region but the data was actually in the LPR3 prod environment at that time.
So the current conclusion which we made is that the submission of this particular document happened twice. 

I would like to know if this particular document was actually submitted twice (for example in a short time) - either by our sending application or maybe something odd happened on the LPR3 side.

**Comment by TueCN** [comment]
@Remcovanderwerf you state the environment as PRODUCTION, but Region Syd is not scheduled to use LPR production before March. 
I think you mean the environment is TEST (i.e. https://lprws-test.sds.dsdn.dk)

**Comment by Remcovanderwerf** [comment]
@TueCN Hi,

no I definitely mean the production environment. At the time of the submission (24th of january)  we had a window of opportunity to do a progression test towards the production environment to see if the performance is as expected.

I have been understanding from my contacts that the data submitted to this production environment was wiped completely afterwards. This could mean that investigating this issue is not possible but if it is I would like to ask if it is possible to check your logs on the LPR3 prod environment.

Thank you in advance!

**Comment by TueCN** [comment]
Ah okay, yes that makes sense.
Yes unfortunately I believe the data is wiped and no logs were kept (I will verify this with our operations team).

If you can reproduce the issue on TEST we will be happy to assist in your investigation.

**Comment by Remcovanderwerf** [comment]
It is hard to actually reproduce this issue.
On an amount of ~600.000 submissions only 7 submissions had this issue.

Awaiting your response from the operations team but otherwise this call may be closed.

**Comment by TueCN** [comment]
@Remcovanderwerf I have gotten word back that it takes considerable effort to restore the data submitted during the "production test run". 

Based on the nature of the issue (there is seemingly nothing wrong on the LPR side), SDS decided not to allocate the resources needed for this endeavor. 
Please close this issue or take it with SDS directly. 

Feel free to open a new issue if you can reproduce any erroneous LPR behavior on TEST

**Comment by Remcovanderwerf** [comment]
Hi @TueCN ,

sounds reasonable. Thank you for the effort anyway!

Kind regards,

Remco van der Werf
