### ISSUE TITLE
LPR3 service unstable

### ISSUE THREAD

**Issue by MichaelEsmannSSE** [scandihealth/lpr3-docs#312]
Currently I very often get these errors when calling https://lprws-test.sds.dsdn.dk/cda-ws/medcom-1.0.1/DocumentRepository_Service/PatientHealthcareReportingService:

504 Gateway Time-out
The server didn't respond in time.

Service Unavailable
DXC Traffic Manager: the service is temporarily unavailable (503). Please try again later.

**Comment by TueCN** [comment]
Hmm this seems to be the same problem as #308.
The prod hotfix https://github.com/scandihealth/lpr3-docs/issues/308#issuecomment-461038566 has not been deployed to TEST yet 
(TEST is scheduled for deployment on Tuesday). 

I have restarted the TEST service and it should again run normally. 
There is a small risk of performance degradation happening from now and until the bugfix is deployed.

**Comment by MichaelEsmannSSE** [comment]
Looks better now. I will close the issue
