### ISSUE TITLE
lpradm-test. A Technical error has occured

### ISSUE THREAD

**Issue by Kashif-Ali-110** [scandihealth/lpr3-docs#313]
Hi Scandihealth,

I am getting error while logging to the [https://lpradm-test.sds.dsdn.dk]

I get nemid login form and gives functional test certificate as credential to sign-in.  But it gives
Technical error message.

![lpradmin-test](https://user-images.githubusercontent.com/45459597/52943257-0a5f9980-336d-11e9-9e27-1ebf02feaf25.png)

Any idea about how to get access to the LPR Administrative module?

Thanks in advance

With best,
Kashif

**Comment by TueCN** [comment]
Hi

When you go to https://lpradm-test.sds.dsdn.dk you should be redirected to nemlog-in.dk where you must log in with credentials that are registered in test SEB (t-seblogin.nsi.dk). After logging in you should be redirected back to LPR.

If this redirect back to LPR does not work, there must be a problem with your SEB login? 
Have you verified with a SEB administrator that your user have a SEB test login?

The login process currently works fine for my user.

Read more about SEB here: https://services.nsi.dk/seb

**Comment by Kashif-Ali-110** [comment]
Hi @TueCN 

Thanks for your reply.

I think we are missing the T-SEB authentication part.

But we are in process with the Sundhedsdatastyrelsen to get authentication about it.

Thanks for your quick reply :)

With best,
Kashif
