### ISSUE TITLE
Requested Envelope -  Body part

### ISSUE THREAD

**Issue by Kashif-Ali-110** [scandihealth/lpr3-docs#316]
Hi,

I have developed soap request with valid assertion, And the body part of the request is given below.
[ProvideAndRegisterDocumentSetEnvelope Body part.txt](https://github.com/scandihealth/lpr3-docs/files/2889633/ProvideAndRegisterDocumentSetEnvelope.Body.part.txt)

> INTEGRITY_CHECK|||The submission set must have an ihe-xdr Classification/Slot element with an authorInstitution attribute that conforms to the 'XDS Metadata for Document Sharing. Danish Profile'|||AUTHOR_INSTITUTION_NOT_FOUND" 
> 

From where can i get the valid registry or repository object, schema's etc uuids ?
Are i am missing the valid registry or repository uuid's?

With best,
kashif

**Comment by jonigkeit** [comment]
That information is available in [the documentation](https://scandihealth.github.io/lpr3-docs/) and the [related material](https://scandihealth.github.io/lpr3-docs/links/index.html).
Ultimately your customer will have to answer which concrete code to use.

**Comment by jonigkeit** [comment]
@Kashif-Ali-110 can you try again, seems like the code 324431000016003 was registered instead of 324441000016005

**Comment by Kashif-Ali-110** [comment]
Hi

Thanks for your quick reply. 

Unfortunately, I am unsuccessfully even by changing the SOR Id to 324431000016003.

Below is the MIME logfile. 
[LPR3MtomLog.txt](https://github.com/scandihealth/lpr3-docs/files/2890181/LPR3MtomLog.txt)

Thanks in advance to your time and help.

With best
kashif
