### ISSUE TITLE
Release notifications

### ISSUE THREAD

**Issue by MartinHylleberg** [scandihealth/lpr3-docs#32]
Hey
In the [Test environment](https://scandihealth.github.io/lpr3-docs/testenvironment/index.html) section it is specified that "New deployments will be notified through GitHub no later than end of business day before nightly deploy."

How are we supposed to subscribe to the notifications? 
There is no way (that I know of) to subscribe to updates to the code (commits) unless you start using third party software.

**Comment by jonigkeit** [comment]
Quoting [GitHub Help > about notifications](https://help.github.com/articles/about-notifications/)

> Watching notifications are received for updates in repositories or team discussions that you're watching. You'll receive a notification when:
>
> \> An issue is opened.
> \> A comment is added to an open issue.
> \> A pull request is opened.
> \> A comment is added to an open pull request.
> \> A comment is added to a commit.
> \> A release is published. For more information, see "About releases."
> \> A review is submitted that approves or requests changes to a pull request.
> \> For a team you're watching, a team discussion is created or a reply is added. For more information, see "About team discussions."
> \> For the parent team of a team you're a member of and watching, a team discussion is created or a reply is added. For more information on nested teams, see "About teams."
>
>A team discussion post for a parent team of or a team you're a member of and watching, is opened, edited, or replied to. For more information, see "Nested teams."
