### ISSUE TITLE
Landspatientregisteret - Templates is down

### ISSUE THREAD

**Issue by Kashif-Ali-110** [scandihealth/lpr3-docs#320]
Hi 

http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?id=1.2.208.176.7.1.10.36&effectiveDate=dynamic

is not running?

**Comment by TueCN** [comment]
Hi,

The link is working fine for me. 
The server might have had a hiccup. Please retry the link.
