### ISSUE TITLE
Code: XDSMissingDocumentMetadata - AUTHOR_INSTITUTION_NOT_FOUND

### ISSUE THREAD

**Issue by joelmetodika** [scandihealth/lpr3-docs#321]
Hi, one of our customers is not able to report to the LPR3 test system. They are getting the error message:
"Code: XDSMissingDocumentMetadata

Description: INTEGRITY_CHECK|||The submission must have an ice-xdr Classification/Slot element with an authorInstitution attribute that conforms to the XDS Metadata for Document Sharing. Danish Profile’|||AUTHOR_INSTITUTION_NOT_FOUND"

From what I can understand this means that the author of the document does not exists in LPR3? I have a screenshot from the LPR3 admin website where their SOR-id and name seems to match what we send in the file. Here is an excerpt from an example file:

<author typeCode="AUT">
	<templateId root="1.2.208.176.7.1.10.102"></templateId>
	<templateId root="2.16.840.1.113883.10.12.102"></templateId>
	<time value="20190304140935+0100"></time>
	<assignedAuthor classCode="ASSIGNED">
		<id nullFlavor="NI"></id>
		<representedOrganization classCode="ORG" determinerCode="INSTANCE">
			<id assigningAuthorityName="SOR" root="1.2.208.176.1.1" extension="412551000016004"></id>
		</representedOrganization>
	</assignedAuthor>
</author> 

According to the customer they have been registered in LPR3 as reporters to both test and live with the sor-id in the code excerpt, so I am unsure what can be wrong. Maybe there is some mismatch with what is registered in LPR3 and what they are reporting?

**Comment by TueCN** [comment]
Hi, 
I assume this issue is related to test and not prod?
Please attach the full SOAP request body here alongside the aforementioned screenshot.

**Comment by TueCN** [comment]
Yes, unfortunately I need the XDR part. 
The AUTHOR_INSTITUTION_NOT_FOUND error happens because LPR cannot find the 
`/soap:Envelope/soap:Body/ProvideAndRegisterDocumentSetRequest/SubmitObjectsRequest/RegistryObjectList/RegistryPackage/Classification/Slot/ValueList/Value`

An example value would be e.g.
```xml
<ns2:Value>Region Nordjylland^^^^^&amp;1.2.208.176.1.1&amp;ISO^^^^6071000016008</ns2:Value>
```

See https://scandihealth.github.io/lpr3-docs/examples/index.html#sample-request-using-mtomxop

**Comment by joelmetodika** [comment]
Hi, we found out what was wrong with the setup. They were missing the 5 "^" that comes after the name in the ns2:Value-tag in the image in your post. So problem solved. 

Thanks!
