### ISSUE TITLE
RegistryObjectList missing properties in WSDL generation

### ISSUE THREAD

**Issue by vprxa** [scandihealth/lpr3-docs#324]
Hi Scandihealth,
I am using the following WSDL to generate classes in C#:
[https://lprws-test.sds.dsdn.dk/cda-ws/DocumentRepository_Service/PatientHealthcareValidateReportingService?WSDL](https://lprws-test.sds.dsdn.dk/cda-ws/DocumentRepository_Service/PatientHealthcareValidateReportingService?WSDL)

The ProvideAndRegisterDocumentSetRequestTypeRequest > SubmitObjectsRequest > RegistryObjectList class is different to the sample provided:
- It contains an IdentifiableType[] array.
- It is missing an ExtrinsicObject. An ExtrinsicObjectType class exists but isn't referenced.
- The slots are contained within Identifiable. The sample request are contained within RegistryPackage.
- The Identifiable is missing a Classification.

Here is what the request looks like:
 
```
<ProvideAndRegisterDocumentSetRequest xmlns="urn:ihe:iti:xds-b:2007">
      <SubmitObjectsRequest id="19ac3ca7-0c50-49ad-a0f0-7f446e8893cb" comment="Value for: comment" xmlns="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0">
          <RequestSlotList xmlns="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" />
          <RegistryObjectList xmlns="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0">
              <Identifiable id="16ec1573-81e4-4901-bb79-77fe2a09c8ba" home="Value for: home">
                  <Slot name="submissionTime" slotType="Value for: submissionTime">
                      <ValueList>
                          <Value>20190311144202</Value>
                      </ValueList>
                  </Slot>
                  <Slot name="authorInstitution" slotType="Value for: authorInstitution">
                      <ValueList>
                          <Value>Novax^^^^^&amp;1.2.208.176.1.1&amp;ISO^^^^300871000016004</Value>
                      </ValueList>
                  </Slot>
                  <Slot name="SubmissionSetStatus" slotType="Value for: SubmissionSetStatus">
                      <ValueList>
                          <Value>Original</Value>
                      </ValueList>
                  </Slot>
              </Identifiable>
          </RegistryObjectList>
      </SubmitObjectsRequest>
      <Document id="56895368-22d2-482a-93b4-95592fc20524">
          <xop:Include href="cid:http://tempuri.org/1/636879121350409378" xmlns:xop="http://www.w3.org/2004/08/xop/include" />
      </Document>
  </ProvideAndRegisterDocumentSetRequest>
```
  
I receive the following error:
> "INTEGRITY_CHECK|||The submission set must have an ihe-xdr Classification/Slot element with an authorInstitution attribute that conforms to the 'XDS Metadata for Document Sharing. Danish Profile'|||AUTHOR_INSTITUTION_NOT_FOUND"

I suspect it is because I unable to set the RegistryObjectList > ExtrinsicObject > Classification as per #188:

Any advice would be appreciated.

Thank you,
Joe

**Comment by TueCN** [comment]
@vprxa what is it you believe is wrong in the WSDL offered by [TEST](https://lprws-test.sds.dsdn.dk/cda-ws/DocumentRepository_Service/PatientHealthcareValidateReportingService?WSDL) compared to the example request listed on [lpr3-docs](https://scandihealth.github.io/lpr3-docs/examples/index.html#sample-request-using-mtomxop)?

To me it looks like the referenced [XDS.b_DocumentRepository.xsd](https://lprws-test.sds.dsdn.dk/cda-ws/DocumentRepository_Service/PatientHealthcareValidateReportingService?xsd=xsd/IHE/XDS.b_DocumentRepository.xsd) looks like expected. The imported [rim.xsd](http://lprws-test.sds.dsdn.dk/cda-ws/DocumentRepository_Service/PatientHealthcareValidateReportingService?xsd=xsd/ebRS/rim.xsd) describes the type `RegistryObjectListType` as containing an array of `Identifiable`, which can be substituted by `RegistryObject`

```xml
  <element name="RegistryObject" type="tns:RegistryObjectType" substitutionGroup="tns:Identifiable" />

  <complexType name="RegistryObjectListType">
    <sequence>
      <element maxOccurs="unbounded" minOccurs="0" ref="tns:Identifiable"/>
    </sequence>
  </complexType>

```

Sorry, I can not offer advice on client implementation. 
The WSDL and sample requests should be valid and working.

**Comment by vprxa** [comment]
Hi @TueCN , 
I am making a comparison between WSDL class generation in C# and the sample LPR3 request.
Here are the generated classes after consuming the WSDL:
[LPR3DocumentRepositoryService.txt](https://github.com/scandihealth/lpr3-docs/files/3039433/LPR3DocumentRepositoryService.txt)

- The RegistryObjectList in class generation is constrained to be IdentifiableType[].
- The ExtrinsicObject is not referenced or available to set.

I am therefore not able to achieve the desired envelope when the request is sent, calling the DocumentRepository_ProvideAndRegisterDocumentSetb method with the DocumentRepository_PortTypeClient client.

I have taken the following approaches:

- Service reference (Visual Studio)
- Web reference .NET 2.0 (Visual Studio)
- Wsdl.exe:
```
cd "C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools"

wsdl.exe https://lprws-test.sds.dsdn.dk/cda-ws/medcom-1.0.1/DocumentRepository_Service/PatientHealthcareValidateReportingService?wsdl /out:LPR3DocumentRepositoryService.cs
```

I have never experienced namespace or model generation differences working with similar services. 
Should I be consuming the service differently?

Thank you,
Joe

**Comment by vprxa** [comment]
Hi @TueCN ,

Thank you for the information regarding the substitution of objects.
I realize now I am not constrained to IdentifiableType[].

I'm happy to close the issue as I continue in new light.

Thank you,
Joe
