### ISSUE TITLE
Another one: org.hibernate.exception.ConstraintViolationException: could not execute batch

### ISSUE THREAD

**Issue by binntho** [scandihealth/lpr3-docs#328]
Clearly the same error as in issue 322 and 318, but apparently with different causes.

In my scenario, every single attempt to submit for one client (psychiatrist) fails with the same error message, while all submits for another client (eye hospital) succeeds without problems.

The error message in full:

javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute batch

I have already sent two examples to TueCN, more examples available on request!

I'm working for Aver & Lauritzen Aps, journalsystem GANGLION.

**Comment by binntho** [comment]
Update: I am now getting this error on every single attempt to submit a Clinical document. Total failure of LPR3?

**Comment by Kashif-Ali-110** [comment]
@binntho  I am getting this same error in our Test environment for the last one week on every single attempt. I have also created a post about it  #325 . 

Have you get rid of this error or any update about it? Would like to hear if any :)

With best,
Kashif @ MyClinic.

**Comment by TueCN** [comment]
@binntho now that solutions for #322 and #318 are being tested, please retry your submissions and let me know if you still experience issues.

**Comment by TueCN** [comment]
@binntho I re-examined your request and can see it is invalid.

You assign the same extension to 3 different Main condition observations. 
Extensions must be globally unique.

With [version 3.8.872](https://github.com/scandihealth/lpr3-docs/milestone/43) your submission no longer generates a runtime error, instead you will get an INTEGRITY_CHECK validation error that says  
`CONDITION_OBSERVATION_ALREADY_EXISTS`
(the 1st condition observation was processed and the extension registered, and then the 2nd condition observation encountered with same extension will give the error)

**Comment by binntho** [comment]
Hi Tue, thanks for that! I'll look at it tomorrow,.

**Comment by binntho** [comment]
OK, this is now solved and closed!
