### ISSUE TITLE
Introduction of new error type for integrity errors

### ISSUE THREAD

**Issue by cjonigkeit-csc** [scandihealth/lpr3-docs#33]
Currently the logical validation flow of the IHE XDR interface is as follows
`XSD -> SchemaTron -> Business rule`
This means that all errors, that are not XSD or SchemaTron errors, are Business rule errors. This includes integrity errors, e.g.
 * referring an entity via an id that does not exist
 * specify a stale setId versionNumber
 * exchanging the patient in a set of clinical documents

While the business rule error typically happen due to EHR user behavior, the above errors are of a technical nature and can most likely not be resolved by an EHR user as opposed to a developer.

Therefore DXC suggests to introduce a new error type `INTEGRITY_CHECK`.

**Comment by cjonigkeit-csc** [comment]
To ensure backward compatibility an optional SOAP Header will be introduced. If and only if the header is present and set to true, will errors be split between INTEGRITY_CHECK and BUSINESS_RULE.
If the header is not present or not set to true, all errors, that are not XSD or SchemaTron errors, are Business rule errors.

**Comment by RasmusThernoe** [comment]
It is possible to get a new interface specifikation with the optional INTEGRITY_CHECK element present in the SOAP header?

**Comment by jonigkeit** [comment]
As soon we have finalized it and tested will update the documentation.

**Comment by TueCN** [comment]
**RESOLUTION**
New error type implemented.

See updated documentation on  
https://scandihealth.github.io/lpr3-docs/aspects/index.html#what-rules-apply-and-what-errors-can-be-reported-and-how 

(Change set b1065af)
