### ISSUE TITLE
Difference between responsfiles and LPR

### ISSUE THREAD

**Issue by AnneRegionSyd** [scandihealth/lpr3-docs#334]
We have recived some response files containing business rules but in LPR there is no business rules to see. Please explain why there is a difference. 

Example: 3e3e209d-d402-5ebb-bd1e-cc7c77e61084
Reporting 26.03.2019 contains a business rule and reporting 28.03.2019 the business rule is gone - but not in the responsfile.

**Comment by KirstenLHSDS** [comment]
Please report this to SDS Servicedesk: servicedesk@sundhedsdata.dk
Thank you!
