### ISSUE TITLE
LPR3 Rule 9.41, 9.44 and 11.42: SOR units have a future end date

### ISSUE THREAD

**Issue by clausheinecke** [scandihealth/lpr3-docs#337]
There is a general issue with how SOR is build regarding how to register the end date on a Unit.
As soon as you have marked the Unit as being closed by setting the end date, you can't undo it!
The only option available is to set the end date to be in the future (way out in the future).
This is the case for some of our units like this one:
![billede](https://user-images.githubusercontent.com/45626571/55606160-0bf7ec00-5778-11e9-9de5-630dfd87990d.png)

Due to this issue we receive errors on kontakts, when such a unit is registered as either Ophold, Responsible or Producing unit.
Because of this issue in SOR, we kindly encourage you to change the validation rules, where you validate a SOR unit's end date, to ignore the end date if that date is in the future.

**Comment by KirstenLHSDS** [comment]
Hello Claus
Thank you for the issue. As this is regarding validationrules, it will be SDS to answer. 
Hence, I will like you to adress this issue to: servicedesk@sundhedsdata.dk, marked as LPR valideringsregler and please close this at Github. 
All issues should be sent to SDS - primarily servicedesk@sundhedsdata.dk but questions regarding registration (indberetningsvejledningen) can be sent to patientregistrering@sundhedsdata.dk 

Thank you!

**Comment by clausheinecke** [comment]
I've reached out to SDS.
Closing ticket.
