### ISSUE TITLE
Simplifying format of cumulative error list

### ISSUE THREAD

**Issue by cjonigkeit-csc** [scandihealth/lpr3-docs#34]
The cumulative error list format is currently deigned on IHE XDR Registry Responses.
This puts unnecessary complexity on both the produces and consumers of the error list and greater risk on the LPR3 project as a whole.

Therefore DXC suggest a [simpler JSON format](https://github.com/scandihealth/lpr3-docs/blob/master/src/res/error.example.us.json) for the error list.

**Comment by cjonigkeit-csc** [comment]
The notion is seconded by Systematic:

![outlook_2018-02-05_13-38-31](https://user-images.githubusercontent.com/23720057/35804917-144c3e52-0a7a-11e8-8897-e506b78a77dd.png)

**Comment by DaveSS** [comment]
I worry about the switch to JSON for the error codes at this point. We are implementing the IHE XDR communications which expect the RegistryResponse to contain errors in XML. While the format of the errors is a bit cumbersome, and the additional information included in the JSON is nice, it isn’t what we expect to receive when implementing XDR. Could you explain how you see the JSON fitting into the IHE XDR communications requirements? Is this something you hope to implement in addition to the standard RegistryResponse errors formatted as you detailed on github?

**Comment by cjonigkeit-csc** [comment]
We are not going to change the XDR Response. That remains how it is.
There is a secondary API (S-FTP), where a reporter can retrieve a list of all current* warnings and errors related to his reported data.

**Comment by mhylle** [comment]
In addition to the above proposal regarding including document information setid) we would also like to propose that variable names are in english.

**Comment by DaveSS** [comment]
Just so I am clear, is this S-FTP API only available to files submitted asynchronously?

**Comment by RasmusThernoe** [comment]
After examining the example JSON file I have a couple of questions regarding the hierarchical structure of the format:

- If an encounter (ENC) is outside the time limits of the episode of care (EOC). Will the JSON format include an error on both the EOC and the ENC?

- If a procedure has an error - e.g. non valid topography - will the JSON format include the complete path to the procedure even though the EOC (and ENC) does not have errors?

- If there are no errors or warnings for an EOC will there still be an "empty" file - representing the EOC - in the accumulated error folder?

- In the example JSON file it looks like the diagnosis and procedure contains a result reporting. Is that correct?

**Comment by RasmusThernoe** [comment]
At the meeting on the 7th of February I raised the issue regarding information about SetId, DocumentId and Version in the JSON format.

In the reply I was told that it will be difficult to state the DocumentId and Version. I did not understand why since I perceive the DocumentId as a message id and every error at the accumulated error list must be caused by a specific message to LPR3. Could you please explain?

The document id and version will be important for our debugging and it is part of the XDR response.

**Comment by RasmusThernoe** [comment]
One more question: Will the error texts in the JSON format - from the accumulated error list - be the ones defined in "Vejledning LPR3 v 1.1 bilag 1 Model og indberetningsregler" in the column "Definition/forklaring"?

**Comment by RasmusThernoe** [comment]
We are still awaiting an answer regarding the questions above.

**Comment by cjonigkeit-csc** [comment]
> In addition to the above proposal regarding including document information setid) we would also like to propose that variable names are in english.
The format has been changed to English.

> Just so I am clear, is this S-FTP API only available to files submitted asynchronously?
Let me try to clarify
#### The old Danish National Patient Register (LPR2)
LPR2 has two types of APIs.
 * A simple synchronous SOAP API that uses a simple purpose build XML format to report encounters.
 * An asynchronous S-FTP API that uses fixed width flat files to report encounters. This API has an accumulated error list. Regardless of how encounters have been reported, all encounters with errors and warnings are present in the accumulated error list. The accumulated error list is updated nightly.
#### The new Danish National Patient Register (LPR3)
LPR3 has two types of APIs.
 * A synchronous IHE/XDR HL7 CDA API to report patients, episodes of care, encounters, conditions, procedures, and observations using CRUD operations supporting partial updates. In its responses the API notifies the caller about any errors and warnings that a request has caused.
 * An asynchronous S-FTP API that _given this enhancement_ provides an accumulated error list of all patients, episode of cares, encounters, conditions, and observations that have errors or warnings. The accumulated error list is formatted as JSON. The accumulated error list is updated nightly.

This enhancement request concerns the asynchronous S-FTP API of LPR3.

> If an encounter (ENC) is outside the time limits of the episode of care (EOC). Will the JSON format include an error on both the EOC and the ENC?
The error will be on the encounter.

>If a procedure has an error - e.g. non valid topography - will the JSON format include the complete path to the procedure even though the EOC (and ENC) does not have errors?
Yes.

> If there are no errors or warnings for an EOC will there still be an "empty" file - representing the EOC - in the accumulated error folder?
If there are neither error or warnings on an episode of care and it transitive closure with the exception of link episodes of care there will be no file.

> In the example JSON file it looks like the diagnosis and procedure contains a result reporting. Is that correct?
Yes. See [UML diagram of the internal model](https://scandihealth.github.io/lpr3-docs/img/LPR3.png)

> In the reply I was told that it will be difficult to state the DocumentId and Version. I did not understand why since I perceive the DocumentId as a message id and every error at the accumulated error list must be caused by a specific message to LPR3. Could you please explain?
See #42.

> Will the error texts in the JSON format - from the accumulated error list - be the ones defined in "Vejledning LPR3 v 1.1 bilag 1 Model og indberetningsregler" in the column "Definition/forklaring"?
Yes. Keep in mind that as SDS changes rules the text may change as well.

**Comment by cjonigkeit-csc** [comment]
Correction to

> Will the error texts in the JSON format - from the accumulated error list - be the ones defined in "Vejledning LPR3 v 1.1 bilag 1 Model og indberetningsregler" in the column "Definition/forklaring"?

After consulting with SDS, it has been agreed that the error descriptions will be rephrased, so that end users such as clinicians will be able to understand them and do the necessary corrections in their EHRs.

**Comment by jonigkeit** [comment]
The change request has been approved by SDS
