### ISSUE TITLE
Certificate error on SDS testsystem

### ISSUE THREAD

**Issue by MichaelEsmannSSE** [scandihealth/lpr3-docs#343]
We are currently receiving this SOAP fault from SDS when calling https://lprws-test.sds.dsdn.dk/cda-ws/medcom-1.0.1/DocumentRepository_Service/PatientHealthcareValidateReportingService:

`<soap:Fault>
         <soap:Code>
            <soap:Value>soap:Receiver</soap:Value>
         </soap:Code>
         <soap:Reason>
            <soap:Text xml:lang="en">Intermediate certificate could not be found at http://f.aia.systemtest22.trust2408.com/systemtest22-ca.cer</soap:Text>
         </soap:Reason>
      </soap:Fault>
`

**Comment by TueCN** [comment]
Yes, we get the same error. 
We are working on it.

**Comment by TueCN** [comment]
It seems that STS test is using a new certificate. 

**RESOLUTION**
LPR _test_ service has been updated with a new local keystore that contains the new certificate found at http://f.aia.systemtest22.trust2408.com/systemtest22-ca.cer.

System should be working as normal again.
