### ISSUE TITLE
Optional CDA elements

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#35]
We would like to verify that it will be acceptable for us to add some elements to the LPR3 documents that are not specified in the art-decor site but are allowed by the CDA schema (note we don't make any expectations about the system receiving the documents to make any use of the data in these elements since their use is not specified in LPR3.) For example, we find it useful to include text elements in section and entry-level elements of CDA documents in order to allow users to easily render information from the LPR3 document that might be helpful for review and error resolution. Since these elements are allowed the CDA and are not prohibited by the LPR3 specification, we expect that it is OK to populate these elements, but we want to verify that this is the case.

**Comment by jonigkeit** [comment]
That should be fine as the templates are open, i.e. allowing other than the specified content.
However the system is required to log all incoming data, which in the case of unnecessary information would lead to a higher demand on storage.
We will ask Sundhedsdatastyrelsen if they have any objections.

**Comment by jonigkeit** [comment]
The question is under evaluation by Sundhedsdatastyrelsen since Friday.

**Comment by jonigkeit** [comment]
Any complaint document is allowed, i.e. you can send optional CDA elements.
