### ISSUE TITLE
Validation Failed (1): Unable to find signature.

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#37]
This issue is based on the technical issues @mhylle mentioned in #36.

When we try send a CDA Document to any of the services listed in:
https://scandihealth.github.io/lpr3-docs/testenvironment/index.html

We gets this error:
```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <env:Header xmlns:env="http://www.w3.org/2003/05/soap-envelope"/>
   <soap:Body>
      <soap:Fault>
         <soap:Code>
            <soap:Value>soap:Receiver</soap:Value>
         </soap:Code>
         <soap:Reason>
            <soap:Text xml:lang="en">Validation Failed (1): Unable to find signature.</soap:Text>
         </soap:Reason>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>
```

I have attached the full HTTP package we try sending:
[http_post_request1.txt](https://github.com/scandihealth/lpr3-docs/files/1712325/http_post_request1.txt)

**Comment by jkiddo** [comment]
You are missing all DGWS headers in the request

**Comment by JacobBangSSE** [comment]
You are correct. We will take a closer look into this.
