### ISSUE TITLE
Country codes value set

### ISSUE THREAD

**Issue by LarsGramMathiasen** [scandihealth/lpr3-docs#38]
Is the value set for country codes (http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-valuesets--lpr-?id=1.2.208.176.1.2.3) based on any ISO standard? If so, which? If not, when can we expect the value set to be finished, such that we can provide correct country codes?

Background: In CDA documents, country (on addr, on patientRole on recordTarget) should contain zero or one [0..1] country, with the value of country drawn from value set: [1.2.208.176.1.2.3](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-valuesets--lpr-?id=1.2.208.176.1.2.3&effectiveDate=dynamic) CPR Country Identifiers (DYNAMIC).
**Source: http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-** (CDA Header Level Template -> DK Alternatively Identified Patient Role (2.1.1) -> hl7:patientRole -> Included -> hl7:addr -> Included -> hl7:country)

Example CDA document with country set: https://github.com/scandihealth/lpr3-docs/blob/master/src/examples/Removal.EpisodeOfCare.xml

**Comment by jonigkeit** [comment]
All value sets are maintained externally to art decor. Consult the Indberetningsvejledningen.

**Comment by jonigkeit** [comment]
We have updated art decor to reflect the externally managed value sets, e.g. [DK Country Identifiers](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-valuesets--lpr-?id=1.2.208.176.1.2.3&effectiveDate=2017-03-01T00:00:00)

**Comment by jonigkeit** [comment]
If you are new to danish national it infrastructure I can inform you that `myndighedsregisteret`(Authority Register) where country and municipality code are maintained, is managed by the Danish Central Person Register (CPR).
You can find information on the `myndighedsregister` [here](https://www.cpr.dk/kunder/gratis-download/myndighedsregister-og-udtraeksbeskrivelse/)

**Comment by LarsGramMathiasen** [comment]
Thank you. I found a complete list here https://www.cpr.dk/media/17645/oversigt-over-lande-og-landekoder.pdf.

**Comment by cjonigkeit-csc** [comment]
@LarsGramMathiasen keep in mind that the content of the value set changes over time. I urge you automatically check and parse [the fixed width file](https://www.cpr.dk/media/17640/a370716.txt).

**Comment by cjonigkeit-csc** [comment]
Recall that a reporting authority is obliged to specify the municipality code, if the reporting authority possess that information.
