### ISSUE TITLE
LPR3 schematron

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#39]
The last schematron files available at GitHub are dated 1/3/2018. There have been numerous changes made to the CDA specification since then and it is difficult for us to internally test LPR3 documents we generate unless we have more current schematron files. Is it possible to provide us with a more accurate version of the schematron.

**Comment by jonigkeit** [comment]
We will update our build environment to continuously release latest unstable to this repository.
Stay tuned.

**Comment by jonigkeit** [comment]
Latest unstable can be obtained from https://github.com/scandihealth/lpr3-cda/blob/unstable/schematron.unstable.zip?raw=true.
