### ISSUE TITLE
FTP file state

### ISSUE THREAD

**Issue by MartinHylleberg** [scandihealth/lpr3-docs#41]
Just a small clarification:
On the meeting feb 7 2018 @jonigkeit informed us that the FTP server for the accumulated errorlist would experience a short down time of about 1 minute each night to wipe old error files and add new accumulated error files, such that when the server was up and running it would be the entire error set that is being represented by the amount of files on the server.

As we are planning on designing our use of the FTP server based on this we would like clarification that this is the case.

**Comment by jonigkeit** [comment]
Every night after midnight all rules are reevaluated. Every episode of care element or its contained encounters, conditions, procedures, or observation organizers that has warnings and/or errors will result in an error/warning file being generated an put on the ftp server accessible to its reporter. The update is staged providing a consistent view on all data.
