### ISSUE TITLE
DocumentId and version in accumulated error list

### ISSUE THREAD

**Issue by cjonigkeit-csc** [scandihealth/lpr3-docs#42]
Quoting @RasmusThernoe from #34 

> At the meeting on the 7th of February I raised the issue regarding information about SetId, DocumentId and Version in the JSON format.
> 
> In the reply I was told that it will be difficult to state the DocumentId and Version. I did not understand why since I perceive the DocumentId as a message id and every error at the accumulated error list must be caused by a specific message to LPR3. Could you please explain?
> 
> The document id and version will be important for our debugging and it is part of the XDR response.

**Comment by cjonigkeit-csc** [comment]
The reason why it is impossible to state a single document as the source of an error is that the function **f** from the set of **requests** to the set of **_current_ errors and warnings** is _surjective_.

Suppose two requests **a** and **b** to the same encounter.

1. Day 1: The request **a** is sent and gives a warning that will become an error in 2 days unless the encounter is changed.
2. Day 2: The request ** b** is sent and gives a warning that will become an error in 1 day unless the encounter is changed.
3. Day 3: The encounter is in error

Which request resulted in the error? **a** or **b** or both?

**Comment by RasmusThernoe** [comment]
In that case I believe it would be fair to state that last message resulted in the error - hence **b**.

**Comment by RasmusThernoe** [comment]
I still think that it would benefit the debugging process if there is traceability between the message/document id and the errors returned from the accumulated error list.
