### ISSUE TITLE
Track over-time changes of diagnosis

### ISSUE THREAD

**Issue by cjonigkeit-csc** [scandihealth/lpr3-docs#43]
Quoting @DaveSS from #40

> Just to follow up, we’re wondering how the CDA model is able to track over-time changes as a specific diagnosis traverses from one kontakt to another. I included a file with screenshots from the SDS LPR3 Specs and a specific example with questions.
> [OverTimeExample.pdf](https://github.com/scandihealth/lpr3-docs/files/1741897/OverTimeExample.pdf)

**Comment by cjonigkeit-csc** [comment]
We will have to consult with SDS to get an answer.
Hopefully, this is not Pandora's box.

**Comment by DaveSS** [comment]
Has there been any progress on getting this question answered?

**Comment by jonigkeit** [comment]
DXC has suggested a simplification of the logic, requiring every cancer observation organizer (canceranmeldelse) to be complete within 30 days of the specific cancer condition is observed.

The issue is still with SDS.

**Comment by jonigkeit** [comment]
While it is feasible to write a rule enforcing the current logic as described in section 10.4.1.3 of the Indberetningsvejledning, validation and thereby execution does have a significant impact of on processing time on all IHE XDR request, as all encounters of transitively touched episode of care elements, including the encounters' conditions and observation organizers have potentially be revalidated.

**Comment by DaveSS** [comment]
We are still waiting on the resolution of this issue. Specifically, we are worried about the implication the simplification of the logic proposed by DXC would have on systems reporting data.

Making the change “per kontakt” may not make sense for certain departments. For example, the full set of cancer information may not be available during the first visit with a patient but may become clear in a future visit – should the first responsible department also fill this information out?

Making the requirement “per kontakt” also leaves a lot of duplicative data in DXC’s system that may not match up (which Kontakt should be treated as the source of truth?). Each kontakt would have 30 days to meet the requirements, but the 1st department is still relying on other departments (future visits) to fill out information for their requirements to be met.

Please let us know the current status of this issue.

**Comment by jonigkeit** [comment]
Having passed the deadline for changes the requirement has been implemented exactly as set forth in the Indberetningsvejledningen.
