### ISSUE TITLE
Unable to get certificate from dom

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#44]
Hello again,

After implementing DGWS and sending a message to one of the test services we got the following SOAP fault "Unable to get certificate from dom".

I have attached the full HTTP message we are trying to sent to you.
[http_post_request2.txt](https://github.com/scandihealth/lpr3-docs/files/1744479/http_post_request2.txt)

I suspect the problem is we are sending all binary values as HTTP attachment (and use XML Include as a reference to the attachment) instead of converting the values with BASE64 and insert the value directly into the XML. If this is the case, I want to ask if this is something you are going to support?

**Comment by jonigkeit** [comment]
At first glance your request looks right.
It looks like to be a bug in a library used by the SOSI library that does not support MTOM.

**Comment by cjonigkeit-csc** [comment]
There are currently no plans to support MTOM besides the documents themselves.

**Comment by cjonigkeit-csc** [comment]
If you would like to have a general support for MTOM you can create an enhancement request.

**Comment by MartinHylleberg** [comment]
We will start looking into this issue. If need be a new issue will be created.

**Comment by cjonigkeit-csc** [comment]
The problem is not missing XOP/MTOM on the server but an invalid signature. Most likely due to changing (pretty printing) the Assertion after signing.
