### ISSUE TITLE
Question about HsuidHeader segment

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#45]
Hi,

Do you have some documentation about the HsuidHeader segment and what fields you are going to use?

**Comment by jkiddo** [comment]
Documentation on HSUID: https://www.nspop.dk/download/attachments/39942568/IFS0018%20Healthcare%20Service%20User%20Identification%20Header.docx?version=1&modificationDate=1459240284254&api=v2 (authored by Systematic)

Fields being used in LPR3:
nsi:SystemOwnerName
nsi:SystemName
nsi:SystemVersion
nsi:OrgResponsibleName
nsi:OrgUsingID with sorcode

**Comment by JacobBangSSE** [comment]
Thanks, just what I was looking.
