### ISSUE TITLE
production versus validation LPR3 submissions

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#47]
Are you planning to have 2 different XDR endpoints for validation and production submissions, or will there be some SOAP element added to determine which service an XDR submission is being submitted to?

**Comment by jonigkeit** [comment]
The are three different endpoints 
 * validate only
 * save if no errors
 * save if no static errors

**Comment by DaveSS** [comment]
Just to be clear. I am asking about the production submission setup once LPR3 goes live (not the current test configurations.) So for the production system, we can expect the same set of 3 endpoints in order to do validation and support either the asynchronous or synchronous submission workflow, depending on which method we choose? I just want o make sure our design is based on the configuration that will be used after LPR3 goes live.

Thanks for all the help.

**Comment by cjonigkeit-csc** [comment]
Absolutely

The will be three distinct endpoints, also in production.
