### ISSUE TITLE
WSDL for service

### ISSUE THREAD

**Issue by MartinHylleberg** [scandihealth/lpr3-docs#5]
I assume that there will be a final WSDL available once the test service endpoint is made available in January. 
Will there be a beta/alpha version that can be used to make initial development against before this?

**Comment by jkiddo-dxc** [comment]
Under [](https://scandihealth.github.io/lpr3-docs/links/index.html), you will find a link pointing to [](https://github.com/scandihealth/lpr3-docs/raw/master/schema.definitions.zip)

**Comment by MartinHylleberg** [comment]
Thank you, I had missed that :)

A follow up question in regard to this: The WSDL specifies the use of SOAP 1.1. Is it possible to use SOAP 1.2 instead?

**Comment by jkiddo-dxc** [comment]
We'll look into it

**Comment by jkiddo-dxc** [comment]
See 80edc3c4656d599fbf9bb1666c1dfef15d18c434 - does it suit your needs @MartinHylleberg?

**Comment by MartinHylleberg** [comment]
Sorry for the late reply. Yes, this was exactly the need we had. Thanks for the quick response!
