### ISSUE TITLE
The system is not authorized

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#52]
Hello again,

I gets the following error now which seems to indicate that out CVR number is not authorized to access PatientHealthcareValidateReportingService test service:

```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <env:Header xmlns:env="http://www.w3.org/2003/05/soap-envelope"/>
   <soap:Body>
      <soap:Fault>
         <soap:Code>
            <soap:Value>soap:Receiver</soap:Value>
            <soap:Subcode>
               <soap:Value>soap:Server</soap:Value>
            </soap:Subcode>
         </soap:Code>
         <soap:Reason>
            <soap:Text xml:lang="en">The system is not authorized (cvrnr = 7883441278834412).</soap:Text>
         </soap:Reason>
         <soap:Detail>
            <medcom:FaultCode xmlns:medcom="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd">not_authorized</medcom:FaultCode>
         </soap:Detail>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>
```

I can't seem to find any information about a whitelist or how to be authorized. Also it seems kinda strange that the error message returns "cvrnr = 7883441278834412" when the CVR in the the sending message is defined with:

```xml
<saml:NameID Format="medcom:cvrnumber">78834412</saml:NameID>
```

and:
```xml
<saml:Attribute Name="medcom:CareProviderID" NameFormat="medcom:cvrnumber"><saml:AttributeValue>78834412</saml:AttributeValue>
```

**Comment by cjonigkeit-csc** [comment]
The error seems odd.

**Comment by cjonigkeit-csc** [comment]
**78834412** has not been registered with DXC as a reporting authority.
However **29190925** Region Midtjylland is.

**Comment by cjonigkeit-csc** [comment]
If you like **78834412** to be registered as a reporting authority please submit the LPR3 registration form.

**Comment by RasmusThernoe** [comment]
Any updates on this one? We need 78834412 as a reporting authority for the LPR3 test service.

**Comment by cjonigkeit-csc** [comment]
SDS has instructed us create you as a processor for Region Midtjylland.
You should have access now.

**Comment by cjonigkeit-csc** [comment]
We have uploaded the [LPR3 registration form](https://github.com/scandihealth/lpr3-docs/blob/master/src/res/Oprettelse%20af%20databehandler%20for%20indberetter%20til%20Landspatientregisteret.docx?raw=true) from the project management collateral to GitHub as well.

**Comment by JacobBangSSE** [comment]
I have verified we have access now.
