### ISSUE TITLE
id/@root for UUID

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#54]
When validating LPR3 documents, most of the id/@root values for UUIDs are specified to be the setId/@root value thoughout the document. The DK External Episode Of Care Marker Act (1.2.208.176.7.1.10.98) still required that the root="1.2.208.176.7.1.2.1". Should this be changed to be the setId/@root like all other id/@root values in the LPR3?

**Comment by jonigkeit** [comment]
Yes, that is an error.
