### ISSUE TITLE
Durable identifier on Episode of Care Marker

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#55]
On ArtDecor the Episode of Care Marker Act has a durable identifier. 
On ArtDecor the Encounter Reason Act does not have a durable identifier.
Why?

**Comment by jonigkeit** [comment]
See #54

**Comment by RasmusThernoe** [comment]
How is this a duplicate of issue #54? 

Issue #54 considers root ids.

Issue #55 is about the Encounter Reason Act not even having a durable identifier and the Episode of Care Marker Act having a durable identifier. Nothing about root ids.

Why this difference?

**Comment by cjonigkeit-csc** [comment]
Nothing but the encompassing encounter is referencing an encounter reason act.

**Comment by RasmusThernoe** [comment]
Thanks for elaborating.

I the case that we need to report an Observation Organizer triggered by an encounter reason we should use the Encounter Act durable identifier - in template 1.2.208.176.7.1.10.77?

**Comment by jkiddo** [comment]
yes
