### ISSUE TITLE
Error levels bundled?

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#56]
At the technical workshop the error levels were explained as gates - hence only one error level in each response. The interface specification on GitHub states:

Errors in submitted documents can be found at any of the levels stated above. If a document fails to meet level 1, no further processing will be conducted and a report will be returned stating the errors on level 1 in ebXML-format as used in IHE XDR. **Errors found at level 2 and level 3 will be bundled and both can be present in the same response**.

That is not consistent.

**Comment by jkiddo** [comment]
Thanks for pointing out the issue. Feel free to create a pull request or wait for us to update the documentation
