### ISSUE TITLE
codeContext in RegistryErrorList does not follow the specification

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#57]
We got the following error message back when calling the PatientHealthcareValidateReportingService service:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ns2:RegistryResponse xmlns="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns4="urn:ihe:iti:xds-b:2007" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns6="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns8="http://www.w3.org/2000/09/xmldsig#" xmlns:ns7="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns9="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:ns11="http://www.nsi.dk/hsuid/2016/08/hsuid-1.1.xsd" xmlns:ns10="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd" xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:soap="http://www.w3.org/2003/05/soap-envelope" status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure">
	<ns2:RegistryErrorList highestSeverity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error">
		<ns2:RegistryError codeContext="The submission set must have an auhtorInstitution." errorCode="InvalidDocumentContent" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"/>
	</ns2:RegistryErrorList>
</ns2:RegistryResponse>
```

According to:
https://scandihealth.github.io/lpr3-docs/aspects/index.html#what-rules-apply-and-what-errors-can-be-reported-and-how

The format of the "codeContext" is not valid because there is no "|||" in the message:

> The value of codeContext is split into two mandatory segments **separated by |||** having the values \<validation type\>|||\<validation text\>. \<validation type\> can be any of the following XSD, SCHEMATRON, BUSINESS_RULE. \<validation text\> contains an explanation of what has been violated in technical terms.

I have attached the CDA document here:
[82dbd0f5-e451-4cae-b1e2-6c24a4728979.zip](https://github.com/scandihealth/lpr3-docs/files/1793169/82dbd0f5-e451-4cae-b1e2-6c24a4728979.zip)

EDIT:
I also think there is a spelling error in the error message: "auhtorInstitution"

**Comment by jkiddo** [comment]
Please provide your submission as well

**Comment by jkiddo** [comment]
https://scandihealth.github.io/lpr3-docs/aspects/index.html#what-rules-apply-and-what-errors-can-be-reported-and-how primarily describes the errors that occur in the documents. The error that you are referring to sounds to be related to the submission set

**Comment by JacobBangSSE** [comment]
So you are saying we should not expect the "codeContext" field to always follow the rules from the spec?

I can't seem to find any information about the authorInstitution field in either ART Decor or the examples in the spec or the WSDL/XDR files.

Here is the TCP dump:
[ncat_6.zip](https://github.com/scandihealth/lpr3-docs/files/1793285/ncat_6.zip)

**Comment by jkiddo** [comment]
What I'm saying is that the errors stated in https://scandihealth.github.io/lpr3-docs/aspects/index.html#what-rules-apply-and-what-errors-can-be-reported-and-how describes the custom errors in this XDR service that holds for the content of the CDA documents. Besides those errors, you can expect the errors that applies for standard IHE XDS/XDR repositories and registries for ITI-41. As stated in the documentation, LPR is implemented as an IHE XDR service that uses XDS MS as metadata set for submissions and document entries.

May I suggest that you have a look at the https://scandihealth.github.io/lpr3-docs/links/index.html where you can find links to IHE material. You'll find a table containing required metadata for document entries and submission sets in Table 4.3.1-3: Sending Actor Metadata Attribute Optionality, IHE ITI TF-3

**Comment by RasmusThernoe** [comment]
The examples in the LPR3 interface specification does not contain an authorInstitution - as Jacob mentions in the comment above.

If the authorInstitution is mandatory shouldn't it be present in the examples in the LPR3 interface specification (https://scandihealth.github.io/lpr3-docs/examples/index.html)?

In the examples the registry package is just empty: <ns4:RegistryPackage/>

**Comment by jkiddo** [comment]
Right ... it could and it should. The example currently does not contain authorInstitution and more elements could be missing in the examples.

**Comment by RasmusThernoe** [comment]
From the standard: "At least an authorPerson, authorTelecommunication or authorInstitution sub-attribute shall be present when the author attribute is included in the metadata."

The cardinality of author is "Required if Known". 

How are we as reporters suppose to know how this optionality has been profiled by the LPR3 interface? The examples do not reflect this.

**Comment by jkiddo** [comment]
It's stated in section [IHE XDR](https://scandihealth.github.io/lpr3-docs/aspects/index.html#ihe-xdr). We'll update the examples

**Comment by jkiddo** [comment]
The cardinality of author and in particular authorInstitution is *mandatory* as stated in "XDS Metadata for Documents Sharing, Danish profile", Table 4. Even if it would be "required if known" all reporting authorities are authorInstitutions and as such it is known and must be sent.

**Comment by RasmusThernoe** [comment]
A valid example in the LPR3 interface specification would be very helpful.
The current invalid examples in the LPR3 interface specification could be misinterpreted - false safety.

**Comment by jkiddo** [comment]
We'll fix it ASAP

**Comment by jkiddo** [comment]
Should be fixed with 37e068fd8de8947008006ed593d4b1ffdc6af629 - feel free to close the issue if you find the fix satisfying

**Comment by JacobBangSSE** [comment]
Is this valid (from the example)?
```xml
<Slot name="authorInstitution">
  <ValueList>
    <Value>25469364</Value>
  </ValueList>
</Slot>
```
According to [Danish Metadata profile](http://svn.medcom.dk/svn/drafts/Standarder/IHE/DK_profil_metadata/Metadata-v095.docx) the format of this field is XON and should contain the following:

> This specification restricts the coding to include the following fields:
> * XON.1 - Organization Name (displayName)
> * XON.6.2 - Assigning Authority (codeSystem)
> * XON.10 Organization Identifier (code)
> 
> No other fields shall be specified.

And comes with this example:

```xml
<rim:Slot name="authorInstitution">
    <rim:ValueList>
        <rim:Value>Odense Universitetshospital – Svendborg Sygehus^^^^^&
             1.2.208.176.1.1&ISO^^^^88878685</rim:Value>
    </rim:ValueList>
</rim:Slot>
```

**Comment by RasmusThernoe** [comment]
Any updates on this one? 
The example in the LPR3 interface specification and the "Danist Metadata Profile" seems to disagree.
What is implemented in the LPR3 test service?

**Comment by jkiddo** [comment]
@RasmusThernoe @JacobBangSSE - you guys are right - the current example is incorrect. It will be updated shortly
