### ISSUE TITLE
Patient Role options

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#58]
There were originally  2 options for the recordTarget/patientRole element in LPR3. One for the case when we have the cpr-nummer for the patient, and one where we did not and the patient needed to be alternately identified. I now see a third option (1.2.208.176.7.1.10.133 DK Civil Registration System And Alternatively Identified Patient Role). Is there a use case where this is supposed to be used in place of the 1.2.208.176.7.1.10.106 DK Civil Registration System Identified Patient Role element? My understanding was that if we had the cpr-nummer, we should use 1.2.208.176.7.1.10.106, otherwise we should use the 1.2.208.176.7.1.10.107 (for patient's that need to be alternately identified.)

**Comment by jonigkeit** [comment]
The use of 1.2.208.176.7.1.10.133 is voluntary.

Suppose you have patient that has a civil registration system identifier, however the clinical staff can not obtain the identifier, e.g. patient unconscious or a major incident with many injured. A reporting authority may report episodes of care using ad-hoc identifiers. After some time the clinical staff obtains the civil registration system identifier. The reporting authority can now link all previous data reported data that used the ad-hoc identifier to all data using the civil registration system identifier by submitting 1.2.208.176.7.1.10.133.
