### ISSUE TITLE
Assinging Authority for setID?

### ISSUE THREAD

**Issue by graugaard** [scandihealth/lpr3-docs#6]
There is a discrepancy between the example provided and the specification (See DKEpisodeOfCareSummariesDocument in [http://art-decor.org/art-decor/decor-templates--lpr-](http://art-decor.org/art-decor/decor-templates--lpr-)).

In the example, the assigning authority is not present for the setId attribute, but the specification requires one. What should it be?

**Comment by jkiddo-dxc** [comment]
Please provide a link to the example

**Comment by graugaard** [comment]
[http://art-decor.org/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.71&effectiveDate=2017-09-13T00:00:00&language=en-US](http://art-decor.org/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.71&effectiveDate=2017-09-13T00:00:00&language=en-US)

In both examples presented here, they lack the assigning authority under the setId.

**Comment by jkiddo** [comment]
Right ... We'll get those updated. Until then, have a look at the examples on https://scandihealth.github.io/lpr3-docs/examples/index.html#examples-from-selected-scenarios
