### ISSUE TITLE
Art-decor template export

### ISSUE THREAD

**Issue by kdjohansson** [scandihealth/lpr3-docs#60]
Is there a way to export Art-decor template to an XML schema (XSD)?

**Comment by jonigkeit** [comment]
The way the CDA standard is constructed, makes it almost useless to create XSD schemas for specific templates.

A CDA template is a profiling of a CDA Document, CDA Header, CDA Section, or CDA Entry. These are defined by CDA R2. The CDA R2 web release contains a XSD schema for CDA. [The technical documentation for the Danish National Patient Register links to it](https://scandihealth.github.io/lpr3-docs/links/index.html).

[DXC provides Schematron definitions for integrations](https://scandihealth.github.io/lpr3-docs/developmentresources/index.html) to use _as is_.
