### ISSUE TITLE
STS Request example

### ISSUE THREAD

**Issue by rsagner** [scandihealth/lpr3-docs#61]
Hi!

We are trying to sign an ID card (later be used with the LPR3 services) using the STS service: http://test2.ekstern-test.nspop.dk:8080/sts/services/NewSecurityTokenService and get the error: Insufficient Digest Elements: Signature could not be validated

I have sent a question to NSPOP but want to ask if anyone have an example of the full HTTP POST request that is needed to sign an id card to be used with the LPR3 service?

The examples on NSPOP are not complete (missing the id card/assertion) :-(

**Comment by jonigkeit** [comment]
Issues regarding STS are out of scope regarding LPR.

**Comment by rsagner** [comment]
For any one interested I found the issue. The canonicalization algorithm was wrong. Based on the example of id card in http://svn.medcom.dk/svn/drafts/DGWS/Den%20Gode%20Webservice_1.0.pdf I used  "http://www.w3.org/TR/2001/REC-xml-c14n-20010315" but that gave the error "Insufficient Digest Elements: Signature could not be validated". Changing to "http://www.w3.org/2001/10/xml-exc-c14n#" solved it.
