### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#62]
Is it possible to get a more detailed error message when we try send the following HTTP package:
[ncat_9.zip](https://github.com/scandihealth/lpr3-docs/files/1803048/ncat_9.zip)

We gets the following error:
```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <env:Header xmlns:env="http://www.w3.org/2003/05/soap-envelope"/>
   <soap:Body>
      <soap:Fault>
         <soap:Code>
            <soap:Value>soap:Receiver</soap:Value>
         </soap:Code>
         <soap:Reason>
            <soap:Text xml:lang="en">java.lang.NullPointerException</soap:Text>
         </soap:Reason>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>
```

**Comment by jonigkeit** [comment]
Your patient is invalid.

**Comment by jonigkeit** [comment]
We suggest that you use the official XSD from [CDA R2](http://www.hl7.org/implement/standards/product_brief.cfm?product_id=7) and the [provided schematron definitions](https://scandihealth.github.io/lpr3-docs/developmentresources/index.html#schematron) to validate your cda documents, before sending them to the XDR endpoints.
