### ISSUE TITLE
Error in Schematron validation logic in relation to versionNumber

### ISSUE THREAD

**Issue by RolandPedersenSSE** [scandihealth/lpr3-docs#64]
There is an error in the schematron validation in relation to version number.

The error message states that: 

(DKRelatedDocument): versionNumber must be **less than** than /versionNumber" 
where versionNumber is the one in /ClinicalDocument/relatedDocument/parentDocument and /versionNumber is the one in /ClinicalDocument
But the rule states this: "versionNumber >= /versionNumber" which makes no sense. It should be this:
"versionNumber **<** /versionNumber
Which also fits with what the error message says.

This is actually an error in art-decor: [DK RelatedDocument](http://art-decor.org/art-decor/decor-templates--lpr-?id=1.2.208.176.7.1.10.111&effectiveDate=2017-12-22T00:00:00)

Validation output:
```
Text: (DKRelatedDocument): versionNumber must be less than than /versionNumber
Test: versionNumber >= /versionNumber
See:
Location: /*:ClinicalDocument/*:relatedDocument/*:parentDocument
```

**Comment by cjonigkeit-csc** [comment]
This has been fixed a long time ago.
See the [schematron files](https://github.com/scandihealth/lpr3-cda/tree/unstable) and [DK RelatedDocument](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?id=1.2.208.176.7.1.10.111&effectiveDate=2017-11-11T00:00:00).

**Comment by jonigkeit** [comment]
@RolandPedersenSSE please close this issue if you have no further comments.
