### ISSUE TITLE
DKEpisodeOfCareAct missing mandatory information

### ISSUE THREAD

**Issue by filippo91** [scandihealth/lpr3-docs#7]
Working with the examples provided in [this ](http://art-decor.org/art-decor/decor-templates--lpr) webpage, I am not able to find the responsible organization -
 SOR code - for an episode of care even though, looking at the HL7 v3 standard, it should be mandatory.

**Comment by jkiddo** [comment]
We're looking into it. Will be fixed in next release

**Comment by cjonigkeit-csc** [comment]
Fixed in preproduction [DK EpisodeOfCareAct](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.80).
Waiting deployment to production.
