### ISSUE TITLE
java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#70]
We get the following (not very specific) message back from the LPR3 PatientHealthcareValidateReportingService:
```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <env:Header xmlns:env="http://www.w3.org/2003/05/soap-envelope"/>
   <soap:Body>
      <soap:Fault>
         <soap:Code>
            <soap:Value>soap:Receiver</soap:Value>
         </soap:Code>
         <soap:Reason>
            <soap:Text xml:lang="en">java.lang.NumberFormatException: For input string: ""</soap:Text>
         </soap:Reason>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>
```

When we are trying to send the following CDA document:
[1521472645299@example.zip](https://github.com/scandihealth/lpr3-docs/files/1829230/1521472645299.example.zip)

With the following Envelope:
[Envelope.zip](https://github.com/scandihealth/lpr3-docs/files/1829239/Envelope.zip)

We have checked the CDA document against the schematron files but got no errors. Can you give us some details where the error are?

**Comment by JacobBangSSE** [comment]
What is the status of this issue?

**Comment by cjonigkeit-csc** [comment]
There are multiple issues with your ClinicalDocument.
 1. You have invalid extensions, such as "HARDCODED: 12345679"
 2. You have invalid/unrecognized combinations of templateIds, such as
```xml
<templateId root="1.2.208.176.7.1.10.51"/>
<templateId root="2.16.840.1.113883.10.12.301"/>
```
 3. You have invalid/unrecognized fields, such as
```
<scopingEntity classCode="ORG">
  <typeId assigningAuthorityName="SOR" extension="16131000016008" 													root="2.16.840.1.113883.1.3"/>
</scopingEntity>
```

These are the issues I observed by taking a glance at your ClinicalDocument. There may be more.

**Comment by jkiddo** [comment]
For basic CDA validation there are numerous services available online. One way of doing such initial validation can be done like the following:

curl -X POST --header "Content-type:application/xml" --data @cda.xml http://cda.medcom.dk/service/CDA/validate/NONE

**Comment by JacobBangSSE** [comment]
Thanks for the hint about the CDA validation service from Medcom which gives us a lot of useful detailed error messages. I can see this service has a lot of additional rules compare to the rules from (I guess the Medcom service validates against basic CDA rules and the schematron files is extra rules we should also validate against):
https://github.com/scandihealth/lpr3-cda/blob/unstable/schematron.unstable.zip

I do think the LPR3 endpoint should never return a vague error message like "NumberFormatException" without any reference to what number it tries to validate and therefore this should be reported as an error.

Also there could be a schematron rule for the specific case of validating the CVR number so it cannot contains letters.  That would give a more helpful error message instead of the "NumberFormatException".

**Comment by jonigkeit** [comment]
@JacobBangSSE if you have no further comment please close this issue.
