### ISSUE TITLE
Patient segment for patients with valid CPR

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#74]
We have a question about an possible inconsistency between the provided schematron files from you and the medcom CDA validation service. 

Art-decor for templateId "1.2.208.176.7.1.10.106" describes that the only required field are an "id" which describes the CPR number. This makes sense since all other information about the patient can be found in the CPR registry.

But if we try validate a CDA document with the medcom CDA validation service which has this recordTarget:
```xml
<recordTarget>
	<templateId root="1.2.208.176.7.1.10.101"/>
	<templateId root="2.16.840.1.113883.10.12.101"/>
	<patientRole classCode="PAT">
		<templateId root="1.2.208.176.7.1.10.106"/>
		<id root="1.2.208.176.1.2" extension="1010101010" assigningAuthorityName="CPR"/>
	</patientRole>
</recordTarget>
```
We gets the following from the medcom CDA validation service:
```json
{
  "infos": [
    
  ],
  "warnings": [
    
  ],
  "errors": [
    {
      "message": "ERROR :  This condition is not verified : If patientRole has not a null of flavor and its enclosing recordTarget has not a null of flavor,  it SHALL have a patient entity, or a providerOrganization (RMIM-080)",
      "location": "\/ClinicalDocument\/recordTarget[0]\/patientRole",
      "errorCode": "cdabasic-PatientRoleSpec-rmim080"
    }
  ]
}
```
If we instead specify an empty patient segment:
```xml
<recordTarget>
	<templateId root="1.2.208.176.7.1.10.101"/>
	<templateId root="2.16.840.1.113883.10.12.101"/>
	<patientRole classCode="PAT">
		<templateId root="1.2.208.176.7.1.10.106"/>
		<id root="1.2.208.176.1.2" extension="1010101010" assigningAuthorityName="CPR"/>
		<patient classCode="PSN">
		</patient>
	</patientRole>
</recordTarget>
```
We got no errors back from the medcom CDA validation service. In both cases we does not get any schematron errors from the provided schematron rules from:
https://github.com/scandihealth/lpr3-cda/blob/unstable/schematron.unstable.zip

**Comment by jonigkeit** [comment]
RMIM-080 is not expressed by Schematron.  See https://gazelle.ihe.net/cda/cda-basic-req.pdf
We will update the example.

**Comment by jonigkeit** [comment]
We will file an issue with art decor about the missing basic constraint.

**Comment by jonigkeit** [comment]
Keep in mind that the interface expects valid CDA R2 and that the schematron files are provided *as is*. The current implementation may be more lenient that CDA R2, but that can change as we implement additional requirement checks.

**Comment by jonigkeit** [comment]
If we carry out additional checks you will be notified in accordance with the change management process.

**Comment by jkiddo** [comment]
@JacobBangSSE - would you like to address this enhancement to the steering committee?

**Comment by JacobBangSSE** [comment]
We have no plans of addressing this to the steering committee.

**Comment by jonigkeit** [comment]
@JacobBangSSE if you have no further comments, please close this issue.
