### ISSUE TITLE
Link between submitted document and response

### ISSUE THREAD

**Issue by MartinHylleberg** [scandihealth/lpr3-docs#8]
The examples supplied at https://scandihealth.github.io/lpr3-docs/examples/index.html specify a document being sent and a sample response for a valid document.

From the examples I am unable to find a link between the request and the response (I cannot find a value that is identical in the 2 documents).

Could you specify where the link between the request document and the response resides?

**Comment by jkiddo** [comment]
We'll look into it

**Comment by jkiddo** [comment]
See f0e2b4a78d0fe0475d76526b0166494a3f3226f5 - result is on https://scandihealth.github.io/lpr3-docs/examples/index.html#sample-request-using-mtomxop and https://scandihealth.github.io/lpr3-docs/examples/index.html#sample-response-with-an-invalid-document

**Comment by MartinHylleberg** [comment]
Can we reopen this one? We are a bit confused by the update:

The updated documents seems to contain some errors and does not actually answer the question:

- The valid response was removed from the samples. Please readd this as it helps when trying to implement the correct case.
- The new "invalid response" sample is in itself invalid, as according to the documentation we can never get both a XSD error and a Schematron error in the same response. 

The samples that were provided earlier actually served the purpose, as they were very simple to read. The only issue we had was that we were unable to relate any id in the request sample with an id in the response sample. (be it the document itself or the header information).

**Comment by jkiddo** [comment]
- Valid response added
- It is correct that schematron and xsd errors cannot be present at the same time. It is only included in the samples for the sake of illustrating how the errors are presented
