### ISSUE TITLE
Unable to get certificate from dom (MTOM related)

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#80]
After the latest release I wanted to test if MTOM now works for the DGWS part of the Envelope. Unfortunately this does not seem to be the case since I gets the following error:
```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <env:Header xmlns:env="http://www.w3.org/2003/05/soap-envelope"/>
   <soap:Body>
      <soap:Fault>
         <soap:Code>
            <soap:Value>soap:Receiver</soap:Value>
         </soap:Code>
         <soap:Reason>
            <soap:Text xml:lang="en">Unable to get certificate from dom</soap:Text>
         </soap:Reason>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>
```

I have attached the SoapUI project I am using to test:
[lpr3-soapui-project.zip](https://github.com/scandihealth/lpr3-docs/files/1880850/lpr3-soapui-project.zip)

**Comment by jonigkeit** [comment]
Your request is invalid.

```
Content-Type: application/octet-stream; name="1522937365262@example.org"
Content-Transfer-Encoding: binary
Content-ID: <1522937365263@example.org>
Content-Disposition: attachment; name="1522937365262@example.org"; filename="1522937365262@example.org"
```

**Comment by jonigkeit** [comment]
Directly on the wire.

**Comment by JacobBangSSE** [comment]
Ok, when you are using the SoapUI project?

**Comment by jonigkeit** [comment]
In our server logs, when you submitted the document.

**Comment by jonigkeit** [comment]
[github-80.log](https://github.com/scandihealth/lpr3-docs/files/1889164/github-80.log)

**Comment by jonigkeit** [comment]
The problem is that you are not in compliance with [XML-binary Optimized Packaging
W3C Recommendation 25 January 2005](https://www.w3.org/TR/2005/REC-xop10-20050125/#interpreting_xop_packages)
Specifically:
> Part metadata is reflected in MIME header fields. Specifically, the URI used in the value of an href attribute information item on a xop:Include element information item contains a URI that uses the 'cid:' scheme (see [RFC 2392]), so the corresponding MIME part MUST have a Content-ID header field (see [RFC 2387] with a corresponding field-value.

**Comment by jonigkeit** [comment]
@JacobBangSSE if you have no further comments please close this issue.

**Comment by JacobBangSSE** [comment]
Sorry for the delay but we finally got MTOM working on our integration platform. I am closing this issue. Thanks for you time. :)
