### ISSUE TITLE
Validation errors in examples

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#81]
I have checked the examples there are linked in the button of the following page by sending each of them to PatientHealthcareValidateReportingService:
https://scandihealth.github.io/lpr3-docs/examples/index.html

All of the examples does contains one or more errors. The only example I did not include in the list is "Indberetning kun med forløbselement" which already has its own issue #73.

Example | Number of errors | Link to respond
------------ | ------------ | -------------
[Indberetning af sletning af procedure uden kontakt](https://scandihealth.github.io/lpr3-docs/examples/Removal.Procedure.xml) | 8 SCHEMATRON | [Link](https://github.com/scandihealth/lpr3-docs/files/1887486/Indberetning.af.sletning.af.procedure.uden.kontakt.txt)
[Indberetning af sletning af forløbselement](https://scandihealth.github.io/lpr3-docs/examples/Removal.EpisodeOfCare.xml) | 8 SCHEMATRON | [Link](https://github.com/scandihealth/lpr3-docs/files/1887489/Indberetning.af.sletning.af.forlobselement.txt)
[Indberetning af sletning af kontaktelement](https://scandihealth.github.io/lpr3-docs/examples/Removal.Encounter.xml) | 7 SCHEMATRON | [Link](https://github.com/scandihealth/lpr3-docs/files/1887491/Indberetning.af.sletning.af.kontaktelement.txt)
[Indberetning af procedure uden kontakt med reference til forløbselement](https://scandihealth.github.io/lpr3-docs/examples/Procedure.ReferenceToEpisodeOfCare.xml) | 13 SCHEMATRON | [Link](https://github.com/scandihealth/lpr3-docs/files/1887497/Indberetning.af.procedure.uden.kontakt.med.reference.til.forlobselement.txt)
[Indberetning af kontakt med reference til forløbselement og hvor der i samme besked er en resultatindberetning af typen ”Fødselsanmeldelse - mor” på kontakten med flere](https://scandihealth.github.io/lpr3-docs/examples/Encounter.ReferenceToEpisodeOfCare.Results-Mother.xml) | 18 SCHEMATRON | [Link](https://github.com/scandihealth/lpr3-docs/files/1887501/Indberetning.af.kontakt.med.reference.til.forlobselement.og.hvor.der.i.samme.besked.er.en.resultatindberetning.af.typen.Fodselsanmeldelse.-.mor.pa.kontakten.med.flere.txt)
[Indberetning af kontakt med reference til forløbselement og hvor der i samme besked er en resultatindberetning af typen ”Neonatal hørescreening” på kontakten med flere resultater](https://scandihealth.github.io/lpr3-docs/examples/Encounter.ReferenceToEpisodeOfCare.Results-Hearingtests.xml) | 16 SCHEMATRON | [Link](https://github.com/scandihealth/lpr3-docs/files/1887505/Indberetning.af.kontakt.med.reference.til.forlobselement.og.hvor.der.i.samme.besked.er.en.resultatindberetning.af.typen.Neonatal.horescreening.pa.kontakten.med.flere.resultater.txt)
[Indberetning af kontakt med reference til forløbselement og hvor der i samme besked er en resultatindberetning af typen ”Beslutning vedrørende personligt alarm- og pejlesystem” på kontakten med flere resultater](https://scandihealth.github.io/lpr3-docs/examples/Encounter.ReferenceToEpisodeOfCare.Results-Decision.Alarm.xml) | 19 SCHEMATRON | [Link](https://github.com/scandihealth/lpr3-docs/files/1887507/Indberetning.af.kontakt.med.reference.til.forlobselement.og.hvor.der.i.samme.besked.er.en.resultatindberetning.af.typen.Beslutning.vedrorende.personligt.alarm-.og.pejlesystem.pa.kontakten.med.flere.resultater.txt)
[Indberetning af kontakt med reference til forløbselement og hvor der i samme besked er en resultatindberetning af typen ”Fødselsanmeldelse - barn” på kontakten med flere resultater](https://scandihealth.github.io/lpr3-docs/examples/Encounter.ReferenceToEpisodeOfCare.Results-Child.xml) | 17 SCHEMATRON | [Link](https://github.com/scandihealth/lpr3-docs/files/1887510/Indberetning.af.kontakt.med.reference.til.forlobselement.og.hvor.der.i.samme.besked.er.en.resultatindberetning.af.typen.Fodselsanmeldelse.-.barn.pa.kontakten.med.flere.resultater.txt)
[Indberetning af kontakt med reference til forløbselement og hvor der i samme besked er en resultatindberetning af typen ”Canceranmeldelse” på kontakten med flere resultater](https://scandihealth.github.io/lpr3-docs/examples/Encounter.ReferenceToEpisodeOfCare.Results-Cancer.xml) | 19 SCHEMATRON | [Link](https://github.com/scandihealth/lpr3-docs/files/1887513/Indberetning.af.kontakt.med.reference.til.forlobselement.og.hvor.der.i.samme.besked.er.en.resultatindberetning.af.typen.Canceranmeldelse.pa.kontakten.med.flere.resultater.txt)
[Indberetning af kontakt med reference til forløbselement og hvor der i samme besked er en resultatindberetning af typen ”Canceranmeldelse” på kontakten med flere resultater](https://scandihealth.github.io/lpr3-docs/examples/Encounter.ReferenceToEpisodeOfCare.Results-Accident.xml) | 18 SCHEMATRON| [Link](https://github.com/scandihealth/lpr3-docs/files/1889068/Indberetning.af.kontakt.med.reference.til.forlobselement.og.hvor.der.i.samme.besked.er.en.resultatindberetning.af.typen.Ulykke.pa.kontakten.med.flere.resultater.txt)
[Indberetning af kontakt med reference til forløbselement og hvor der i samme besked er en resultatindberetning af typen ”Abortoplysninger” på kontakten med flere resultater](https://scandihealth.github.io/lpr3-docs/examples/Encounter.ReferenceToEpisodeOfCare.Results-Abortion.xml) | 18 SCHEMATRON | [Link](https://github.com/scandihealth/lpr3-docs/files/1889079/Indberetning.af.kontakt.med.reference.til.forlobselement.og.hvor.der.i.samme.besked.er.en.resultatindberetning.af.typen.Abortoplysninger.pa.kontakten.med.flere.resultater.txt)
[Indberetning af komplet kontakt med reference til forløbselement og med tilhørende procedurer og diagnoser og til diagnoserne (cancer) hørende metastaser og lokalrecidiv](https://scandihealth.github.io/lpr3-docs/examples/Encounter.ReferenceToEpisodeOfCare.Proceduce.Diagnose-Cancer.xml) | 39 SCHEMATRON | [Link](https://github.com/scandihealth/lpr3-docs/files/1887521/Indberetning.af.komplet.kontakt.med.reference.til.forlobselement.og.med.tilhorende.procedurer.og.diagnoser.og.til.diagnoserne.cancer.horende.metastaser.og.lokalrecidiv.txt)

Also, two of the examples has the same danish title "Indberetning af kontakt med reference til forløbselement og hvor der i samme besked er en resultatindberetning af typen ”Canceranmeldelse” på kontakten med flere resultater". I guess the one of them should have been "Ulykke" instead of "Canceranmeldelse".

**Updated after the fixes in 9bb3922**

**Comment by jkiddo** [comment]
Examples updated 7d7a60ed4b73d60a8b1082476dca6d0c70dec95a

**Comment by JacobBangSSE** [comment]
Looks good.
