### ISSUE TITLE
"transaction rolled back" error when trying to create an episode of care

### ISSUE THREAD

**Issue by RolandPedersenSSE** [scandihealth/lpr3-docs#83]
We are receiving a strange error when trying to create an episode of care and we cannot figure out what is wrong. The creation worked earlier today, so we are a little confused as to why it does not work now.
Also, a better error message would be nice.

The error:
```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <env:Header xmlns:env="http://www.w3.org/2003/05/soap-envelope"/>
   <soap:Body>
      <soap:Fault>
         <soap:Code>
            <soap:Value>soap:Receiver</soap:Value>
         </soap:Code>
         <soap:Reason>
            <soap:Text xml:lang="en">Transaction rolled back</soap:Text>
         </soap:Reason>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>
```
Episode of care clinical document that fails:
[cda-episodeOfCare.zip](https://github.com/scandihealth/lpr3-docs/files/1898973/cda-episodeOfCare.zip)

Envelope:
[Envelope.zip](https://github.com/scandihealth/lpr3-docs/files/1898977/Envelope.zip)

**Comment by RasmusThernoe** [comment]
This one is blocking. Please prioritize.

**Comment by jonigkeit** [comment]
Your request should succeed as of now.

**Comment by RolandPedersenSSE** [comment]
I can confirm that it succeeds now. Thank you for the fix.

**Comment by jonigkeit** [comment]
Sry about the inconvenience
