### ISSUE TITLE
Null Pointer Exception: Updating Encounter

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#88]
Bug in the central solution to return the raw "Null Pointer Exception" to the client.

We got another NullPointerException from PatientHealthcareValidateReportingService:

```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <env:Header xmlns:env="http://www.w3.org/2003/05/soap-envelope"/>
   <soap:Body>
      <soap:Fault>
         <soap:Code>
            <soap:Value>soap:Receiver</soap:Value>
         </soap:Code>
         <soap:Reason>
            <soap:Text xml:lang="en">java.lang.NullPointerException</soap:Text>
         </soap:Reason>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>
```

We are sending the following CDA document:
[TC5-Encounter-Update.zip](https://github.com/scandihealth/lpr3-docs/files/1919825/TC5-Encounter-Update.zip)

**Comment by RasmusThernoe** [comment]
The service returns "Null Pointer Exception" if CDA document is not UTF-8 encoded.

**Comment by jkiddo** [comment]
What is stated in the charset in the Content-Type of your request?

**Comment by RasmusThernoe** [comment]
The charset is UTF-8 and we know that our XML content is not. 
This makes the LPR3 service return a Null Pointer Exception and not an error message.

**Comment by jonigkeit** [comment]
@RasmusThernoe is the webservice not returning an error status, e.g. 4xx or 5xx?

**Comment by RasmusThernoe** [comment]
It returns the SOAP fault above with a null pointer exception. This issue is not blocking.

**Comment by TueCN** [comment]
I cannot reproduce the error with the provided xml file alone.

A SOAP fault is a valid SOAP response.  
I understand specifying `soap:Receiver` in `soap:Code` indicates this is a problem with the server, but we do not consider this issue a notable bug worth chasing, given the nature of the cause: The client specifying one encoding while actually using another encoding.

If you wish this behavior changed please raise the issue in the LPR project steering committee.

**Comment by RasmusThernoe** [comment]
OK,
