### ISSUE TITLE
Searching on 'Vis Fejl' without Episode of Care

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#89]
Searching in the administration client at the list 'Vis Fejl' return a "java.lang.RuntimeException". See attachment.

![sogerudenforlobid](https://user-images.githubusercontent.com/36242392/38874440-599fafbe-4258-11e8-809b-99c4895cd64b.PNG)

**Comment by TueCN** [comment]
@RasmusThernoe are you still experiencing this issue?

I believe we internally found this defect and fixed it, but for some reason this issue was never linked with the internal bug report.

I can not reproduce the error so hopefully you no longer have the issue either.

**Comment by RasmusThernoe** [comment]
@TueCN I have just tried it and it works.

But I also tried searching without an EOC id on the 'Vis indberetninger' and got this:

![image](https://user-images.githubusercontent.com/36242392/39744089-582a4896-52a3-11e8-9676-1c68eeb4290d.png)

**Comment by TueCN** [comment]
I cannot reproduce the problem in the current version of the service. @RasmusThernoe are you  still experiencing this issue? 
 
Please try and clear your cache (Chrome: Open DevTools with F12 -> right click the refresh icon -> click "Empty Cache and Hard Reload")

It is possible you were searching while the system was suffering from a performance problem. We are working on improving search performance for a future release.

**Comment by RasmusThernoe** [comment]
I am no longer experiencing the issue - cannot reproduce.
