### ISSUE TITLE
Generate a durable identifier for the episode of care

### ISSUE THREAD

**Issue by filippo91** [scandihealth/lpr3-docs#9]
I am trying to generate the identifier for the episode of care and I would like to have some clarification on how to create the UUID v5. In particular, how does the SOR identifier fit into this process?

I thought it would be enough to use the namespace and the local unique identifier:
extension = generateUUID5(namespace, identifier);

**Comment by jkiddo** [comment]
The use of UUIDv5 is so that you are able to generate something unique that is namespaced - all under your own control. What you choose as inputs is up to you.

**Comment by jkiddo** [comment]
Here's an example of how you should do it on debian for Episode Of Care:

```bash
#!/bin/bash

EPISODE_OF_CARE_IDENTIFIER_OID=1.2.208.176.7.1.10.80
AUTHOR_SOR_IDENTIFIER=$1
INTERNAL_EPISODE_OF_CARE_UID=$2

CMD='uuid -v5 ns:OID '$EPISODE_OF_CARE_IDENTIFIER_OID
EPISODE_OF_CARE_IDENTIFIER_UUID=`$CMD`
CMD='uuid -v5 '$EPISODE_OF_CARE_IDENTIFIER_UUID' '$AUTHOR_SOR_IDENTIFIER
AUTHOR_SOR_UUID=`$CMD`
CMD='uuid -v5 '$AUTHOR_SOR_UUID' '$INTERNAL_EPISODE_OF_CARE_UID
EPISODE_OF_CARE_UUID=`$CMD`


echo 'EpisodeOfCareIdentifierUUID: '$EPISODE_OF_CARE_IDENTIFIER_UUID
echo 'AuthorSORUUID: '$AUTHOR_SOR_UUID
echo 'EpisodeOfCareUUID: '$EPISODE_OF_CARE_UUID

```

**Comment by cjonigkeit-csc** [comment]
So an durable identifier for an episode of care is created by the following UUID chain.

`uuid(uuid(uuid(6ba7b812-9dad-11d1-80b4-00c04fd430c8, 1.2.208.176.7.1.10.80),[SOR_ID]),[LOCAL_EPISODE_OF_CARE_ID])`

NB: `6ba7b812-9dad-11d1-80b4-00c04fd430c8` is the namespace of OID as defined by [RFC 4122](https://www.ietf.org/rfc/rfc4122.txt) and `uuid(6ba7b812-9dad-11d1-80b4-00c04fd430c8, 1.2.208.176.7.1.10.80)` evaluates to `fe537378-31eb-5036-91da-72ed4eecae10` that you can recognize in the [CDA template for DK Episode Of Care Act](http://art-decor.org/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.80).

The reason for the SOR ID is to avoid id clashes between data providers.
Suppose Region X and Region Y each have an episode of care with the same **local** identifier, but schematically the episodeS of care have no relation with each other at all. By adding the SOR_ID as part of the UUID chain we avoid an UUID clash.
