### ISSUE TITLE
gui-client: "Valideret" always the same as "Starttidspunkt"

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#92]
In the "Vis indberetninger" overview the value of "Valideret" looks to be always the same as "Starttidspunkt" and is not the timestamp for when the "Forløb" was validated. Instead, it looks like it is the start timestamp for the "Forløbselement":
![image](https://user-images.githubusercontent.com/36299108/38932295-0d4f45d4-4316-11e8-9b79-344902cfef75.png)

**Comment by TueCN** [comment]
This is indeed a bug. We will look into it.

**Comment by TueCN** [comment]
This (might) require a database change. Due to prioritization, a fix to this issue might be a few days or weeks away.
