### ISSUE TITLE
"Transaction Rolled Back" when deleting Episode of Care

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#93]
**Bug** in the central solution to return the raw "Transaction rolled back" to the client.

The issue is **blocking** for our current system test of delete flows.

We get a "Transaction Rolled Back" when trying to delete an Episode of Care.

```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <env:Header xmlns:env="http://www.w3.org/2003/05/soap-envelope"/>
   <soap:Body>
      <soap:Fault>
         <soap:Code>
            <soap:Value>soap:Receiver</soap:Value>
         </soap:Code>
         <soap:Reason>
            <soap:Text xml:lang="en">Transaction rolled back</soap:Text>
         </soap:Reason>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>
```
The create EOC file: 
[TC1-EpisodeOfCare-Create-Test2.zip](https://github.com/scandihealth/lpr3-docs/files/1925249/TC1-EpisodeOfCare-Create-Test2.zip)

The delete EOC file: 
[TC8-EpisodeOfCare-Delete-Test2.zip](https://github.com/scandihealth/lpr3-docs/files/1925250/TC8-EpisodeOfCare-Delete-Test2.zip)

**Comment by jonigkeit** [comment]
**Resolution**
Fixed removal logic, extended automated tests.

**Comment by RasmusThernoe** [comment]
Tested OK.
