### ISSUE TITLE
No connection to Accumulated Error List

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#95]
**This issue is blocking.**

In the release note of UL4:
> The LPR3 Accumulated Error List will be generated every 5 minutes for testing purposes and can be found in the sFTP folder: **sftp://lpr2indberet-test.sds.dsdn.dk**

I have tried to connect **sftp://lpr2indberet-test.sds.dsdn.dk** using FileZilla:
![image](https://user-images.githubusercontent.com/36242392/39124293-37a33848-46fb-11e8-8a1e-354a9faa7707.png)

We have tried both port 21 (FTP/FTPS) and port 22 (sFTP) because of the answer in https://github.com/scandihealth/lpr3-docs/issues/21.

We have also performed a full port scan:

> C:\WINDOWS\system32>nmap -p- lpr2indberet-test.sds.dsdn.dk
> Starting Nmap 7.60 ( https://nmap.org ) at 2018-04-23 13:12 Romance Daylight Time
> Nmap scan report for lpr2indberet-test.sds.dsdn.dk (195.80.246.241)
> Host is up (0.013s latency).
> Not shown: 65533 filtered ports
> PORT    STATE SERVICE
> 80/tcp  open  http
> 443/tcp open  https
> Nmap done: 1 IP address (1 host up) scanned in 106.07 seconds

Looks like only the HTTP and HTTPS ports are open - no FTP ports on sftp://lpr2indberet-test.sds.dsdn.dk.

**Comment by jonigkeit** [comment]
The port should be 2222.
I do not think anonymous login is enabled.
Let us get back to you on this.

**Comment by RasmusThernoe** [comment]
Resolved - connected to ftp folder.

Cause: No information provided regarding which sundhedsdatanetaftale to use in order to access the accumulated error list and how to require a password for the ftp.
