### ISSUE TITLE
Interface guide not updated and incorrect: Accumulated Error List

### ISSUE THREAD

**Issue by RasmusThernoe** [scandihealth/lpr3-docs#98]
The interface guide (https://scandihealth.github.io/lpr3-docs/index.html) is not updated with any information regarding the new JSON format used by the accumulated error list - delivered in UL4.

On the contrary the interface guide describes the format (accessible by sFTP) as "ebXML-format as used in IHE XDR" - which is incorrect.

We need the interface guide to be updated as we are developing and testing the parts of our implementation that use the accumulated error list.

**Comment by jonigkeit** [comment]
@RasmusThernoe the documentation should be updated as of push [Updated link.](https://github.com/scandihealth/lpr3-docs/commit/f7ff0485205118bb50e7bca6db2404366e0579df)

**Comment by RasmusThernoe** [comment]
Thank you for the update.
