### ISSUE TITLE
FTP server for accumulated error list does not support FTP/FTPS

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#99]
**This is a blocking issue for us.**

When I try to connect to "lpr2indberet-test.sds.dsdn.dk" on port 2222 with a FTP client I get the following error:
```
ftp> open lpr2indberet-test.sds.dsdn.dk 2222
Connected to lpr2indberet-test.sds.dsdn.dk.
SSH-2.0-CerberusFTPServer_8.0
Connection closed by remote host.
```
It looks like the service is running as SFTP (FTP over SSH) and not FTPS (FTP over SSL) which we actually asked about in issue #21 where we got the following answer:
> Der er tale om S-FTP, FTP-SSL, FTPS, eller FTP Secure

**Comment by jkiddo** [comment]
See comment from #21

**Comment by RasmusThernoe** [comment]
Closed.
